### ISSUE TITLE
adafactor crashes at start

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#104]
I changed a few lines so the line number might be a little off.
adam and dadapt works fine with same training parameters.

error:

2023-09-07 16:10:40,622 [DEBUG] Starting into epoch 0 out of 0, final epoch will be 100
Steps:   0%|                                                                                                          | 0/1000 [00:05<?, ?it/s, lr=0, step_loss=0.153]Traceback (most recent call last):
  File "/root/SimpleTuner/train_sdxl.py", line 1410, in <module>
    main()
  File "/root/SimpleTuner/train_sdxl.py", line 1090, in main
    optimizer.step()
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/optimizer.py", line 142, in step
    self.optimizer.step(closure)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/optimization.py", line 694, in step
    lr = self._get_lr(group, state)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/optimization.py", line 617, in _get_lr
    param_scale = max(param_group["eps"][1], param_state["RMS"])
TypeError: 'float' object is not subscriptable
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 🚀 View run b6-ada at: https://wandb.ai/zhuliyi0/sptnr-sdxl-lvchengguiyuxi-768/runs/gyc6xmt6
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230907_161034-gyc6xmt6/logs
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 256, in check_network_status
    self._loop_check_status(
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 212, in _loop_check_status
    local_handle = request()
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 864, in deliver_network_status
    return self._deliver_network_status(status)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 610, in _deliver_network_status
    return self._deliver_record(record)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 569, in _deliver_record
    handle = mailbox._deliver_record(record, interface=self)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
    interface._publish(record)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-09-07 16:10:56,140 [DEBUG] Incremented Retry for (url='/api/4504800232407040/envelope/'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-09-07 16:10:56,141 [WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)'))': /api/4504800232407040/envelope/
2023-09-07 16:10:56,560 [DEBUG] Incremented Retry for (url='/api/4504800232407040/envelope/'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2023-09-07 16:10:56,560 [WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)'))': /api/4504800232407040/envelope/
2023-09-07 16:10:57,359 [DEBUG] Incremented Retry for (url='/api/4504800232407040/envelope/'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2023-09-07 16:10:57,359 [WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)'))': /api/4504800232407040/envelope/
Traceback (most recent call last):
  File "/root/miniconda3/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python', '/root/SimpleTuner/train_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--resolution=768', '--use_adafactor_optimizer', '--learning_rate=1', '--noise_offset=0.1', '--snr_gamma=5.0', '--seed=-1', '--use_ema', '--enable_xformers_memory_efficient_attention', '--set_grads_to_none', '--freeze_encoder', '--gradient_checkpointing', '--instance_data_dir=/root/autodl-tmp/Dataset/lvchengguiyuxi', '--num_train_epochs=100', '--random_flip', '--train_batch=3', '--gradient_accumulation_steps=2', '--caption_dropout_probability=0.05', '--caption_strategy=textfile', '--input_pertubation=0.1', '--use_original_images=false', '--validation_guidance=7', '--validation_guidance_rescale=0', '--validation_steps=20', '--validation_resolution=1024', '--num_validation_images=1', '--validation_prompt=a photo of a lvchengguiyuxi style high-rise building, lawn, tree, wall, clear sky', '--checkpointing_steps=1000', '--checkpoints_total_limit=1', '--tracker_project_name=sptnr-sdxl-lvchengguiyuxi-768', '--tracker_run_name=b6-ada', '--output_dir=/root/autodl-tmp/simpletunerOutput/lvchengguiyuxi-768-b6-ada', '--seen_state_path=/root/autodl-tmp/simpletunerOutput/training_images_seen.json', '--state_path=/root/autodl-tmp/simpletunerOutput/training_state.json']' returned non-zero exit status 1.

**Comment by zhuliyi0** [comment]
and my setting:

accelerate launch --mixed_precision="bf16" \
	--num_processes="1" \
	--num_machines="1" \
	--dynamo_backend="no" \
/root/SimpleTuner/train_sdxl.py \
	--pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
	--resolution="768" \
    --use_adafactor_optimizer \
	--learning_rate="1" \
    --noise_offset=0.1 \
    --snr_gamma=5.0 \
	--seed=-1 \
	--use_ema \
    --enable_xformers_memory_efficient_attention \
    --set_grads_to_none \
    --freeze_encoder \
    --gradient_checkpointing \
	--instance_data_dir="/root/autodl-tmp/Dataset/lvchengguiyuxi" \
	--num_train_epochs="100" \
	--random_flip \
	--train_batch="3" \
	--gradient_accumulation_steps="2" \
	--caption_dropout_probability=0.05 \
    --caption_strategy="textfile" \
    --input_pertubation=0.1 \
    --use_original_images="false" \
	--validation_guidance="7" \
	--validation_guidance_rescale="0" \
	--validation_steps="20" \
	--validation_resolution="1024" \
	--num_validation_images=1 \
	--validation_prompt="a photo of a lvchengguiyuxi style high-rise building, lawn, tree, wall, clear sky" \
	--checkpointing_steps="1000" \
	--checkpoints_total_limit="1" \
    --tracker_project_name="sptnr-sdxl-lvchengguiyuxi-768" \
	--tracker_run_name="b6-ada" \
	--output_dir="/root/autodl-tmp/simpletunerOutput/lvchengguiyuxi-768-b6-ada" \
	--seen_state_path="/root/autodl-tmp/simpletunerOutput/training_images_seen.json" \
	--state_path="/root/autodl-tmp/simpletunerOutput/training_state.json"

**Comment by zhuliyi0** [comment]
well actually dadapt outputs noise, not working either.

**Comment by zhuliyi0** [comment]
@bghira  I really appreciate your quick responce, but please feel no pressure to fix things. These are more of a documentation of bugs and some suggestions while I experiment.

**Comment by bghira** [comment]
Adafactor really needs some more attention, but Dadaptation shouldn't output pure noise.

I've done a full model conversion to V-pred with Dadaptation, though maybe it's version-specific.

However, Adafactor was added for #27 and #46 and wasn't really tested beyond seeing whether it helped with a 24G GPU to run training (it didn't)

if it's not too much to ask, maybe you can make a minimal reproducer script with the issue, and if it still happens I would assume it's an upstream bug.

**Comment by zhuliyi0** [comment]
I tried to reproduce it on lastest release, this time a difference error when validation start:

Traceback (most recent call last):
  File "/root/SimpleTuner/train_sdxl.py", line 1460, in <module>
    main()
  File "/root/SimpleTuner/train_sdxl.py", line 1144, in main
    optimizer.step()
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/optimizer.py", line 142, in step
    self.optimizer.step(closure)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/optimization.py", line 694, in step
    lr = self._get_lr(group, state)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/optimization.py", line 617, in _get_lr
    param_scale = max(param_group["eps"][1], param_state["RMS"])
TypeError: 'float' object is not subscriptable

the setting:

accelerate launch --mixed_precision="bf16" \
	--num_processes="1" \
	--num_machines="1" \
	--dynamo_backend="no" \
/root/SimpleTuner/train_sdxl.py \
	--pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
	--resolution="640" \
	--learning_rate="1" \
	--seed=-1 \
	--use_adafactor_optimizer \
    --freeze_encoder \
	--instance_data_dir="/root/autodl-tmp/Dataset/test2" \
	--num_train_epochs="10" \
	--train_batch="1" \
	--gradient_accumulation_steps="1" \
	--caption_dropout_probability=0.3 \
    --minimum_image_size=768 \
    --delete_unwanted_images \
    --caption_strategy="filename" \
    --input_pertubation=0.1 \
    --use_original_images="false" \
	--validation_guidance="7" \
	--validation_guidance_rescale="0" \
	--validation_steps="2" \
	--validation_resolution="1024" \
	--num_validation_images=1 \
	--validation_prompt="a modern office building with a glass facade and a cloudy sky in the background" \
	--checkpointing_steps="1000" \
	--checkpoints_total_limit="1" \
--tracker_project_name="sptnr-sdxl-test" \
	--tracker_run_name="b6-1e5-drop03" \
--output_dir="/root/autodl-tmp/simpletunerOutput/arch3k-test" \
    --report_to="tensorboard" \
	--seen_state_path="/root/autodl-tmp/simpletunerOutput/training_images_seen.json" \
	--state_path="/root/autodl-tmp/simpletunerOutput/training_state.json"	

If I change --use_adafactor_optimizer back to --use_8bit_adam, the error is gone.

**Comment by zhuliyi0** [comment]
I will try to do that when I am good enough to impletement a short script all by myself. For now I will stick to good ol' adam. You can close this issue if you want. Thanks.

**Comment by bghira** [comment]
It's fixed in v0.6.0 but I really don't trust or like that optimizer. I don't think it works very well. The loss would spike up to 15..
