### ISSUE TITLE
Docker: Missing Dependencies

### ISSUE THREAD

**Issue by Putzzmunta** [bghira/SimpleTuner#1077]
Hi,
tried the Dockersetup today, it seems that there are Dependencies missing.

i followed the setup guide. The Exception occurs, when trying to run 'train.sh'

```
  - Downgrading lycoris-lora (3.1.0 258387f -> 3.0.1.dev14 258387f)
Accelerate config file not found: /root/.cache/huggingface/accelerate/default_config.yaml. Using values from config.env.
INFO:root:lm_eval is not installed, GPTQ may not be usable
An error occurred while importing OpenCV2 due to a missing LibGL dependency on your system or container. Unfortunately, this is not a dependency that SimpleTuner can include during install time.
For Ubuntu systems, you can typically resolve this by running the following command:
sudo apt-get install libgl1-mesa-glx
or, if that does not work:
sudo apt-get install libgl1-mesa-dri
If all else fails, you may need to contact the support department for your chosen platform. You can find the full error message at the end of debug.log inside the SimpleTuner directory.
Traceback (most recent call last):
  File "/workspace/SimpleTuner/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1174, in launch_command
    simple_launcher(args)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 769, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/SimpleTuner/.venv/bin/python', 'train.py']' returned non-zero exit status 1.
```

**Comment by Putzzmunta** [comment]
I fixed it. By modifying the Dockerfile. Here: https://stackoverflow.com/questions/63889102/unable-to-run-docker-image-due-to-libgl-error is a similar Issue reported.
My Dockerfile contains these additional lines (14-18):
```
RUN apt-get update -y
RUN apt install libgl1-mesa-glx -y
RUN apt-get install 'ffmpeg'\
    'libsm6'\
    'libxext6'  -y
```

**Comment by Putzzmunta** [comment]
@barakyo Are you interested in a PR?

**Comment by bghira** [comment]
i believe it's @komninoschatzipapas

**Comment by komninoschatzipapas** [comment]
@Putzzmunta  Feel free to open a PR. I haven't updated the Dockerfile in a bit. The update command isn't necessary though since that aleady exists.

**Comment by PsychoLogicAu** [comment]
@komninoschatzipapas is the Dockerfile used much? I have some changes on my fork, and an added a docker compose I use locally which I could contribute

**Comment by Putzzmunta** [comment]
Here is this PR:  #1126
