### ISSUE TITLE
wandb error on second run

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#108]
Got this error after I pulled the lastest release branch. The first run was running ok, I killed it with ctrl-c, and the second run on the same dataset will always error:

wandb: ERROR Attempted to change value of key "seed" from 941387699 to 1008619276
wandb: ERROR If you really want to do this, pass allow_val_change=True to config.update()
Traceback (most recent call last):
  File "/root/SimpleTuner/train_sdxl.py", line 1460, in <module>
    main()
  File "/root/SimpleTuner/train_sdxl.py", line 867, in main
    accelerator.init_trackers(
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 602, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 2205, in init_trackers
    tracker.store_init_configuration(config)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/tracking.py", line 86, in execute_on_main_process
    return function(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/tracking.py", line 316, in store_init_configuration
    wandb.config.update(values)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 184, in update
    sanitized = self._update(d, allow_val_change)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 237, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 258, in _sanitize
    raise config_util.ConfigError(
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "seed" from 941387699 to 1008619276
If you really want to do this, pass allow_val_change=True to config.update()
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.

**Comment by bghira** [comment]
this relates to the change we made for your wandb project / run name fix. i also took a whack at this one, but it seems like the value it recommends i pass in gets ignored. a new training run name would be needed to bypass that.

**Comment by bghira** [comment]
alternatively, set the --seed to that 'from' value

**Comment by zhuliyi0** [comment]
ok that was my bad, I was running a different version from what I suggested:

```
        accelerator.init_trackers(
            args.tracker_project_name,
            config=vars(public_args),
            init_kwargs={
                "wandb":
                {
                    "name": args.tracker_run_name,
                }
            },
        )
```

No id specified. this allows multiple runs with same name on Wandb. Messy but who cares..

**Comment by bghira** [comment]
used a hash of the args instead. it'll reuse the same one if the params don't change!
