### ISSUE TITLE
training the model and problem with connecting to huggingface

### ISSUE THREAD

**Issue by mmitchef** [bghira/SimpleTuner#1127]
Hello, thanks for sharing the code. I am trying to follow up the steps here [](https://github.com/bghira/SimpleTuner/blob/main/documentation/quickstart/FLUX.md ) but I am getting this problem even though I login into wandb and huggingface-cli.
thanks for any quidance.

`black-forest-labs/FLUX.1-dev is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `token` or log in with `huggingface-cli login`.
Traceback (most recent call last):
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/scheduler/scheduler_config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/configuration_utils.py", line 379, in load_config
    config_file = hf_hub_download(
                  ^^^^^^^^^^^^^^^^
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1484, in _raise_on_head_call_error
    raise head_call_error
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 301, in _request_wrapper
    hf_raise_for_status(response)
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 423, in hf_raise_for_status
    raise _format(GatedRepoError, message, response) from e
huggingface_hub.errors.GatedRepoError: 403 Client Error. (Request ID: Root=1-672ce79f-25371f931ed9d1fc67c0bea8;a3baf1dd-e365-48cb-a7ef-d352dc9460a7)

Cannot access gated repo for url https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/scheduler/scheduler_config.json.
Access to model black-forest-labs/FLUX.1-dev is restricted and you are not in the authorized list. Visit https://huggingface.co/black-forest-labs/FLUX.1-dev to ask for access.

During handling of the above exception, another exception occurred:
wandb
Traceback (most recent call last):
  File "/usr/SimpleTuner/train.py", line 22, in <module>
    trainer = Trainer()
              ^^^^^^^^^
  File "/usr/SimpleTuner/helpers/training/trainer.py", line 164, in __init__
    self.parse_arguments(args=config, disable_accelerator=disable_accelerator)
  File "/usr/SimpleTuner/helpers/training/trainer.py", line 218, in parse_arguments
    self.init_noise_schedule()
  File "/usr/SimpleTuner/helpers/training/trainer.py", line 290, in init_noise_schedule
    self.config, _flow_matching, self.noise_scheduler = load_scheduler_from_args(
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/SimpleTuner/helpers/training/schedulers.py", line 20, in load_scheduler_from_args
    noise_scheduler = FlowMatchEulerDiscreteScheduler.from_pretrained(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/schedulers/scheduling_utils.py", line 150, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
                                  ^^^^^^^^^^^^^^^^
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/configuration_utils.py", line 394, in load_config
    raise EnvironmentError(
OSError: black-forest-labs/FLUX.1-dev is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `token` or log in with `huggingface-cli login`.

`

**Comment by bghira** [comment]
see in the console output early-ish on where it says what account you are logged in as and make sure that account has access to the gated repository

**Comment by bghira** [comment]
check in the simpletuner debug.log file in its directory where you ran it from and toward the top where it is initialising it tells you whether you are logged into hugging face hub or not - i think it might not show this if you are not pushing checkpoints to the hub, however.

**Comment by mmitchef** [comment]
Thanks, I checked it, seems I am not pushing checkpoint

**Comment by mmitchef** [comment]
Ok, I changed this into config file and got another error. Will chcek to see if I can solve it. Thank you so much.

**Comment by mmitchef** [comment]
I got this new error 
`Accelerate config file not found: /home/mmitchef/.cache/huggingface/accelerate/default_config.yaml. Using values from config.env.
INFO:root:lm_eval is not installed, GPTQ may not be usable
2024-11-07 12:19:39,805 [INFO] Using json configuration backend.
2024-11-07 12:19:39,805 [INFO] [CONFIG.JSON] Loaded configuration from config/config.json
2024-11-07 12:19:39,805 [WARNING] Skipping false argument: --disable_benchmark
2024-11-07 12:19:39,805 [WARNING] Skipping false argument: --validation_torch_compile
--resume_from_checkpoint=latest
--data_backend_config=config/multidatabackend.json
--aspect_bucket_rounding=2
--seed=42
--minimum_image_size=0
--output_dir=output/models
--lora_type=standard
--lora_rank=16
--max_train_steps=10000
--num_train_epochs=0
--checkpointing_steps=500
--checkpoints_total_limit=5
--hub_model_id=checkflux
--push_to_hub
--push_checkpoints_to_hub
--model_card_safe_for_work
--tracker_project_name=lora-training
--tracker_run_name=simpletuner-lora
--report_to=wandb
--model_type=lora
--pretrained_model_name_or_path=black-forest-labs/FLUX.1-dev
--model_family=flux
--train_batch_size=1
--gradient_checkpointing
--caption_dropout_probability=0.0
--resolution_type=pixel_area
--resolution=1024
--validation_seed=42
--validation_steps=500
--validation_resolution=1024x1024
--validation_guidance=3.0
--validation_guidance_rescale=0.0
--validation_num_inference_steps=20
--validation_prompt=A photo-realistic image of a cat
--disable_tf32
--mixed_precision=bf16
--optimizer=adamw_bf16
--learning_rate=1e-4
--lr_scheduler=polynomial
--lr_warmup_steps=100
2024-11-07 12:19:39,808 [WARNING] The VAE model madebyollin/sdxl-vae-fp16-fix is not compatible. Please use a compatible VAE to eliminate this warning. The baked-in VAE will be used, instead.
2024-11-07 12:19:39,808 [INFO] VAE Model: black-forest-labs/FLUX.1-dev
2024-11-07 12:19:39,809 [INFO] Default VAE Cache location: 
2024-11-07 12:19:39,809 [INFO] Text Cache location: cache
2024-11-07 12:19:39,809 [WARNING] Updating T5 XXL tokeniser max length to 512 for Flux.
2024-11-07 12:19:39,809 [WARNING] --disable_tf32 is provided, not enabling. Training will potentially be much slower.
black-forest-labs/FLUX.1-dev is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `token` or log in with `huggingface-cli login`.
Traceback (most recent call last):
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/scheduler/scheduler_config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/configuration_utils.py", line 379, in load_config
    config_file = hf_hub_download(
                  ^^^^^^^^^^^^^^^^
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1484, in _raise_on_head_call_error
    raise head_call_error
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 301, in _request_wrapper
    hf_raise_for_status(response)
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 423, in hf_raise_for_status
    raise _format(GatedRepoError, message, response) from e
huggingface_hub.errors.GatedRepoError: 403 Client Error. (Request ID: Root=1-672cf550-6f1803924e5582c86820418b;6d5b3ffc-9ce1-47bc-817a-91cf03ac1287)

Cannot access gated repo for url https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/scheduler/scheduler_config.json.
Access to model black-forest-labs/FLUX.1-dev is restricted and you are not in the authorized list. Visit https://huggingface.co/black-forest-labs/FLUX.1-dev to ask for access.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data1/mmitchef/SimpleTuner/train.py", line 22, in <module>
    trainer = Trainer()
              ^^^^^^^^^
  File "/data1/mmitchef/SimpleTuner/helpers/training/trainer.py", line 164, in __init__
    self.parse_arguments(args=config, disable_accelerator=disable_accelerator)
  File "/data1/mmitchef/SimpleTuner/helpers/training/trainer.py", line 218, in parse_arguments
    self.init_noise_schedule()
  File "/data1/mmitchef/SimpleTuner/helpers/training/trainer.py", line 290, in init_noise_schedule
    self.config, _flow_matching, self.noise_scheduler = load_scheduler_from_args(
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/mmitchef/SimpleTuner/helpers/training/schedulers.py", line 20, in load_scheduler_from_args
    noise_scheduler = FlowMatchEulerDiscreteScheduler.from_pretrained(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/schedulers/scheduling_utils.py", line 150, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
                                  ^^^^^^^^^^^^^^^^
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data1/mmitchef/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/configuration_utils.py", line 394, in load_config
    raise EnvironmentError(
OSError: black-forest-labs/FLUX.1-dev is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `token` or log in with `huggingface-cli login`.
`

**Comment by bghira** [comment]
you will have to identify why your huggingface token is not working or detected by the trainer, there isn't much special going on there
