### ISSUE TITLE
transformer version problem

### ISSUE THREAD

**Issue by mobilejammer** [bghira/SimpleTuner#1239]
when I use the 4.47.1 version occur:
 File "/home/ubuntu/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: 'weight' must be 2-D

when down the version to  4.31.0 as https://github.com/huggingface/transformers/issues/24643 "RuntimeError: 'weight' must be 2-D" training with DeepSpeed 
run train.sh the same problem and new problem accur

**Comment by mobilejammer** [comment]
> well, if you come up with the fix, let me know. i am unable to reproduce the issue locally.

give you a star! flux-dev full parameter funetune, use deep speed, this problem occur.

**Comment by bghira** [comment]
then the bug is upstream

**Comment by mobilejammer** [comment]
> it seems to be that you're using stage ZeRO 3 but this is a really flaky level of DeepSpeed that has to be explicitly supported by Diffusers, and this doesn't seem to be the case for Flux.
> 
> the upstream recommendation is to use the `deepspeed_zero_init_disabled_context_manager` context manager to load models that should not be sharded, but we're not even keeping the text encoders or VAE loaded through training.
> 
> so the "weight must be 2D" error is coming from Flux's embedding layer.
> 
> you can of course decide not to train the embedding layer, which will require hacking trainer.py to remove, and this will not be a supported option, where you are then on your own.
> 
> the only real solution is to reduce to zero 2 and/or use a larger GPU.

do this project support fsdp

**Comment by bghira** [comment]
not really, no. we use deepspeed for it.

**Comment by bghira** [comment]
i managed to work around this for zero3 in the main branch, by disabling deepspeed when we load the text encoders. please test

**Comment by bghira** [comment]
my personal machine w/ a 4090 that i've tested this on has 128G ram and a 7800X3D but it runs into these weird kernel errors when it is running.

it happens in many other cases too, so it's probably here a defective GPU or power delivery problems. but i thought i'd give a heads up that when running deepspeed with constrained GPU memory there may be some CUDA memory allocation failures.

**Comment by mobilejammer** [comment]
when I use fsdp to run multi-machine multi-gpu training, 200steps run success but runtime error 

RuntimeError: Detected mismatch between collectives on ranks. Rank 6 is running collective: CollectiveFingerPrint(SequenceNumber=35724OpType=BARRIER), but Rank 0 is running collective: CollectiveFingerPrint(SequenceNumber=0OpType=GATHER).Collectives differ in the following aspects:     Sequence number: 35724vs 0  Op type: BARRIERvs GATHER

Traceback (most recent call last):
  File "/home/ubuntu/SimpleTuner/train.py", line 107, in <module>
    trainer.train()
  File "/home/ubuntu/SimpleTuner/helpers/training/trainer.py", line 2976, in train
    self.accelerator.wait_for_everyone()
  File "/home/ubuntu/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 2659, in wait_for_everyone
    wait_for_everyone()
  File "/home/ubuntu/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/utils/other.py", line 144, in wait_for_everyone
    PartialState().wait_for_everyone()
  File "/home/ubuntu/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 375, in wait_for_everyone
    torch.distributed.barrier()
  File "/home/ubuntu/SimpleTuner/.venv/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/SimpleTuner/.venv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 4159, in barrier
    work = group.barrier(opts=opts)
RuntimeError: Detected mismatch between collectives on ranks. Rank 4 is running collective: CollectiveFingerPrint(SequenceNumber=35724OpType=BARRIER), but Rank 0 is running collective: CollectiveFingerPrint(SequenceNumber=0OpType=GATHER).Collectives differ in the following aspects:     Sequence number: 35724vs 0  Op type: BARRIERvs GATHER

**Comment by bghira** [comment]
no idea. you are on your own with torch FSDP or FSDP2.
