### ISSUE TITLE
error when trying to resume from checkpoint

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#127]
```
Resuming from checkpoint backup-checkpoint-3000
path: backup-checkpoint-3000
output dir: /root/autodl-tmp/simpletunerOutput/goa5cats-768-b6-1e5-drop01
load from: /root/autodl-tmp/simpletunerOutput/goa5cats-768-b6-1e5-drop01/backup-checkpoint-3000
The config attributes {'decay': 0.9999, 'inv_gamma': 1.0, 'min_decay': 0.0, 'optimization_step': 3000, 'power': 0.6666666666666666, 'update_after_step': 0, 'use_ema_warmup': False} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Traceback (most recent call last):
  File "/root/SimpleTuner/train_sdxl.py", line 1478, in <module>
    main()
  File "/root/SimpleTuner/train_sdxl.py", line 943, in main
    global_step = int(path.split("-")[1])
ValueError: invalid literal for int() with base 10: 'checkpoint'
```

I used the exact same settings from previous training to resume from. Actually I was trying to save a pipeline from this checkpoint for inference, is this the only way?

**Comment by bghira** [comment]
your path has two `-` characters in it. rename it to `checkpoint-3000`

**Comment by zhuliyi0** [comment]
that shouldn't matter, does it? It is a valid path and the script was loading the checkpoint before error.

**Comment by zhuliyi0** [comment]
oh I see what you mean after looking at that line of code.

**Comment by bghira** [comment]
it is indeed something that can be improved but it's pretty easily worked around, maybe you can open a PR?
