### ISSUE TITLE
error when training on image that has black padding

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#132]
I am training a small dataset with couple hundreds of images with various aspect ratios. SimpleTuner will discard a quarter of them if batch set to 8 or something like that. To reduce number of aspect buckets, I padded some training image with black border (is this a good way?). Now I get this error, which will go away if I remove all images with black border:

```
2023-09-14 18:55:30,591 [INFO] ***** Running training *****
2023-09-14 18:55:30,591 [INFO]   Num examples = 8
2023-09-14 18:55:30,591 [INFO]   Num Epochs = 100
2023-09-14 18:55:30,591 [INFO]   Instantaneous batch size per device = 2
2023-09-14 18:55:30,591 [INFO]   Total train batch size (w. parallel, distributed & accumulation) = 4
2023-09-14 18:55:30,592 [INFO]   Gradient Accumulation steps = 2
2023-09-14 18:55:30,592 [INFO]   Total optimization steps = 200
Steps:   0%|                                                                                                                                                                     | 0/200 [00:00<?, ?it/s]2023-09-14 18:55:30,592 [DEBUG] Starting into epoch 0 out of 0, final epoch will be 100
Steps:   0%|                                                                                                                                           | 0/200 [00:01<?, ?it/s, lr=1e-5, step_loss=0.214]Traceback (most recent call last):
  File "/root/SimpleTuner/train_sdxl.py", line 1477, in <module>
    main()
  File "/root/SimpleTuner/train_sdxl.py", line 982, in main
    for step, batch in enumerate(train_dataloader):
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/data_loader.py", line 394, in __iter__
    next_batch = next(dataloader_iter)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/root/SimpleTuner/train_sdxl.py", line 545, in <lambda>
    collate_fn=lambda examples: collate_fn(examples),
  File "/root/SimpleTuner/train_sdxl.py", line 486, in collate_fn
    pixel_values = torch.stack(latents)
RuntimeError: stack expects each tensor to be equal size, but got [4, 64, 71] at entry 0 and [4, 64, 64] at entry 1

```

This is a test run of 8 images, 2 of them has black padding. If I remove these 2, this error goes away.

**Comment by zhuliyi0** [comment]
the dataset, if it helps to pin it down:

https://drive.google.com/file/d/1iydce2EJG2q_wu5aEfSmvMLmFeDLYtyW/view?usp=drive_link

**Comment by bghira** [comment]
did you remove the contents of vae_cache after resizing the images?

**Comment by bghira** [comment]
for what its worth;

* the trainer does not audit the vae cache. if you change the contents, it will mess up. the aspect bucket will be corrected, but the vae cache entry will not.
* having black padding isn't necessarily the best solution. you might want to just crop your images.
* black padding shouldn't cause tensor issues

**Comment by zhuliyi0** [comment]
you are right it is vae cache. removed it and it now runs smoothly. thanks.
