### ISSUE TITLE
KeyError: '0.57' when enforcing minimum image size of 768.

### ISSUE THREAD

**Issue by roperi** [bghira/SimpleTuner#240]
dataset : 220 images at around 1024x1024 resolution
training resolution: 768

```
2023-12-15 14:14:13,143 [WARNING] (BucketManager) Removed bucket 0.57 due to insufficient samples.
2023-12-15 14:14:13,143 [INFO] (BucketManager) Enforcing minimum image size of 768. This could take a while for very-large datasets.
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1426, in <module>
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 307, in main
    bucket_manager.refresh_buckets(rank_info())
  File "/workspace/SimpleTuner/helpers/multiaspect/bucket.py", line 386, in refresh_buckets
    self.compute_aspect_ratio_bucket_indices()
  File "/workspace/SimpleTuner/helpers/multiaspect/bucket.py", line 297, in compute_aspect_ratio_bucket_indices
    self._save_cache(enforce_constraints=True)
  File "/workspace/SimpleTuner/helpers/multiaspect/bucket.py", line 128, in _save_cache
    self._enforce_min_bucket_size()
  File "/workspace/SimpleTuner/helpers/multiaspect/bucket.py", line 404, in _enforce_min_bucket_size
    self._enforce_resolution_constraints(bucket)
  File "/workspace/SimpleTuner/helpers/multiaspect/bucket.py", line 425, in _enforce_resolution_constraints
    images = self.aspect_ratio_bucket_indices[bucket]
KeyError: '0.57'

```

**Comment by bghira** [comment]
a workaround is to use `--crop=true --crop_style=random`

**Comment by bghira** [comment]
v0.8.1 includes a fix for this

**Comment by bghira** [comment]
hmm, seems like i needed to do a second fix for this one too. i created a dataset with insufficient samples in a bucket for testing and was able to reproduce it. the main branch... has it working
