### ISSUE TITLE
metadata not found warning and tensor size mismatch error when processing bucket

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#299]
See attached log.  I am training on1k+ images with single GPU, only some of them gave warning and error. The issue is on latest release branch. The old branch from about 5 month ago is running normally on the same dataset. 

[log.txt](https://github.com/bghira/SimpleTuner/files/14177349/log.txt)

and here is data config json file:

[data_config.json](https://github.com/bghira/SimpleTuner/files/14177437/data_config.json)

**Comment by zhuliyi0** [comment]
then training crashed at step 1 with this error:

Epoch 1/1 Steps:   0%|                                                                                | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/SimpleTuner/train_sdxl.py", line 1523, in <module>
    main()
  File "/root/SimpleTuner/train_sdxl.py", line 1028, in main
    for step, batch in random_dataloader_iterator(train_backends):
  File "/root/SimpleTuner/helpers/data_backend/factory.py", line 670, in random_dataloader_iterator
    yield (step, next(chosen_iter))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 676, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 623, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 254, in __iter__
    for idx in self.sampler:
  File "/root/SimpleTuner/helpers/multiaspect/sampler.py", line 339, in __iter__
    to_yield = self._validate_and_yield_images_from_samples(
  File "/root/SimpleTuner/helpers/multiaspect/sampler.py", line 289, in _validate_and_yield_images_from_samples
    if "crop_coordinates" not in image_metadata:
TypeError: argument of type 'NoneType' is not iterable

**Comment by bghira** [comment]
was this dataset in use from the prior release, eg. v0.8? even earlier v0.9 versions will be incompatible.

it **looks** like the bucket cache reload was a no-op, which might happen when everything is already cached. but we've got more metadata now... anyway, that's just a guess. SIMPLETUNER_LOG_LEVEL=DEBUG might be more elucidating

**Comment by bghira** [comment]
the solution if it's a version compat issue is to remove the .json files from the data root dir

**Comment by zhuliyi0** [comment]
yes removing json file fixed it. Thanks.
