### ISSUE TITLE
RuntimeError: Input type (float) and bias type (c10::BFloat16) should be the same

### ISSUE THREAD

**Issue by komninoschatzipapas** [bghira/SimpleTuner#356]
I'm getting an error when running validation on my SDXL model:

```
Loaded scheduler as DDPMScheduler from `scheduler` subfolder of orionsoftware/juggernaut-XL-v9.                                                                                                                                                        | 0/5 [00:00<?, ?it/s]
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 685.39it/s]
Model weights saved in /workspace/output/pipeline/vae/diffusion_pytorch_model.safetensors
Model weights saved in /workspace/output/pipeline/unet/diffusion_pytorch_model.safetensors
2024-04-19 16:46:24,120 [INFO] (validation) Running validation... 
 Generating 2 images.
                                                                                                                             Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1633, in <module>                                                        
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 1560, in main
    log_validations(
  File "/workspace/SimpleTuner/helpers/legacy/validation.py", line 352, in log_validations
    pipeline(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 1245, in __call__
    image = self.vae.decode(latents, return_dict=False)[0]
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 304, in decode
    decoded = self._decode(z).sample
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 274, in _decode
    z = self.post_quant_conv(z)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (float) and bias type (c10::BFloat16) should be the same
wandb: / 0.100 MB of 0.100 MB uploaded (0.002 MB deduped)
wandb: Run history:
wandb:             epoch ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:     learning_rate ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇███
wandb: optimization_loss ▄▄▂▅▄█▅▂▃▃▂▁▃▃▅▄▆▆▆▇▂▃▄▆▃▄▁▄▂▄▁▅▄▄▃▆▄▆▇▂
wandb:        train_loss ▄▄▂▅▄█▅▂▃▃▂▁▃▃▅▄▆▆▆▇▂▃▄▆▃▄▁▄▂▄▁▅▄▄▃▆▄▆▇▂
wandb:   train_luminance ▄▆▃▇█▂▅▅▄▁▆▆▂▃▅▅▅█▂▄▃▆▅▄▆▄█▂▆▅▆▂▃▆▃▃▆▁▄█
wandb: 
wandb: Run summary:
wandb:             epoch 1
wandb:     learning_rate 0.0
wandb: optimization_loss 0.12789
wandb:        train_loss 0.12789
wandb:   train_luminance 147.21747
wandb: 
wandb: 🚀 View run simpletuner-sdxl at: redacted
wandb: Synced 5 W&B file(s), 57 media file(s), 59 artifact file(s) and 0 other file(s)
wandb: Find logs at: redacted
Traceback (most recent call last):
  File "/workspace/SimpleTuner/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1023, in launch_command
    simple_launcher(args)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 643, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/SimpleTuner/.venv/bin/python', 'train_sdxl.py', '--model_type=full', '--pretrained_model_name_or_path=orionsoftware/juggernaut-XL-v9', '--enable_xformers_memory_efficient_attention', '--gradient_checkpointing', '--set_grads_to_none', '--gradient_accumulation_steps=1', '--resume_from_checkpoint=latest', '--snr_gamma=5', '--data_backend_config=/workspace/multidatabackend.json', '--num_train_epochs=1', '--max_train_steps=0', '--metadata_update_interval=65', '--adam_bfloat16', '--learning_rate=8e-7', '--lr_scheduler=polynomial', '--seed', '-1', '--lr_warmup_steps=1000', '--output_dir=/workspace/output', '--inference_scheduler_timestep_spacing=trailing', '--training_scheduler_timestep_spacing=trailing', '--report_to=wandb', '--allow_tf32', '--mixed_precision=bf16', '--vae_dtype=bf16', '--prediction_type=v_prediction', '--rescale_betas_zero_snr', '--training_scheduler_timestep_spacing=trailing', '--inference_scheduler_timestep_spacing=trailing', '--train_batch=12', '--caption_dropout_probability=0.03', '--validation_prompt=ethnographic photography of teddy bear at a picnic', '--num_validation_images=1', '--validation_num_inference_steps=30', '--validation_seed=42', '--minimum_image_size=832', '--resolution=832', '--validation_resolution=1024', '--resolution_type=pixel', '--checkpointing_steps=150', '--checkpoints_total_limit=2', '--validation_steps=100', '--tracker_run_name=simpletuner-sdxl', '--tracker_project_name=sdxl-training', '--validation_guidance=7.5', '--validation_guidance_rescale=0.0', '--validation_negative_prompt=blurry, cropped, ugly']' returned non-zero exit status 1.
```

I tried both with the default validation settings and by setting my own as such:
```
export VALIDATION_PROMPT="test"
export VALIDATION_GUIDANCE=7.5
export VALIDATION_GUIDANCE_RESCALE=0.7
export VALIDATION_STEPS=100
export VALIDATION_NUM_INFERENCE_STEPS=30
export VALIDATION_SEED=42
export VALIDATION_RESOLUTION=832
```
Both with no luck.

<details>
  <summary>sdxl-env.sh</summary>
export SIMPLETUNER_LOG_LEVEL=DEBUG
export SIMPLETUNER_TRAINING_LOOP_LOG_LEVEL=DEBUG
export MODEL_TYPE='full'
export USE_BITFIT=false
export LEARNING_RATE=8e-7 #@param {type:"number"}
export MODEL_NAME="orionsoftware/juggernaut-XL-v9"

export DEBUG_EXTRA_ARGS="--report_to=wandb"
export TRACKER_PROJECT_NAME="sdxl-training"
export TRACKER_RUN_NAME="simpletuner-sdxl"

export NUM_EPOCHS=1
export MAX_NUM_STEPS=0

export DATALOADER_CONFIG="/workspace/multidatabackend.json"
export OUTPUT_DIR="/workspace/output"

export RESOLUTION=832
export RESOLUTION_TYPE="pixel"
export MINIMUM_RESOLUTION=$RESOLUTION

export TRAIN_BATCH_SIZE=8
export GRADIENT_ACCUMULATION_STEPS=1

export LR_SCHEDULE="polynomial"

export CAPTION_DROPOUT_PROBABILITY=0.03

export METADATA_UPDATE_INTERVAL=65
export VAE_BATCH_SIZE=8

export DELETE_ERRORED_IMAGES=0
export DELETE_SMALL_IMAGES=0

export TRAINING_SCHEDULER_TIMESTEP_SPACING="trailing"
export INFERENCE_SCHEDULER_TIMESTEP_SPACING="trailing"

export MIN_SNR_GAMMA=5

export USE_XFORMERS=true

export USE_GRADIENT_CHECKPOINTING=true

export ALLOW_TF32=true
export OPTIMIZER="adamw_bf16"

export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --prediction_type=v_prediction --rescale_betas_zero_snr"
export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --training_scheduler_timestep_spacing=trailing --inference_scheduler_timestep_spacing=trailing"

export TRAINING_SEED=-1
export MIXED_PRECISION="bf16"
export PURE_BF16=true
export TRAINING_DYNAMO_BACKEND='no'
</details>

**Comment by bghira** [comment]
this is resolved
