### ISSUE TITLE
checkpoint conversion script errors out when text encoder is unavailable

### ISSUE THREAD

**Issue by komninoschatzipapas** [bghira/SimpleTuner#358]
The text encoder is not output by the training script but seems to be required by `convert_sdxl_checkpoint.py`:
```
(.venv) root@a4a009f3dcf3:/workspace/SimpleTuner# tree /workspace/output/pipeline/
/workspace/output/pipeline/
├── model_index.json
├── scheduler
│   └── scheduler_config.json
├── tokenizer
│   ├── merges.txt
│   ├── special_tokens_map.json
│   ├── tokenizer_config.json
│   └── vocab.json
├── tokenizer_2
│   ├── merges.txt
│   ├── special_tokens_map.json
│   ├── tokenizer_config.json
│   └── vocab.json
├── unet
│   ├── config.json
│   └── diffusion_pytorch_model.safetensors
└── vae
    ├── config.json
    └── diffusion_pytorch_model.safetensors

5 directories, 14 files
(.venv) root@a4a009f3dcf3:/workspace/SimpleTuner# python convert_sdxl_checkpoint.py --model_path="/workspace/output/pipeline" --checkpoint_path=/workspace/a.safetensors --half --use_safetensors
Traceback (most recent call last):
  File "/workspace/SimpleTuner/convert_sdxl_checkpoint.py", line 309, in <module>
    text_enc_dict = torch.load(text_enc_path, map_location="cpu")
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/output/pipeline/text_encoder/pytorch_model.bin'
```

**Comment by bghira** [comment]
this is done purposely because:

- at this stage of training, those models are not loaded or available
- the trainer does not tune the text encoder with the full model
- DeepSpeed gets upset when you try loading multiple models, and it hangs

if you'd like to alter the checkpoint conversion script to pull any missing text encoders from their respective hub paths, that'd be i think something worth doing.

**Comment by bghira** [comment]
added option `--save_text_encoder`
