### ISSUE TITLE
 ImportError: libcupti.so.11.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by roperi** [bghira/SimpleTuner#38]
Getting the following error when `bash train_sdxl.sh`

```
bash train_sdxl.sh
Traceback (most recent call last):
  File "/workspace/SimpleTuner/.venv/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 32, in <module>
    import torch
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcupti.so.11.7: cannot open shared object file: No such file or directory

```

Tried this and didn't work
```
export LD_LIBRARY_PATH=/usr/local/cuda-11.8/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=/usr/local/cuda-11.8
```

Using `runpod/pytorch:1.13.0-py3.10-cuda11.7.1-devel` docker image.

**Comment by bghira** [comment]
the `ubuntu.sh` script has the requirements you must install.

**Comment by bghira** [comment]
it looks like you're trying to use cuda_home of 11.8 on an 11.7 image. does that impact things?

**Comment by bghira** [comment]
it seems like an issue with the runpod image. can you try a generic ubuntu 22.04?

**Comment by bghira** [comment]
I do not, you might have to `apt-cache search cuda` and adjust.

**Comment by bghira** [comment]
Use `pytorch/pytorch_2.0.1-cuda11.7-cudnn8-devel/jupyter`.
