### ISSUE TITLE
[ERROR] (__main__) local variable 'webhook_handler' referenced before assignment

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#387]
branch new install, got error:

2024-05-10 09:03:49,075 [INFO] (ArgsParser) VAE Model: madebyollin/sdxl-vae-fp16-fix
2024-05-10 09:03:49,075 [INFO] (ArgsParser) Default VAE Cache location: 
2024-05-10 09:03:49,075 [INFO] (ArgsParser) Text Cache location: cache
2024-05-10 09:03:49,103 [WARNING] (accelerate.utils.other) Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
2024-05-10 09:03:49,111 [INFO] (__main__) Enabling tf32 precision boost for NVIDIA devices due to --allow_tf32.
2024-05-10 09:03:49,111 [INFO] (__main__) Load tokenizers
2024-05-10 09:03:49,343 [INFO] (__main__) Load text encoder 1..
2024-05-10 09:03:49,482 [INFO] (__main__) Load text encoder 2..
2024-05-10 09:03:50,024 [INFO] (__main__) Load VAE..
2024-05-10 09:04:00,293 [INFO] (__main__) Moving models to GPU. Almost there.
2024-05-10 09:04:02,596 [INFO] (__main__) Creating the U-net..
2024-05-10 09:04:02,596 [ERROR] (__main__) local variable 'webhook_handler' referenced before assignment

Resetting git to v0.9.4 fixed it.

**Comment by zhuliyi0** [comment]
I got it run, but the speed is slow, like 10+s/it. So I switched to another linux instance to rule out hardware issue, and this time another error (which is strange, I used the same source version and same training setting):

Write embeds to disk:  15%|█████████▊                                                       | 50/330 [00:02<00:07, 36.55it/s]Token indices sequence length is longer than the specified maximum sequence length for this model (81 > 77). Running this sequence through the model will result in indexing errors
2024-05-10 09:22:30,995 [WARNING] (TextEmbeddingCache) The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['center of image.']
Token indices sequence length is longer than the specified maximum sequence length for this model (81 > 77). Running this sequence through the model will result in indexing errors
Write embeds to disk:  66%|██████████████████████████████████████████▎                     | 218/330 [00:06<00:02, 40.44it/s]2024-05-10 09:22:35,193 [WARNING] (TextEmbeddingCache) The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['arrow at lower right. realistic tree']
Write embeds to disk:  77%|█████████████████████████████████████████████████               | 253/330 [00:07<00:01, 41.30it/s]2024-05-10 09:22:35,995 [WARNING] (TextEmbeddingCache) The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['site.']
Write embeds to disk:  93%|███████████████████████████████████████████████████████████▋    | 308/330 [00:08<00:00, 41.26it/s]2024-05-10 09:22:37,359 [WARNING] (TextEmbeddingCache) The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['to left and on top. an polygonal island with two bridges in river.']
Write embeds to disk:  98%|██████████████████████████████████████████████████████████████▋ | 323/330 [00:09<00:00, 40.94it/s]2024-05-10 09:22:37,737 [WARNING] (TextEmbeddingCache) The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['lower right.']
2024-05-10 09:22:37,808 [INFO] (DataBackendFactory) (id=siteplan600-1024) Completed processing 330 captions.                 
2024-05-10 09:22:37,808 [INFO] (DataBackendFactory) (id=siteplan600-1024) Creating VAE latent cache.                         
2024-05-10 09:22:37,810 [INFO] (DataBackendFactory) Skipping error scan for dataset siteplan600-1024. Set 'scan_for_errors' to True in the dataset config to enable this if your training runs into mismatched latent dimensions.
Traceback (most recent call last):
  File "/root/autodl-tmp/SimpleTuner/train_sdxl.py", line 1633, in <module>
    main()
  File "/root/autodl-tmp/SimpleTuner/train_sdxl.py", line 448, in main
    ) = prepare_validation_prompt_list(
  File "/root/autodl-tmp/SimpleTuner/helpers/legacy/validation.py", line 69, in prepare_validation_prompt_list
    raise ValueError(
ValueError: Embed cache engine did not contain a model_type. Cannot continue.
Traceback (most recent call last):
  File "/root/miniconda3/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1082, in launch_command
    simple_launcher(args)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 688, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python', '/root/autodl-tmp/SimpleTuner/train_sdxl.py', '--pretrained_model_name_or_path=/root/autodl-tmp/sd_xl_base_1.0', '--allow_tf32', '--learning_rate=1e-5', '--lr_scheduler=constant', '--lr_num_cycles=10', '--lr_warmup_steps=0', '--snr_gamma=5.0', '--seed=2024', '--adam_bfloat16', '--freeze_encoder', 'true', '--data_backend_config=/root/autodl-tmp/workspace/data_config_siteplan600-unCd-0.5.json', '--max_train_steps=40000', '--num_train_epochs=0', '--train_batch=1', '--gradient_accumulation_steps=1', '--caption_dropout_probability=0', '--validation_noise_scheduler=euler-a', '--validation_guidance=7', '--validation_guidance_rescale=0', '--validation_steps=200', '--validation_resolution=1024', '--num_validation_images=1', '--user_prompt_library=/root/autodl-tmp/workspace/siteplan_prompts.json', '--checkpointing_steps=4000', '--checkpoints_total_limit=5', '--tracker_project_name=simpletuner-sdxl-siteplan600-unCd-0.5', '--tracker_run_name=1024-b6-1e5-cycle4k', '--output_dir=/root/autodl-tmp/simpletunerOutput/sitePlan600-sdxl-1024-b1-1e5-unCd-0.1', '--report_to=wandb']' returned non-zero exit status 1.

Any clue how to fix that?

btw I've been having no luck at all running newer versions : (

**Comment by bghira** [comment]
are you using the `.sh` file to launch the script, or producing the commandline args manually?

**Comment by zhuliyi0** [comment]
> i live in central america and we have power curtailments which have made it hard to fully test this stuff. i've made a commit to resolve the webhook handler error.
> 
> the reason it's slower now is because it doesn't pre-cache the vae embeds. they go through on the first epoch. you can use `--vae_cache_preprocess` to enable this behaviour again
> 
> for the other error i'll have to see the dataloader json config

Here is my data config:

[
    {
        "id": "siteplan600-1024",
        "type": "local",
        "instance_data_dir": "/root/autodl-tmp/Dataset/siteplan600/1024",
        "crop": false,
        "crop_style": "random",
        "crop_aspect": "square",
        "resolution": 0.25,
        "resolution_type": "area",
        "minimum_image_size": 0.1,
        "caption_strategy": "textfile",
        "cache_dir_vae": "/root/vae_cache/siteplan600",
        "vae_cache_clear_each_epoch": false,
        "probability": 1.0,
        "repeats": 1,
        "text_embeds": "embed-cache-siteplan600"
    },
    {
        "id": "embed-cache-siteplan600",
        "dataset_type": "text_embeds",
        "default": false,
        "type": "local",
        "cache_dir": "/root/textembed_cache/siteplan600"
    }
]

**Comment by zhuliyi0** [comment]
> are you using the `.sh` file to launch the script, or producing the commandline args manually?

I use commandline args directly. Here is my command:

accelerate launch --mixed_precision="bf16" \
	--num_processes="1" \
	--num_machines="1" \
	--dynamo_backend="no" \
/root/autodl-tmp/SimpleTuner/train_sdxl.py \
	--pretrained_model_name_or_path="/root/autodl-tmp/sd_xl_base_1.0" \
    --allow_tf32 \
	--learning_rate="1e-5" \
	--lr_scheduler="constant" \
    --lr_num_cycles=10 \
	--lr_warmup_steps=0 \
    --snr_gamma=5.0 \
	--seed=2024 \
	--adam_bfloat16 \
    --freeze_encoder true \
    --data_backend_config="/root/autodl-tmp/workspace/data_config_siteplan600-unCd-0.5.json" \
	--max_train_steps="40000" \
    --num_train_epochs=0 \
	--train_batch="1" \
	--gradient_accumulation_steps="1" \
	--caption_dropout_probability=0 \
    --validation_noise_scheduler="euler-a" \
	--validation_guidance="7" \
	--validation_guidance_rescale="0" \
	--validation_steps="200" \
	--validation_resolution="1024" \
	--num_validation_images=1 \
	--user_prompt_library="/root/autodl-tmp/workspace/siteplan_prompts.json" \
	--checkpointing_steps="4000" \
	--checkpoints_total_limit="5" \
    --tracker_project_name="simpletuner-sdxl-siteplan600-unCd-0.5" \
	--tracker_run_name="1024-b6-1e5-cycle4k" \
    --output_dir="/root/autodl-tmp/simpletunerOutput/sitePlan600-sdxl-1024-b1-1e5-unCd-0.1" \
    --report_to="wandb" \

**Comment by bghira** [comment]
you need to set default = true on the text embed dataset

**Comment by zhuliyi0** [comment]
I added 'vae_cache_preprocess' arg, then I keep getting this error:

2024-05-11 08:35:17,346 [ERROR] (VAECache) Error encoding images ['/root/autodl-tmp/Dataset/siteplan600/512/e516c97a592bf601bdc93b80d4cabe43.jpg', '/root/autodl-tmp/Dataset/siteplan600/512/6f5cbef9f344e2593199365f2ee5ad6f.jpg', '/root/autodl-tmp/Dataset/siteplan600/512/3b0a8b71cb7b69b9557f07a95d301976.jpg']: stack expects each tensor to be equal size, but got [3, 896, 1216] at entry 0 and [3, 960, 1152] at entry 2
2024-05-11 08:35:17,347 [ERROR] (root) An error occurred in a future: Error encoding images ['/root/autodl-tmp/Dataset/siteplan600/512/e516c97a592bf601bdc93b80d4cabe43.jpg', '/root/autodl-tmp/Dataset/siteplan600/512/6f5cbef9f344e2593199365f2ee5ad6f.jpg', '/root/autodl-tmp/Dataset/siteplan600/512/3b0a8b71cb7b69b9557f07a95d301976.jpg']: stack expects each tensor to be equal size, but got [3, 896, 1216] at entry 0 and [3, 960, 1152] at entry 2, traceback: Traceback (most recent call last):
  File "/root/SimpleTuner/helpers/caching/vae.py", line 743, in _encode_images_in_batch
    latents = self.encode_images(
  File "/root/SimpleTuner/helpers/caching/vae.py", line 510, in encode_images
    processed_images = torch.stack(uncached_images).to(
RuntimeError: stack expects each tensor to be equal size, but got [3, 896, 1216] at entry 0 and [3, 960, 1152] at entry 2
, file <frame at 0x1e8549c0, file '/root/SimpleTuner/helpers/caching/vae.py', line 876, code _process_futures>, 872, future traceback Traceback (most recent call last):
  File "/root/SimpleTuner/helpers/caching/vae.py", line 743, in _encode_images_in_batch
    latents = self.encode_images(
  File "/root/SimpleTuner/helpers/caching/vae.py", line 510, in encode_images
    processed_images = torch.stack(uncached_images).to(
RuntimeError: stack expects each tensor to be equal size, but got [3, 896, 1216] at entry 0 and [3, 960, 1152] at entry 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/SimpleTuner/helpers/caching/vae.py", line 872, in _process_futures
    future.result()
  File "/root/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/root/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/root/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/SimpleTuner/helpers/caching/vae.py", line 774, in _encode_images_in_batch
    raise Exception(
Exception: Error encoding images ['/root/autodl-tmp/Dataset/siteplan600/512/e516c97a592bf601bdc93b80d4cabe43.jpg', '/root/autodl-tmp/Dataset/siteplan600/512/6f5cbef9f344e2593199365f2ee5ad6f.jpg', '/root/autodl-tmp/Dataset/siteplan600/512/3b0a8b71cb7b69b9557f07a95d301976.jpg']: stack expects each tensor to be equal size, but got [3, 896, 1216] at entry 0 and [3, 960, 1152] at entry 2, traceback: Traceback (most recent call last):
  File "/root/SimpleTuner/helpers/caching/vae.py", line 743, in _encode_images_in_batch
    latents = self.encode_images(
  File "/root/SimpleTuner/helpers/caching/vae.py", line 510, in encode_images
    processed_images = torch.stack(uncached_images).to(
RuntimeError: stack expects each tensor to be equal size, but got [3, 896, 1216] at entry 0 and [3, 960, 1152] at entry 2

I also tried set 'keep_vae_loaded', doesn't seem to help with speed. I thought VAE is pretty fast, like fraction of a second per image? What I am seeing is much longer than that, so VAE is not the issue?

**Comment by zhuliyi0** [comment]
I think I figured out 'Embed cache engine did not contain a model_type. Cannot continue.', I set 'default' flag to false, so there was no default in that config. The error is gone now.

**Comment by zhuliyi0** [comment]
> you need to set default = true on the text embed dataset

yes I figured it out while you are replying, thanks.

**Comment by zhuliyi0** [comment]
I used a new Linux instance to get the same slow speed, so not hardware issue. I tried --vae_cache_preprocess and somehow got cuda OOM error during caching, so I turned it off.

While running, I can see RAM going up and then down in cycles, and GPU is doing nothing most of the time.

**Comment by bghira** [comment]
the OOM is a dirty way to exit, and it does leave things resident in memory quite often

there is an option for the vae batch size that you can reduce from the default value

**Comment by zhuliyi0** [comment]
I changed vae_batch_size to 1, and it is caching now. The RAM is cycling slowly in the same way before, so you are probably right about the cause of slow speed. I thought VAE caching is always there and I don't remember any slow down like this. Can you explain a bit about new VAE caching vs the old? Thanks.

**Comment by zhuliyi0** [comment]
Is this normal speed for VAE caching? Most of the images are around 1m pixel, a few of them are large.

(Rank: 0)  | Bucket     | Image Count 
------------------------------
(Rank: 0)  | 1.36       | 70          
(Rank: 0)  | 0.88       | 13          
(Rank: 0)  | 0.65       | 12          
(Rank: 0)  | 0.74       | 44          
(Rank: 0)  | 1.29       | 19          
(Rank: 0)  | 1.83       | 3           
(Rank: 0)  | 1.2        | 12          
(Rank: 0)  | 0.78       | 18          
(Rank: 0)  | 0.94       | 8           
(Rank: 0)  | 1.54       | 26          
(Rank: 0)  | 1.0        | 40          
(Rank: 0)  | 0.68       | 4           
(Rank: 0)  | 0.83       | 8           
(Rank: 0)  | 1.06       | 6           
(Rank: 0)  | 1.13       | 18          
(Rank: 0)  | 0.57       | 2           
(Rank: 0)  | 0.48       | 2           
(Rank: 0)  | 1.75       | 11          
(Rank: 0)  | 2.09       | 3           
(Rank: 0)  | 0.55       | 3           
(Rank: 0)  | 1.46       | 4           
(Rank: 0)  | 1.62       | 1           
(Rank: 0)  | 0.46       | 1           
(Rank: 0)  | 0.62       | 1           
Loading captions: 100%|█████████████████████████████████████████████████████████████████| 330/330 [00:00<00:00, 60923.47it/s]
2024-05-11 10:03:00,397 [INFO] (DataBackendFactory) (id=siteplan600-1024) Initialise text embed pre-computation using the textfile caption strategy. We have 330 captions to process.
2024-05-11 10:03:00,407 [INFO] (DataBackendFactory) (id=siteplan600-1024) Completed processing 330 captions.
2024-05-11 10:03:00,407 [INFO] (DataBackendFactory) (id=siteplan600-1024) Creating VAE latent cache.
2024-05-11 10:03:00,407 [INFO] (DataBackendFactory) (id=siteplan600-1024) Discovering cache objects..
2024-05-11 10:03:00,408 [INFO] (DataBackendFactory) Skipping error scan for dataset siteplan600-1024. Set 'scan_for_errors' to True in the dataset config to enable this if your training runs into mismatched latent dimensions.
2024-05-11 10:03:48,066 [INFO] (VAECache) Bucket 0.48 caching results: {'not_local': 0, 'already_cached': 0, 'cached': 0, 'total': 2}
2024-05-11 10:04:49,121 [INFO] (VAECache) Bucket 0.65 caching results: {'not_local': 0, 'already_cached': 0, 'cached': 0, 'total': 12}
                                                                                                                             
2024-05-11 10:06:51,025 [INFO] (VAECache) Bucket 1.0 caching results: {'not_local': 0, 'already_cached': 0, 'cached': 1, 'total': 40}
2024-05-11 10:07:52,031 [INFO] (VAECache) Bucket 0.88 caching results: {'not_local': 0, 'already_cached': 0, 'cached': 0, 'total': 12}
2024-05-11 10:11:11,733 [INFO] (VAECache) Bucket 1.36 caching results: {'not_local': 0, 'already_cached': 0, 'cached': 2, 'total': 69}
2024-05-11 10:12:15,925 [INFO] (VAECache) Bucket 0.83 caching results: {'not_local': 0, 'already_cached': 0, 'cached': 0, 'total': 8}
2024-05-11 10:13:21,350 [INFO] (VAECache) Bucket 1.13 caching results: {'not_local': 0, 'already_cached': 0, 'cached': 0, 'total': 18}
2024-05-11 10:14:25,801 [INFO] (VAECache) Bucket 1.29 caching results: {'not_local': 0, 'already_cached': 0, 'cached': 0, 'total': 19}
2024-05-11 10:16:38,755 [INFO] (VAECache) Bucket 0.74 caching results: {'not_local': 0, 'already_cached': 0, 'cached': 1, 'total': 44}
2024-05-11 10:17:42,300 [INFO] (VAECache) Bucket 1.46 caching results: {'not_local': 0, 'already_cached': 0, 'cached': 0, 'total': 4}
2024-05-11 10:18:46,082 [INFO] (VAECache) Bucket 0.68 caching results: {'not_local': 0, 'already_cached': 0, 'cached': 0, 'total': 4}
2024-05-11 10:19:47,420 [INFO] (VAECache) Bucket 1.75 caching results: {'not_local': 0, 'already_cached': 0, 'cached': 0, 'total': 11}
2024-05-11 10:20:47,789 [INFO] (VAECache) Bucket 0.55 caching results: {'not_local': 0, 'already_cached': 0, 'cached': 0, 'total': 3}

**Comment by bghira** [comment]
nope, but as you're not using the bash scripts to launch it, there's probably some setting not being applied that everyone else will automatically get.

in other words, the defaults are often overridden by the bash scripts.
