### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by roperi** [bghira/SimpleTuner#40]
Docker image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
OS: Ubuntu 20.04.5 LTS
24 GB VRAM
29 GB RAM  4 vCPU

I tried with batch size 1 and 2. And with and without multi-gpu support. Both fail. 

```
$ bash train_sdxl.sh                                                                                                                                                   
[2023-08-18 10:54:39,821] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 10:54:44,720] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 10:54:44,758] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 10:54:44,778] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 10:54:44,799] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 10:54:44,821] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 10:54:44,852] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 10:54:44,880] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 10:54:44,883] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 10:54:44,885] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 10:54:44,894] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1191, in <module>
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1191, in <module>
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 156, in main
    accelerator = Accelerator(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 358, in __init__
    self.state = AcceleratorState(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 720, in __init__
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 156, in main
        PartialState(cpu, **kwargs)accelerator = Accelerator(

  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 198, in __init__
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 358, in __init__
Traceback (most recent call last):
    torch.cuda.set_device(self.device)
  File "/workspace/SimpleTuner/train_sdxl.py", line 1191, in <module>
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    self.state = AcceleratorState(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 720, in __init__
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    PartialState(cpu, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 198, in __init__
    torch.cuda.set_device(self.device)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 156, in main
    torch._C._cuda_setDevice(device)
RuntimeError    : accelerator = Accelerator(CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 358, in __init__
    self.state = AcceleratorState(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 720, in __init__
    PartialState(cpu, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 198, in __init__
    torch.cuda.set_device(self.device)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1191, in <module>
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 156, in main
    accelerator = Accelerator(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 358, in __init__
    self.state = AcceleratorState(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 720, in __init__
    PartialState(cpu, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 198, in __init__
    torch.cuda.set_device(self.device)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1191, in <module>
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1191, in <module>
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 156, in main
    accelerator = Accelerator(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 358, in __init__
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 156, in main
        accelerator = Accelerator(self.state = AcceleratorState(

  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 358, in __init__
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 720, in __init__
    self.state = AcceleratorState(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 720, in __init__
    PartialState(cpu, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 198, in __init__
    PartialState(cpu, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 198, in __init__
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1191, in <module>
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1191, in <module>
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 156, in main
    accelerator = Accelerator(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 358, in __init__
    self.state = AcceleratorState(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 720, in __init__
    PartialState(cpu, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 198, in __init__
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 156, in main
    torch.cuda.set_device(self.device)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    accelerator = Accelerator(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 358, in __init__
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    self.state = AcceleratorState(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 720, in __init__
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1191, in <module>
    PartialState(cpu, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 198, in __init__
    torch.cuda.set_device(self.device)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 156, in main
    accelerator = Accelerator(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 358, in __init__
    self.state = AcceleratorState(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 720, in __init__
    PartialState(cpu, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/state.py", line 198, in __init__
    torch.cuda.set_device(self.device)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Downloading (_)lve/main/config.json: 100%|______________________________________________________________________________________________________________________________________________________| 631/631 [00:00<00:00, 3.44MB/s]
Downloading (_)ch_model.safetensors:  85%|______________________________________________________________________________________________________________________________                      | 283M/335M [00:03<00:00, 86.9MB/s]
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 12254 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 12255) of binary: /workspace/SimpleTuner/.venv/bin/python
Traceback (most recent call last):
  File "/workspace/SimpleTuner/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 970, in launch_command
    multi_gpu_launcher(args)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_sdxl.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-08-18_10:54:51
  host      : ee48d4679c9e
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 12256)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-08-18_10:54:51
  host      : ee48d4679c9e
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 12257)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-08-18_10:54:51
  host      : ee48d4679c9e
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 12258)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2023-08-18_10:54:51
  host      : ee48d4679c9e
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 12259)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2023-08-18_10:54:51
  host      : ee48d4679c9e
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 12260)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2023-08-18_10:54:51
  host      : ee48d4679c9e
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 12261)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2023-08-18_10:54:51
  host      : ee48d4679c9e
  rank      : 8 (local_rank: 8)
  exitcode  : 1 (pid: 12262)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[8]:
  time      : 2023-08-18_10:54:51
  host      : ee48d4679c9e
  rank      : 9 (local_rank: 9)
  exitcode  : 1 (pid: 12263)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-18_10:54:51
  host      : ee48d4679c9e
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 12255)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

```

**Comment by bghira** [comment]
you might have missed the `--multi_gpu` or `num_processes=2`
