### ISSUE TITLE
SD3 error: can't load tokenizer

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#447]
Same issue when I launch from shell script and launch by command line. Shell script gave more detail about the error though:

TRAINER_EXTRA_ARGS not set, defaulting to empty.
VALIDATION_NEGATIVE_PROMPT not set, defaulting to empty.
Enabling BitFit.
2024-06-13 16:07:28,018 [INFO] (ArgsParser) VAE Model: madebyollin/sdxl-vae-fp16-fix
2024-06-13 16:07:28,019 [INFO] (ArgsParser) Default VAE Cache location: 
2024-06-13 16:07:28,019 [INFO] (ArgsParser) Text Cache location: cache
2024-06-13 16:07:28,043 [INFO] (__main__) Enabling tf32 precision boost for NVIDIA devices due to --allow_tf32.
2024-06-13 16:07:28,043 [INFO] (__main__) Load tokenizers
2024-06-13 16:07:30,403 [WARNING] (__main__) Primary tokenizer (CLIP-L/14) failed to load. Continuing to test whether we have just the secondary tokenizer..
Error: -> Can't load tokenizer for 'stabilityai/stable-diffusion-3-medium'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'stabilityai/stable-diffusion-3-medium' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
Traceback: Traceback (most recent call last):
  File "/root/autodl-tmp/SimpleTuner/train_sdxl.py", line 277, in main
    tokenizer_1 = CLIPTokenizer.from_pretrained(**tokenizer_kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2073, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'stabilityai/stable-diffusion-3-medium'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'stabilityai/stable-diffusion-3-medium' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

Can't load tokenizer for 'stabilityai/stable-diffusion-3-medium'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'stabilityai/stable-diffusion-3-medium' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
Traceback (most recent call last):
  File "/root/autodl-tmp/SimpleTuner/train_sdxl.py", line 2075, in <module>
    main()
  File "/root/autodl-tmp/SimpleTuner/train_sdxl.py", line 287, in main
    raise e
  File "/root/autodl-tmp/SimpleTuner/train_sdxl.py", line 277, in main
    tokenizer_1 = CLIPTokenizer.from_pretrained(**tokenizer_kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2073, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'stabilityai/stable-diffusion-3-medium'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'stabilityai/stable-diffusion-3-medium' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

Network should be fine since I just pulled from github. I did a quick google, but didn't find working solution. Help is appreciated.

**Comment by bghira** [comment]
use `stabilityai/stable-diffusion-3-medium-diffusers`

**Comment by bghira** [comment]
(also, be sure to pass `--sd3`)

**Comment by janzd** [comment]
@zhuliyi0 
SD3 isn't publicly accessible. You need to log in at Hugging Face and fill in a form on the Hugging Face page of SD3 to get access to the model. However, since it's only accessible by having a Hugging Face account and agreeing with the terms of use, you need to use Hugging Face CLI on your computer and link it with your account.

First, you need an access token from Hugging Face. You can find it in Settings on Hugging Face. If you don't have one, create a new token and copy the value to clipboard.

Then,

```
pip install -U "huggingface_hub[cli]"
export HUGGINGFACE_TOKEN={YOUR ACCESS TOKEN FROM HUGGING FACE}
huggingface-cli login --token $HUGGINGFACE_TOKEN
```

and you should be set to start using SD3.

**Comment by janzd** [comment]
@bghira 
Maybe worth mentioning in the README that people need to agree with the terms of use of SD3 on Hugging Face and use an access token and huggingface-cli to log in?

**Comment by bghira** [comment]
they used the wrong path entirely.
