### ISSUE TITLE
SD3 full training fails to generate validation images

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [bghira/SimpleTuner#460]
I'm testing SD3 full training and it fails to generate validation images, with the error attached below. The training continues to run fine after that.
The setting that I've used for validation:
``` bash
# Use this to append an instance prompt to each caption, used for adding trigger words.
# This has not been tested in SDXL.
#export INSTANCE_PROMPT="lotr style "
# If you also supply a user prompt library or `--use_prompt_library`, this will be added to those lists.
export VALIDATION_PROMPT="minimalism simple illustration vector art style clean single black circle symmetric shape sharp professional print quality white background highres high contrast black and white"
export VALIDATION_GUIDANCE=5.0
# You'll want to set this to 0.7 if you are training a terminal SNR model.
export VALIDATION_GUIDANCE_RESCALE=0.0
# How frequently we will save and run a pipeline for validations.
export VALIDATION_STEPS=14
export VALIDATION_NUM_INFERENCE_STEPS=30
export VALIDATION_NEGATIVE_PROMPT="ugly, old, mutation, lowres, low quality, doll, long neck, extra limbs, text, signature, artist name, bad anatomy, poorly drawn, malformed, deformed, blurry, out of focus, noise, dust"
export VALIDATION_SEED=10
export VALIDATION_RESOLUTION=$RESOLUTION
```
Error:

``` log
2024-06-15 17:41:58,221 [ERROR] (helpers.training.validation) Error generating validation image: Cannot generate a cpu tensor from a generator of type cuda., Traceback (most recent call last):
  File "/workspace/SimpleTuner/helpers/training/validation.py", line 666, in validate_prompt
    validation_image_results = self.pipeline(**pipeline_kwargs).images
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/SimpleTuner/helpers/sd3/pipeline.py", line 902, in __call__
    latents = self.prepare_latents(
  File "/workspace/SimpleTuner/helpers/sd3/pipeline.py", line 677, in prepare_latents
    latents = randn_tensor(shape, generator=generator, device=device, dtype=dtype)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/utils/torch_utils.py", line 67, in randn_tensor
    raise ValueError(f"Cannot generate a {device} tensor from a generator of type {gen_device_type}.")
ValueError: Cannot generate a cpu tensor from a generator of type cuda.

2024-06-15 17:41:58,230 [ERROR] (helpers.training.validation) Error generating validation image: Cannot generate a cpu tensor from a generator of type cuda., Traceback (most recent call last):
  File "/workspace/SimpleTuner/helpers/training/validation.py", line 666, in validate_prompt
    validation_image_results = self.pipeline(**pipeline_kwargs).images
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/SimpleTuner/helpers/sd3/pipeline.py", line 902, in __call__
    latents = self.prepare_latents(
  File "/workspace/SimpleTuner/helpers/sd3/pipeline.py", line 677, in prepare_latents
    latents = randn_tensor(shape, generator=generator, device=device, dtype=dtype)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/utils/torch_utils.py", line 67, in randn_tensor
    raise ValueError(f"Cannot generate a {device} tensor from a generator of type {gen_device_type}.")
ValueError: Cannot generate a cpu tensor from a generator of type cuda.
```

**Comment by bghira** [comment]
please test the main branch when you have a chance. it's not clear why this occurs, unless it's a difference in how the vae preprocessing vs on-demand caches are working. do you have any more information on that?

**Comment by bghira** [comment]
btw, `VALIDATION_STEPS` will make a image every 14 training steps. you likely want this higher, around 100 at least, depending on how slowly your training runs.

**Comment by a-l-e-x-d-s-9** [comment]
I've used 14 steps just to test it, not to wait too long.
Unfortunately, I already terminated my server for today, but I will test it again tomorrow.

**Comment by a-l-e-x-d-s-9** [comment]
I've tested it again, images are generated now, so it seems to be fixed.
