### ISSUE TITLE
dataset config preparation ?

### ISSUE THREAD

**Issue by benihime91** [bghira/SimpleTuner#505]
Hi, trying to run a training run and for the love of god i am not being able to setup the training. I have pointed the issue down to my dataset config json file. I am adding the debug log as well as the config file here.

My use case is this -
1. I have a directory where i store all the datasets but not all datasets are used for training. 
2. I used to have a metadata file in kohya trainer metadata format which lists all the required files and the captions/tags needed for training and traines with only the given image keys.
3. I have converted that file to parquet and created the dataset config as shown below, but i am not being able to start the training. It is not able to find the image files.

```json
[
  {
    "id": "dashshaper--v1.2.5_image_dataset",
    "type": "local",
    "instance_data_dir": "/mnt/data1/ayushman/datasets/",
    "caption_strategy": "parquet",
    "metadata_backend": "parquet",
    "parquet": {
      "path": "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dashshaper--v1.2.5_meta_cap_clean.parquet",
      "filename_column": "image",
      "caption_column": "caption",
      "fallback_caption_column": "tags",
      "width_column": "width",
      "height_column": "height",
      "identifier_includes_extension": true
    },
    "resolution": 768,
    "minimum_image_size": 768,
    "maximum_image_size": 2048,
    "target_downsample_size": 2048,
    "prepend_instance_prompt": false,
    "instance_prompt": null,
    "only_instance_prompt": false,
    "disable": false,
    "cache_dir_vae": "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/vae_cache",
    "probability": 1.0,
    "skip_file_discovery": "",
    "preserve_data_backend_cache": false,
    "vae_cache_clear_each_epoch": true,
    "repeats": 1,
    "crop": true,
    "crop_aspect": "preserve",
    "crop_style": "random",
    "resolution_type": "pixel",
    "text_embeds": "dashshaper--v1.2.5_text_embeds_dataset",
    "cache_dir": "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/cache_dir"
  },
  {
    "id": "dashshaper--v1.2.5_text_embeds_dataset",
    "dataset_type": "text_embeds",
    "default": true,
    "type": "local",
    "cache_dir": "/mnt/data1/projects/dash-diffusion/SimpleTuner/work_dir/cache_dir"
  }
]

```

```txt
2024-06-20 03:26:52,965 [INFO] (ArgsParser) VAE Model: madebyollin/sdxl-vae-fp16-fix
2024-06-20 03:26:52,965 [INFO] (ArgsParser) Default VAE Cache location: 
2024-06-20 03:26:52,965 [INFO] (ArgsParser) Text Cache location: cache
2024-06-20 03:26:53,241 [INFO] (__main__) Enabling tf32 precision boost for NVIDIA devices due to --allow_tf32.
2024-06-20 03:26:53,241 [INFO] (__main__) Load tokenizers
2024-06-20 03:26:53,330 [INFO] (__main__) Load OpenAI CLIP-L/14 text encoder..
2024-06-20 03:26:53,360 [INFO] (__main__) Loading T5-XXL v1.1 text encoder from /mnt/data1/ayushman/projects/dash-diffusion/local_ckpts/dashshaper-1.2-step00048900/text_encoder..
2024-06-20 03:26:53,601 [INFO] (__main__) Loading LAION OpenCLIP-G/14 text encoder..
2024-06-20 03:26:53,694 [INFO] (ArgsParser) VAE Model: madebyollin/sdxl-vae-fp16-fix
2024-06-20 03:26:53,694 [INFO] (ArgsParser) Default VAE Cache location: 
2024-06-20 03:26:53,694 [INFO] (ArgsParser) Text Cache location: cache
2024-06-20 03:26:53,706 [INFO] (ArgsParser) VAE Model: madebyollin/sdxl-vae-fp16-fix
2024-06-20 03:26:53,706 [INFO] (ArgsParser) Default VAE Cache location: 
2024-06-20 03:26:53,706 [INFO] (ArgsParser) Text Cache location: cache
2024-06-20 03:26:54,725 [INFO] (__main__) Load VAE..
2024-06-20 03:26:54,921 [INFO] (__main__) Moving models to GPU. Almost there.
2024-06-20 03:26:55,457 [INFO] (__main__) Loading SDXL U-net..
2024-06-20 03:26:55,807 [INFO] (__main__) Moving the U-net to GPU in torch.bfloat16 precision.
2024-06-20 03:26:58,220 [INFO] (__main__) Enabling xformers memory-efficient attention.
2024-06-20 03:26:58,269 [INFO] (__main__) Initialising VAE in bf16 precision, you may specify a different value if preferred: bf16, fp32, default
2024-06-20 03:26:58,355 [INFO] (__main__) Loaded VAE into VRAM.
2024-06-20 03:26:58,372 [INFO] (DataBackendFactory) Loading data backend config from /mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dataset_meta.json
2024-06-20 03:26:58,372 [INFO] (DataBackendFactory) Configuring text embed backend: dashshaper--v1.2.5_text_embeds_dataset
2024-06-20 03:26:58,373 [INFO] (TextEmbeddingCache) (Rank: 0) (id=dashshaper--v1.2.5_text_embeds_dataset) Listing all text embed cache entries
2024-06-20 03:26:58,373 [INFO] (DataBackendFactory) Pre-computing null embedding
2024-06-20 03:26:59,114 [INFO] (DataBackendFactory) Loading data backend config from /mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dataset_meta.json
2024-06-20 03:26:59,114 [INFO] (DataBackendFactory) Configuring text embed backend: dashshaper--v1.2.5_text_embeds_dataset
2024-06-20 03:26:59,114 [INFO] (TextEmbeddingCache) (Rank: 2) (id=dashshaper--v1.2.5_text_embeds_dataset) Listing all text embed cache entries
2024-06-20 03:26:59,115 [INFO] (DataBackendFactory) Pre-computing null embedding
2024-06-20 03:26:59,122 [INFO] (DataBackendFactory) Loading data backend config from /mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dataset_meta.json
2024-06-20 03:26:59,122 [INFO] (DataBackendFactory) Configuring text embed backend: dashshaper--v1.2.5_text_embeds_dataset
2024-06-20 03:26:59,122 [INFO] (TextEmbeddingCache) (Rank: 1) (id=dashshaper--v1.2.5_text_embeds_dataset) Listing all text embed cache entries
2024-06-20 03:26:59,123 [INFO] (DataBackendFactory) Pre-computing null embedding
2024-06-20 03:27:06,517 [INFO] (DataBackendFactory) Completed loading text embed services.
2024-06-20 03:27:06,517 [INFO] (DataBackendFactory) Completed loading text embed services.
2024-06-20 03:27:06,517 [INFO] (DataBackendFactory) Completed loading text embed services.
2024-06-20 03:27:06,518 [INFO] (DataBackendFactory) Configuring data backend: dashshaper--v1.2.5_image_dataset
2024-06-20 03:27:06,518 [INFO] (DataBackendFactory) Configured backend: {'id': 'dashshaper--v1.2.5_image_dataset', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': True, 'crop_aspect': 'preserve', 'crop_aspect_buckets': None, 'crop_style': 'random', 'disable_validation': False, 'resolution': 768, 'resolution_type': 'pixel', 'parquet': {'path': '/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dashshaper--v1.2.5_meta_cap_clean.parquet', 'filename_column': 'image', 'caption_column': 'caption', 'fallback_caption_column': 'tags', 'width_column': 'width', 'height_column': 'height', 'identifier_includes_extension': True}, 'caption_strategy': 'parquet', 'instance_data_root': '/mnt/data1/ayushman/datasets/', 'maximum_image_size': 2048, 'target_downsample_size': 2048}, 'dataset_type': 'image'}
2024-06-20 03:27:06,518 [INFO] (DataBackendFactory) Configuring data backend: dashshaper--v1.2.5_image_dataset
2024-06-20 03:27:06,518 [INFO] (DataBackendFactory) Configuring data backend: dashshaper--v1.2.5_image_dataset
2024-06-20 03:27:06,518 [INFO] (DataBackendFactory) Configured backend: {'id': 'dashshaper--v1.2.5_image_dataset', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': True, 'crop_aspect': 'preserve', 'crop_aspect_buckets': None, 'crop_style': 'random', 'disable_validation': False, 'resolution': 768, 'resolution_type': 'pixel', 'parquet': {'path': '/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dashshaper--v1.2.5_meta_cap_clean.parquet', 'filename_column': 'image', 'caption_column': 'caption', 'fallback_caption_column': 'tags', 'width_column': 'width', 'height_column': 'height', 'identifier_includes_extension': True}, 'caption_strategy': 'parquet', 'instance_data_root': '/mnt/data1/ayushman/datasets/', 'maximum_image_size': 2048, 'target_downsample_size': 2048}, 'dataset_type': 'image'}
2024-06-20 03:27:06,518 [INFO] (DataBackendFactory) Configured backend: {'id': 'dashshaper--v1.2.5_image_dataset', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': True, 'crop_aspect': 'preserve', 'crop_aspect_buckets': None, 'crop_style': 'random', 'disable_validation': False, 'resolution': 768, 'resolution_type': 'pixel', 'parquet': {'path': '/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dashshaper--v1.2.5_meta_cap_clean.parquet', 'filename_column': 'image', 'caption_column': 'caption', 'fallback_caption_column': 'tags', 'width_column': 'width', 'height_column': 'height', 'identifier_includes_extension': True}, 'caption_strategy': 'parquet', 'instance_data_root': '/mnt/data1/ayushman/datasets/', 'maximum_image_size': 2048, 'target_downsample_size': 2048}, 'dataset_type': 'image'}
2024-06-20 03:27:06,518 [INFO] (DataBackendFactory) (id=dashshaper--v1.2.5_image_dataset) Loading bucket manager.
2024-06-20 03:27:06,518 [INFO] (DataBackendFactory) (id=dashshaper--v1.2.5_image_dataset) Loading bucket manager.
2024-06-20 03:27:06,618 [INFO] (DataBackendFactory) (id=dashshaper--v1.2.5_image_dataset) Loading bucket manager.
2024-06-20 03:27:11,034 [INFO] (DataBackendFactory) (id=dashshaper--v1.2.5_image_dataset) Refreshing aspect buckets on main process.
2024-06-20 03:27:11,034 [INFO] (ParquetMetadataBackend) Discovering new files...
2024-06-20 03:30:30,142 [INFO] (ParquetMetadataBackend) Image processing statistics: {'total_processed': 6536786, 'skipped': {'already_exists': 0, 'metadata_missing': 0, 'not_found': 6536786, 'too_small': 0, 'other': 0}}
2024-06-20 03:30:30,142 [INFO] (BaseMetadataBackend) Enforcing minimum image size of 768. This could take a while for very-large datasets.
2024-06-20 03:30:30,143 [INFO] (ParquetMetadataBackend) Completed aspect bucket update.
2024-06-20 03:30:30,204 [INFO] (DataBackendFactory) (id=dashshaper--v1.2.5_image_dataset) Reloading bucket manager cache on subprocesses.
2024-06-20 03:30:30,204 [INFO] (DataBackendFactory) (id=dashshaper--v1.2.5_image_dataset) Reloading bucket manager cache on subprocesses.
2024-06-20 03:30:30,205 [INFO] (DataBackendFactory) Configured backend: {'id': 'dashshaper--v1.2.5_image_dataset', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': True, 'crop_aspect': 'preserve', 'crop_aspect_buckets': None, 'crop_style': 'random', 'disable_validation': False, 'resolution': 768, 'resolution_type': 'pixel', 'parquet': {'path': '/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dashshaper--v1.2.5_meta_cap_clean.parquet', 'filename_column': 'image', 'caption_column': 'caption', 'fallback_caption_column': 'tags', 'width_column': 'width', 'height_column': 'height', 'identifier_includes_extension': True}, 'caption_strategy': 'parquet', 'instance_data_root': '/mnt/data1/ayushman/datasets/', 'maximum_image_size': 2048, 'target_downsample_size': 2048}, 'dataset_type': 'image', 'data_backend': <helpers.data_backend.local.LocalDataBackend object at 0x7ff3b091fc70>, 'instance_data_root': '/mnt/data1/ayushman/datasets', 'metadata_backend': <helpers.metadata.backends.parquet.ParquetMetadataBackend object at 0x7ff3b091fa00>}
2024-06-20 03:30:30,205 [INFO] (DataBackendFactory) Configured backend: {'id': 'dashshaper--v1.2.5_image_dataset', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': True, 'crop_aspect': 'preserve', 'crop_aspect_buckets': None, 'crop_style': 'random', 'disable_validation': False, 'resolution': 768, 'resolution_type': 'pixel', 'parquet': {'path': '/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dashshaper--v1.2.5_meta_cap_clean.parquet', 'filename_column': 'image', 'caption_column': 'caption', 'fallback_caption_column': 'tags', 'width_column': 'width', 'height_column': 'height', 'identifier_includes_extension': True}, 'caption_strategy': 'parquet', 'instance_data_root': '/mnt/data1/ayushman/datasets/', 'maximum_image_size': 2048, 'target_downsample_size': 2048}, 'dataset_type': 'image', 'data_backend': <helpers.data_backend.local.LocalDataBackend object at 0x7f39bcd079d0>, 'instance_data_root': '/mnt/data1/ayushman/datasets', 'metadata_backend': <helpers.metadata.backends.parquet.ParquetMetadataBackend object at 0x7f39bcd07c70>}
2024-06-20 03:30:30,205 [INFO] (DataBackendFactory) Configured backend: {'id': 'dashshaper--v1.2.5_image_dataset', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': True, 'crop_aspect': 'preserve', 'crop_aspect_buckets': None, 'crop_style': 'random', 'disable_validation': False, 'resolution': 768, 'resolution_type': 'pixel', 'parquet': {'path': '/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dashshaper--v1.2.5_meta_cap_clean.parquet', 'filename_column': 'image', 'caption_column': 'caption', 'fallback_caption_column': 'tags', 'width_column': 'width', 'height_column': 'height', 'identifier_includes_extension': True}, 'caption_strategy': 'parquet', 'instance_data_root': '/mnt/data1/ayushman/datasets/', 'maximum_image_size': 2048, 'target_downsample_size': 2048}, 'dataset_type': 'image', 'data_backend': <helpers.data_backend.local.LocalDataBackend object at 0x7f26e1e37c70>, 'instance_data_root': '/mnt/data1/ayushman/datasets', 'metadata_backend': <helpers.metadata.backends.parquet.ParquetMetadataBackend object at 0x7f26e2032350>}
2024-06-20 03:30:30,205 [ERROR] (__main__) No images were discovered by the bucket manager in the dataset: dashshaper--v1.2.5_image_dataset., traceback: Traceback (most recent call last):
  File "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/train_sdxl.py", line 698, in main
    configure_multi_databackend(
  File "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/helpers/data_backend/factory.py", line 570, in configure_multi_databackend
    raise Exception(
Exception: No images were discovered by the bucket manager in the dataset: dashshaper--v1.2.5_image_dataset.


```

**Comment by bghira** [comment]
can you show one row from the parquet?

**Comment by benihime91** [comment]
Hey this is what one row looks like:
(image paths are truncated, but i have verified that the images exist)

```
image              /mnt/data1/ayushman/datasets/aesthetic_harsha/...
caption            A vintage car parked on a paved surface, with ...
tags                                                            None
width                                                           3072
height                                                          2304
base_image_path    aesthetic_harsha/2008 Vintage Motor Cars of He...
Name: 100, dtype: object
```

**Comment by bghira** [comment]
ok you have to remove the full preceding /path from the sample filename column.

you can have nested dirs under the dir root. but it needs to have the instance_data_dir value not in there. sorry if that's confusing.

**Comment by benihime91** [comment]
so i it should work with `base_image_path` as filename column and keep everything same ?
i am assuming internally you are doing something like `os.path.join(instance_dir, parquet.filename_column)`

**Comment by bghira** [comment]
yes :)

**Comment by bghira** [comment]
it was a problem earlier in teh year. when training on eg. RunPod or Kaggle or my own systems, which all had the same data under three different prefix. abs path was a nightmare

**Comment by benihime91** [comment]
hey tried running after doing the changes discussed above getting this error : `AttributeError: 'NoneType' object has no attribute 'size'` (log attaced below)

> (dataset config)

```json
[
  {
    "id": "dashshaper--v1.2.5_image_dataset",
    "type": "local",
    "instance_data_dir": "/mnt/data1/ayushman/datasets",
    "caption_strategy": "parquet",
    "metadata_backend": "parquet",
    "parquet": {
      "path": "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dashshaper--v1.2.5_meta_cap_clean.parquet",
      "filename_column": "base_image_path",
      "caption_column": "caption",
      "fallback_caption_column": "tags",
      "width_column": "width",
      "height_column": "height",
      "identifier_includes_extension": true
    },
    "resolution": 768,
    "minimum_image_size": 768,
    "maximum_image_size": 2048,
    "target_downsample_size": 2048,
    "prepend_instance_prompt": false,
    "instance_prompt": null,
    "only_instance_prompt": false,
    "disable": false,
    "cache_dir_vae": "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/vae_cache",
    "probability": 1.0,
    "skip_file_discovery": "",
    "preserve_data_backend_cache": false,
    "vae_cache_clear_each_epoch": true,
    "repeats": 1,
    "crop": true,
    "crop_aspect": "preserve",
    "crop_style": "random",
    "resolution_type": "pixel",
    "text_embeds": "dashshaper--v1.2.5_text_embeds_dataset",
    "cache_dir": "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/cache_dir"
  },
  {
    "id": "dashshaper--v1.2.5_text_embeds_dataset",
    "dataset_type": "text_embeds",
    "default": true,
    "type": "local",
    "cache_dir": "/mnt/data1/projects/dash-diffusion/SimpleTuner/work_dir/cache_dir"
  }
]

```

> (error log)
```txt
2024-06-20 06:04:43,707 [INFO] (__main__) Enabling xformers memory-efficient attention.
2024-06-20 06:04:43,756 [INFO] (__main__) Initialising VAE in bf16 precision, you may specify a different value if preferred: bf16, fp32, default
2024-06-20 06:04:43,811 [INFO] (__main__) Loaded VAE into VRAM.
2024-06-20 06:04:43,828 [INFO] (DataBackendFactory) Loading data backend config from /mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dataset_meta.json
2024-06-20 06:04:43,828 [INFO] (DataBackendFactory) Configuring text embed backend: dashshaper--v1.2.5_text_embeds_dataset
2024-06-20 06:04:43,829 [INFO] (TextEmbeddingCache) (Rank: 0) (id=dashshaper--v1.2.5_text_embeds_dataset) Listing all text embed cache entries
2024-06-20 06:04:43,829 [INFO] (DataBackendFactory) Pre-computing null embedding
2024-06-20 06:04:44,495 [INFO] (DataBackendFactory) Loading data backend config from /mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dataset_meta.json
2024-06-20 06:04:44,495 [INFO] (DataBackendFactory) Configuring text embed backend: dashshaper--v1.2.5_text_embeds_dataset
2024-06-20 06:04:44,495 [INFO] (TextEmbeddingCache) (Rank: 1) (id=dashshaper--v1.2.5_text_embeds_dataset) Listing all text embed cache entries
2024-06-20 06:04:44,496 [INFO] (DataBackendFactory) Pre-computing null embedding
2024-06-20 06:04:44,593 [INFO] (DataBackendFactory) Loading data backend config from /mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dataset_meta.json
2024-06-20 06:04:44,593 [INFO] (DataBackendFactory) Configuring text embed backend: dashshaper--v1.2.5_text_embeds_dataset
2024-06-20 06:04:44,593 [INFO] (TextEmbeddingCache) (Rank: 2) (id=dashshaper--v1.2.5_text_embeds_dataset) Listing all text embed cache entries
2024-06-20 06:04:44,594 [INFO] (DataBackendFactory) Pre-computing null embedding
2024-06-20 06:04:52,028 [INFO] (DataBackendFactory) Completed loading text embed services.
2024-06-20 06:04:52,029 [INFO] (DataBackendFactory) Completed loading text embed services.
2024-06-20 06:04:52,029 [INFO] (DataBackendFactory) Completed loading text embed services.
2024-06-20 06:04:52,029 [INFO] (DataBackendFactory) Configuring data backend: dashshaper--v1.2.5_image_dataset
2024-06-20 06:04:52,029 [INFO] (DataBackendFactory) Configuring data backend: dashshaper--v1.2.5_image_dataset
2024-06-20 06:04:52,029 [INFO] (DataBackendFactory) Configuring data backend: dashshaper--v1.2.5_image_dataset
2024-06-20 06:04:52,029 [INFO] (DataBackendFactory) Configured backend: {'id': 'dashshaper--v1.2.5_image_dataset', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': True, 'crop_aspect': 'preserve', 'crop_aspect_buckets': None, 'crop_style': 'random', 'disable_validation': False, 'resolution': 768, 'resolution_type': 'pixel', 'parquet': {'path': '/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dashshaper--v1.2.5_meta_cap_clean.parquet', 'filename_column': 'base_image_path', 'caption_column': 'caption', 'fallback_caption_column': 'tags', 'width_column': 'width', 'height_column': 'height', 'identifier_includes_extension': True}, 'caption_strategy': 'parquet', 'instance_data_root': '/mnt/data1/ayushman/datasets', 'maximum_image_size': 2048, 'target_downsample_size': 2048}, 'dataset_type': 'image'}
2024-06-20 06:04:52,029 [INFO] (DataBackendFactory) Configured backend: {'id': 'dashshaper--v1.2.5_image_dataset', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': True, 'crop_aspect': 'preserve', 'crop_aspect_buckets': None, 'crop_style': 'random', 'disable_validation': False, 'resolution': 768, 'resolution_type': 'pixel', 'parquet': {'path': '/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dashshaper--v1.2.5_meta_cap_clean.parquet', 'filename_column': 'base_image_path', 'caption_column': 'caption', 'fallback_caption_column': 'tags', 'width_column': 'width', 'height_column': 'height', 'identifier_includes_extension': True}, 'caption_strategy': 'parquet', 'instance_data_root': '/mnt/data1/ayushman/datasets', 'maximum_image_size': 2048, 'target_downsample_size': 2048}, 'dataset_type': 'image'}
2024-06-20 06:04:52,029 [INFO] (DataBackendFactory) Configured backend: {'id': 'dashshaper--v1.2.5_image_dataset', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': True, 'crop_aspect': 'preserve', 'crop_aspect_buckets': None, 'crop_style': 'random', 'disable_validation': False, 'resolution': 768, 'resolution_type': 'pixel', 'parquet': {'path': '/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/work_dir/dashshaper--v1.2.5_meta_cap_clean.parquet', 'filename_column': 'base_image_path', 'caption_column': 'caption', 'fallback_caption_column': 'tags', 'width_column': 'width', 'height_column': 'height', 'identifier_includes_extension': True}, 'caption_strategy': 'parquet', 'instance_data_root': '/mnt/data1/ayushman/datasets', 'maximum_image_size': 2048, 'target_downsample_size': 2048}, 'dataset_type': 'image'}
2024-06-20 06:04:52,029 [INFO] (DataBackendFactory) (id=dashshaper--v1.2.5_image_dataset) Loading bucket manager.
2024-06-20 06:04:52,029 [INFO] (DataBackendFactory) (id=dashshaper--v1.2.5_image_dataset) Loading bucket manager.
2024-06-20 06:04:52,030 [INFO] (DataBackendFactory) (id=dashshaper--v1.2.5_image_dataset) Loading bucket manager.
2024-06-20 06:04:56,829 [INFO] (DataBackendFactory) (id=dashshaper--v1.2.5_image_dataset) Refreshing aspect buckets on main process.
2024-06-20 06:04:56,830 [INFO] (ParquetMetadataBackend) Discovering new files...
2024-06-20 06:07:37,016 [ERROR] (ParquetMetadataBackend) Error processing image: 'NoneType' object has no attribute 'size'
2024-06-20 06:07:37,111 [ERROR] (ParquetMetadataBackend) Error traceback: Traceback (most recent call last):
  File "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/helpers/metadata/backends/parquet.py", line 416, in _process_for_bucket
    prepared_sample = training_sample.prepare()
  File "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/helpers/image_manipulation/training_sample.py", line 289, in prepare
    self.crop()
  File "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/helpers/image_manipulation/training_sample.py", line 568, in crop
    self._downsample_before_crop()
  File "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/helpers/image_manipulation/training_sample.py", line 359, in _downsample_before_crop
    if self._should_downsample_before_crop():
  File "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/helpers/image_manipulation/training_sample.py", line 342, in _should_downsample_before_crop
    self.image.size[0] > self.pixel_resolution
AttributeError: 'NoneType' object has no attribute 'size'

2024-06-20 06:07:37,112 [ERROR] (ParquetMetadataBackend) Error processing image: 'NoneType' object has no attribute 'size'
2024-06-20 06:07:37,112 [ERROR] (ParquetMetadataBackend) Error traceback: Traceback (most recent call last):
  File "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/helpers/metadata/backends/parquet.py", line 416, in _process_for_bucket
    prepared_sample = training_sample.prepare()
  File "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/helpers/image_manipulation/training_sample.py", line 289, in prepare
    self.crop()
  File "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/helpers/image_manipulation/training_sample.py", line 568, in crop
    self._downsample_before_crop()
  File "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/helpers/image_manipulation/training_sample.py", line 359, in _downsample_before_crop
    if self._should_downsample_before_crop():
  File "/mnt/data1/ayushman/projects/dash-diffusion/SimpleTuner/helpers/image_manipulation/training_sample.py", line 342, in _should_downsample_before_crop
    self.image.size[0] > self.pixel_resolution
AttributeError: 'NoneType' object has no attribute 'size'
```

**Comment by bghira** [comment]
alright, i've pushed a fix for that. the `pixel` resolution_type is intended for DeepFloyd training, so isn't tested very often. it should work here though.

**Comment by benihime91** [comment]
hey thanks! so latest pull should work ?

**Comment by bghira** [comment]
yup
