### ISSUE TITLE
cannot import name 'random_dataloader_iterator_with_prefetch' from 'helpers.data_backend.factory'

### ISSUE THREAD

**Issue by OliviaOliveiira** [bghira/SimpleTuner#541]
Hey!
The recent update seems to break down the training startup
```
DEBUG_EXTRA_ARGS not set, defaulting to empty.
TRAINER_EXTRA_ARGS not set, defaulting to empty.
Disabling Xformers for Stable Diffusion 3 (https://github.com/huggingface/diffusers/issues/8535)
Traceback (most recent call last):
  File "/home/miya123/Рабочий стол/Huita/SimpleTuner/train_sdxl.py", line 33, in <module>
    from helpers.data_backend.factory import (
ImportError: cannot import name 'random_dataloader_iterator_with_prefetch' from 'helpers.data_backend.factory' (/home/miya123/Рабочий стол/Huita/SimpleTuner/helpers/data_backend/factory.py)
Traceback (most recent call last):
  File "/home/miya123/Рабочий стол/Huita/SimpleTuner/.venv/bin/accelerate", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/miya123/Рабочий стол/Huita/SimpleTuner/.venv/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/miya123/Рабочий стол/Huita/SimpleTuner/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/home/miya123/Рабочий стол/Huita/SimpleTuner/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/miya123/Рабочий стол/Huita/SimpleTuner/.venv/bin/python', 'train_sdxl.py', '--model_type=lora', '--pretrained_model_name_or_path=/media/miya123/UUI/Users/USER01/.cache/huggingface/hub/models--stabilityai--stable-diffusion-3-medium-diffusers/snapshots/ea42f8cef0f178587cf766dc8129abd379c90671', '--set_grads_to_none', '--gradient_accumulation_steps=4', '--resume_from_checkpoint=latest', '--snr_gamma=5', '--data_backend_config=/home/miya123/Рабочий стол/Huita/SimpleTuner/Base_dir/multidatabackend.json', '--num_train_epochs=0', '--max_train_steps=1500', '--metadata_update_interval=65', '--adam_bfloat16', '--learning_rate=1e-5', '--lr_scheduler=constant', '--seed', '42', '--lr_warmup_steps=10', '--output_dir=/home/miya123/Рабочий стол/Huita/SimpleTuner/Base_dir/models', '--inference_scheduler_timestep_spacing=trailing', '--training_scheduler_timestep_spacing=trailing', '--allow_tf32', '--mixed_precision=bf16', '--lora_rank=64', '--sd3', '--train_batch=1', '--caption_dropout_probability=0.1', '--validation_prompt=ethnographic photography of teddy bear at a picnic', '--num_validation_images=1', '--validation_num_inference_steps=30', '--validation_seed=42', '--minimum_image_size=1024', '--resolution=1024', '--validation_resolution=1024', '--resolution_type=pixel', '--checkpointing_steps=500', '--checkpoints_total_limit=2', '--validation_steps=100', '--override_dataset_config', '--tracker_run_name=sd3-lora-huera', '--tracker_project_name=sd3-training', '--validation_guidance=7.5', '--validation_guidance_rescale=0.0', '--validation_negative_prompt=blurry, cropped, ugly']' returned non-zero exit status 1.
```

**Comment by bghira** [comment]
please pull the latest branch.
