### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by roperi** [bghira/SimpleTuner#56]
Trainer fails to start. Using latest tag: v0.2.3

```
08/26/2023 19:20:15 - INFO - __main__ - Pre-computing text embeds / updating cache.
Processing prompts:   0%|          | 0/42 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1297, in <module>
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 602, in main
    embed_cache.precompute_embeddings_for_prompts(
  File "/workspace/SimpleTuner/helpers/sdxl_embeds.py", line 137, in precompute_embeddings_for_prompts
    self.compute_embeddings_for_prompts(prompts, return_concat=False)
  File "/workspace/SimpleTuner/helpers/sdxl_embeds.py", line 96, in compute_embeddings_for_prompts
    self.cache_dir, self.create_hash(prompt) + ".pt"
  File "/workspace/SimpleTuner/helpers/sdxl_embeds.py", line 17, in create_hash
    return hashlib.md5(caption.encode()).hexdigest()
AttributeError: 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "/workspace/SimpleTuner/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

**Comment by bghira** [comment]
I ran into this, and it's possibly fixed in the `data_backend` branch. Can you give that a try? I have tested it briefly for S3 and local backend.

**Comment by bghira** [comment]
#52

**Comment by bghira** [comment]
eg. it would be in one of these. quite a bit to sift through.
![image](https://github.com/bghira/SimpleTuner/assets/59658056/fe95e2b5-edff-407a-a030-c6ff81c56540)

**Comment by bghira** [comment]
well, that's embarassing. i wrote the files using the wrong method. i hesitate to say it's fixed because i haven't tested local backend again. but, that's definitely moving in the right direction.

**Comment by bghira** [comment]
i was able to load up a training session in a local backend on that data_backend branch, using a fresh Vast.ai instance.
