### ISSUE TITLE
Crash due to random_dataloader_iterator not being a generator and possible fix

### ISSUE THREAD

**Issue by LeroyDaydreamer** [bghira/SimpleTuner#567]
I got a crash when finetuing with train_sd21.sh:

```
[ERROR] (__main__) Epic fail: cannot unpack non-iterable int object, traceback: Traceback (most recent call last):
  File "/home/user/ai/SimpleTuner/train_sd21.py", line 1645, in <module>
    main()
  File "/home/user/ai/SimpleTuner/train_sd21.py", line 1115, in main
    for step, batch in random_dataloader_iterator(train_backends):
        ^^^^^^^^^^^
TypeError: cannot unpack non-iterable int object
```
I'm just starting to learn Python so I had ChatGPT and Claude helping figuring out what's going on. 
The error occured even when there are no possible execution paths that don't return a tuple. 
After a lot of testing and back and forth with the AIs both insisted that the current implementation is wrong and the function should be a generator. Looking at the sdxl training script and how it is used there this was also my impression. So I had Claude changing it accordingly since ChatGPT kept messing it up. It looks correct to me and more importantly it also works. I now saw this has just recently intentionally been changed to not be a generator though I don't understand the reason. The old code doesn't look correct either though, I might be wrong but as I understand it there shouldn't be returns, just yields like in the code below. 
helpers\data_backend\factory.py:
```python
def random_dataloader_iterator(backends: dict):
    prefetch_log_debug("Random dataloader iterator launched.")
    global step
    if step is None:
        step = StateTracker.get_epoch_step()
    else:
        step = 0

    gradient_accumulation_steps = StateTracker.get_args().gradient_accumulation_steps
    logger.debug(f"Backends to select from {backends}")
    if backends == {}:
        logger.debug(
            "All dataloaders exhausted. Moving to next epoch in main training loop."
        )
        StateTracker.clear_exhausted_buckets()
        StateTracker.set_repeats(repeats=0)        
        yield step, False
    while backends:
        step += 1
        epoch_step = int(step / gradient_accumulation_steps)
        StateTracker.set_epoch_step(epoch_step)
        chosen_backend_id = select_dataloader_index(step, backends)
        if chosen_backend_id is None:
            logger.debug("No dataloader iterators were available.")
            yield step, False
        chosen_iter = iter(backends[chosen_backend_id])
        try:
            yield step, next(chosen_iter)
        except MultiDatasetExhausted:
            # We may want to repeat the same dataset multiple times in a single epoch.
            # If so, we can just reset the iterator and keep going.
            repeats = StateTracker.get_data_backend_config(chosen_backend_id).get(
                "repeats", False
            )
            if (
                repeats
                and repeats > 0
                and StateTracker.get_repeats(chosen_backend_id) < repeats
            ):
                StateTracker.increment_repeats(chosen_backend_id)
                logger.debug(
                    f"Dataset (name={chosen_backend_id}) is now sampling its {StateTracker.get_repeats(chosen_backend_id)} repeat out of {repeats} total allowed."
                )
                continue
            logger.debug(
                f"Dataset (name={chosen_backend_id}) is now exhausted after {StateTracker.get_repeats(chosen_backend_id)} repeat(s). Removing from list."
            )
            del backends[chosen_backend_id]
            StateTracker.backend_exhausted(chosen_backend_id)
            StateTracker.set_repeats(data_backend_id=chosen_backend_id, repeats=0)
        finally:
            if not backends or all(
                [
                    StateTracker.get_data_backend_config(backend_id).get(
                        "ignore_epochs", False
                    )
                    for backend_id in backends
                ]
            ):
                logger.debug(
                    "All dataloaders exhausted. Moving to next epoch in main training loop."
                )
                StateTracker.clear_exhausted_buckets()
                yield step, False
    yield step, False
    ```

**Comment by bghira** [comment]
whether it's a generator or not is an implementation detail, in the sense that an infinite loop (`while True:`) also works to the same results with lower complexity. previously the iterator was a generator, which is why the SD 2.x trainer expects that. but instead, it should loop forever and use the revised checks that exist in the sdxl script. it is quite a lot of work and involves subtle understandings of these details.

**Comment by bghira** [comment]
see #568, everything is reorganised to use the one script now.
