### ISSUE TITLE
Can't resume from final checkpoint Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'simpletuner-results/pipeline/unet_ema'.

### ISSUE THREAD

**Issue by roperi** [bghira/SimpleTuner#57]
Trying to resume from the saved tuned model with this...

```
# sdxl-env.sh
...
export RESUME_CHECKPOINT="simpletuner-results/pipeline"
...
```
...fails:

```
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'simpletuner-results/pipeline/unet_ema'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1293, in <module>
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 779, in main
    accelerator.load_state(os.path.join(args.output_dir, path))
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 2695, in load_state
    hook(models, input_dir)
  File "/workspace/SimpleTuner/helpers/sdxl_save_hooks.py", line 24, in load_model_hook
    load_model = EMAModel.from_pretrained(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/training_utils.py", line 118, in from_pretrained
    _, ema_kwargs = model_cls.load_config(path, return_unused_kwargs=True)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 384, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like simpletuner-results/pipeline/unet_ema is not the path to a directory containing a config.json file.
```

tree structure:
```
$ ls  simpletuner-results/pipeline/
model_index.json  scheduler  text_encoder  text_encoder_2  tokenizer  tokenizer_2  unet  va
```

There is no `unet_ema` folder.

**Comment by bghira** [comment]
you might need to use the /full/path/to this. i noticed this when looking at the code, like, how did that ever work? but i then realised, i am always passing full path in.

**Comment by bghira** [comment]
the resume might be a bit wonky between having EMA originally and then the final export actually merges the EMA weights into the model.

see here:

```py
    accelerator.wait_for_everyone()
    if accelerator.is_main_process:
        unet = accelerator.unwrap_model(unet)
        if args.use_ema:
            ema_unet.copy_to(unet.parameters())

        pipeline = StableDiffusionXLPipeline.from_pretrained(
            args.pretrained_model_name_or_path,
            text_encoder=text_encoder_1,
            text_encoder_2=text_encoder_2,
            tokenizer=tokenizer_1,
            tokenizer_2=tokenizer_2,
            vae=vae,
            unet=unet,
            revision=args.revision,
        )
        pipeline.scheduler = DDIMScheduler.from_pretrained(
            args.pretrained_model_name_or_path,
            subfolder="scheduler",
            prediction_type=args.prediction_type,
            timestep_spacing=args.training_scheduler_timestep_spacing,
            rescale_betas_zero_snr=args.rescale_betas_zero_snr,
        )
        pipeline.save_pretrained(
            os.path.join(args.output_dir, "pipeline"), safe_serialization=True
        )
```

i'm not sure that resume from, is the best way to do this. i think the actual base model you use needs to be, this /full/path/to that pipeline. and i would move it somewhere else first, so it doesn't get overwritten :D

**Comment by bghira** [comment]
```bash
# Configure these values.
# Using a Huggingface Hub model:
export MODEL_NAME="stabilityai/stable-diffusion-xl-base-1.0"
# Using a local path to a huggingface hub model or saved checkpoint:
#export MODEL_NAME="/datasets/models/pipeline"
```

see this line in the sdxl env example.
