### ISSUE TITLE
TypeError: layer_norm(): argument 'input' (position 1) must be Tensor, not tuple

### ISSUE THREAD

**Issue by xingyouxin** [bghira/SimpleTuner#575]
While fine-tuning SD3 with LoRA, the error is showing up: 

```
Traceback (most recent call last):
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/train.py", line 2454, in <module>
    main()
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/train.py", line 1843, in main
    model_pred = transformer(
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1593, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1411, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 822, in forward
    return model_forward(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 810, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/models/transformers/transformer_sd3.py", line 309, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 494, in checkpoint
    ret = function(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/models/transformers/transformer_sd3.py", line 304, in custom_forward
    return module(*inputs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 162, in forward
    norm_hidden_states, gate_msa, shift_mlp, scale_mlp, gate_mlp = self.norm1(hidden_states, emb=temb)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/models/normalization.py", line 83, in forward
    x = self.norm(x) * (1 + scale_msa[:, None]) + shift_msa[:, None]
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 201, in forward
    return F.layer_norm(
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2573, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
TypeError: layer_norm(): argument 'input' (position 1) must be Tensor, not tuple
```

Is the dataset format suitable? I created a dataset of 10 pictures and 10 .txt prompt files.

**Comment by bghira** [comment]
this is duplicate issue #503

**Comment by xingyouxin** [comment]
> this is duplicate issue #503

Thank you, my hero!

**Comment by xingyouxin** [comment]
For this issue, setting GRADIENT_CHECKPOINTING=false in config.env figured out my problem. Thanks for all.
