### ISSUE TITLE
TypeError: SD3LoraLoaderMixin.save_lora_weights() got an unexpected keyword argument 'text_encoder_1_lora_layers_to_save'

### ISSUE THREAD

**Issue by xingyouxin** [bghira/SimpleTuner#576]
I have tried to debug by checking the logs first.

```
SD3LoraLoaderMixin.save_lora_weights() got an unexpected keyword argument 'text_encoder_1_lora_layers_to_save'
Traceback (most recent call last):
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/train.py", line 2454, in <module>
    main()
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/train.py", line 2117, in main
    accelerator.save_state(save_path)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 2955, in save_state
    hook(self._models, weights, output_dir)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/helpers/training/save_hooks.py", line 261, in save_model_hook
    self._save_lora(models=models, weights=weights, output_dir=output_dir)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/helpers/training/save_hooks.py", line 187, in _save_lora
    StableDiffusion3Pipeline.save_lora_weights(
TypeError: SD3LoraLoaderMixin.save_lora_weights() got an unexpected keyword argument 'text_encoder_1_lora_layers_to_save'
```

Then I find the source codes as follows:

```
if self.args.sd3:
            StableDiffusion3Pipeline.save_lora_weights(
                output_dir,
                transformer_lora_layers=transformer_lora_layers_to_save,
                # SD3 doesn't support text encoder training.
                text_encoder_1_lora_layers_to_save=text_encoder_1_lora_layers_to_save,
                text_encoder_2_lora_layers_to_save=text_encoder_2_lora_layers_to_save,
                text_encoder_3_lora_layers_to_save=text_encoder_3_lora_layers_to_save,
            )
```

It seems that sds API doesn't support the text_encoder_1_lora_layers_to_save parameter. Maybe I have to edit the diffusers source codes?

**Comment by bghira** [comment]
thank you, that should be fixed in the main branch

**Comment by xingyouxin** [comment]
> thank you, that should be fixed in the main branch

Thank you very much!
