### ISSUE TITLE
TypeError: SD3LoraLoaderMixin.save_lora_weights() got an unexpected keyword argument 'text_encoder_lora_layers'

### ISSUE THREAD

**Issue by xingyouxin** [bghira/SimpleTuner#579]
With the introduction of Stable Diffusion 3 quickstart documentation, I cloned the latest SimpleTuner project and installed the dependencies. However, I meet this error: 

```
SD3LoraLoaderMixin.save_lora_weights() got an unexpected keyword argument 'text_encoder_lora_layers'
Traceback (most recent call last):
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/train.py", line 2464, in <module>
    main()
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/train.py", line 2125, in main
    accelerator.save_state(save_path)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 2955, in save_state
    hook(self._models, weights, output_dir)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/helpers/training/save_hooks.py", line 262, in save_model_hook
    self._save_lora(models=models, weights=weights, output_dir=output_dir)
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/helpers/training/save_hooks.py", line 188, in _save_lora
    StableDiffusion3Pipeline.save_lora_weights(
TypeError: SD3LoraLoaderMixin.save_lora_weights() got an unexpected keyword argument 'text_encoder_lora_layers'
```

After checking the source file in .venv/lib/python3.10/site-packages/diffusers/loaders/lora.py, I find that the save_lora_weights() API truly have no parameter of text_encoder_lora_layers. At the same time, I checked the lora.py file on my Windows os PC. It has the parameter of text_encoder_lora_layers. Thus, I realized that it was a version error. I finally figured out this problem by reinstall diffusers from source file, as follows:

```
pip uninstall diffusers
pip install git+https://github.com/huggingface/diffusers
```

**Comment by bghira** [comment]
thank you. i've updated the Diffusers dependency for nvidia systems.

**Comment by xingyouxin** [comment]
> thank you. i've updated the Diffusers dependency for nvidia systems.

Nice going!
