### ISSUE TITLE
Could SD3 fine-tuning with LoRA support 256x256 resolution size?

### ISSUE THREAD

**Issue by xingyouxin** [bghira/SimpleTuner#581]
For 1024x1024 resolution datasets, the project runs well. While I changed the dataset image resolution to 256x256 and set the relevant parameter (RESOLUTION) in config.env to 256, the error occurred:

```
2024-07-13 22:18:42,362 [ERROR] (__main__) No images were discovered by the bucket manager in the dataset: pseudo-camera-10k-sd3., traceback: Traceback (most recent call last):
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/train.py", line 780, in main
    configure_multi_databackend(
  File "/home/xyx/AITools/StableDiffusion3/SimpleTuner/helpers/data_backend/factory.py", line 603, in configure_multi_databackend
    raise Exception(
Exception: No images were discovered by the bucket manager in the dataset: pseudo-camera-10k-sd3.
```

Should I change other parameters? I appreciate your help ~

**Comment by bghira** [comment]
you'll need to also edit multidatabackend.json and switch `resolution` to 256 and `resolution_type` to pixel but with small sizes like that you can only do square crops due to the need for a 64px aspect bucket interval

**Comment by xingyouxin** [comment]
> you'll need to also edit multidatabackend.json and switch `resolution` to 256 and `resolution_type` to pixel but with small sizes like that you can only do square crops due to the need for a 64px aspect bucket interval

Thank you, sir!
