### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [4, 128, 170] at entry 0 and [4, 96, 128] at entry 2

### ISSUE THREAD

**Issue by bghira** [bghira/SimpleTuner#59]
```
Traceback (most recent call last):
  File "/root/SimpleTuner/train_sdxl.py", line 1343, in <module>
    main()
  File "/root/SimpleTuner/train_sdxl.py", line 858, in main
    for step, batch in enumerate(train_dataloader):
  File "/root/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/data_loader.py", line 394, in __iter__
    next_batch = next(dataloader_iter)
  File "/root/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/root/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/root/SimpleTuner/train_sdxl.py", line 617, in <lambda>
    collate_fn=lambda examples: collate_fn(examples),
  File "/root/SimpleTuner/train_sdxl.py", line 559, in collate_fn
    pixel_values = torch.stack(latents)
RuntimeError: stack expects each tensor to be equal size, but got [4, 128, 170] at entry 0 and [4, 96, 128] at entry 2
```

**Comment by bghira** [comment]
fixed in b29d9a85af0d861e4f3e16f09422115ed90c6397
