### ISSUE TITLE
Error training Flux LoRA

### ISSUE THREAD

**Issue by markuryy** [bghira/SimpleTuner#621]
I'm not sure if there is something wrong with my config or if this issue would occur regardless. Training Flux.1 dev

`| 0/30000 [00:02<?, ?it/s]The size of tensor a (10) must match the size of tensor b (16) at non-singleton dimension 1
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train.py", line 2651, in <module>
    main()
  File "/workspace/SimpleTuner/train.py", line 1818, in main
    noisy_latents = (
RuntimeError: The size of tensor a (10) must match the size of tensor b (16) at non-singleton dimension 1`

**Comment by markuryy** [comment]
I changed the `TRAIN_BATCH_SIZE` from 10 to 16 and it seemed to produce a different error:
```cross_attention_kwargs ['image_rotary_emb'] are not expected by XFormersAttnProcessor and will be ignored.
too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train.py", line 2651, in <module>
    main()
  File "/workspace/SimpleTuner/train.py", line 1969, in main
    model_pred = transformer(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 822, in forward
    return model_forward(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 810, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/models/transformers/transformer_flux.py", line 392, in forward
    encoder_hidden_states, hidden_states = torch.utils.checkpoint.checkpoint(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 494, in checkpoint
    ret = function(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/models/transformers/transformer_flux.py", line 387, in custom_forward
    return module(*inputs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/models/transformers/transformer_flux.py", line 198, in forward
    attn_output, context_attn_output = self.attn(
ValueError: too many values to unpack (expected 2)

**Comment by bghira** [comment]
you might need to enable square cropping. the model doesn't let you train with ARB yet.

**Comment by kudou-reira** [comment]
> you might need to enable square cropping. the model doesn't let you train with ARB yet.

I can reproduce both errors from @markuryy. This is my `multibackend.json`. All images in the dataset are 1K (`1024 x 1024`) resolution, but I changed the file to force a square crop anyway just to be sure.

```
[
  {
    "id": "dataset_name",
    "type": "local",
    "crop": true,
    "crop_aspect": "square",
    "crop_style": "center",
    "resolution": 1.0,
    "minimum_image_size": 1.0,
    "maximum_image_size": 1.0,
    "target_downsample_size": 1.0,
    "resolution_type": "area",
    "cache_dir_vae": "/path",
    "instance_data_dir": "/path",
    "disabled": false,
    "skip_file_discovery": "",
    "caption_strategy": "textfile",
    "metadata_backend": "json",
    "repeats": 10
  },
  {
    "id": "text-embeds",
    "type": "local",
    "dataset_type": "text_embeds",
    "default": true,
    "cache_dir": "/path",
    "disabled": false,
    "write_batch_size": 128
  }
]
```

**Comment by bghira** [comment]
got it, this was due to xformers! thank you!

**Comment by mitchoz** [comment]
> got it, this was due to xformers! thank you!

How did you solve it? I'm having the same issue, xformers is installed and disabling xformers doesn't seem to solve the problem. 
Have tried normalizing images and cropping manually too, no change.

**Comment by mitchoz** [comment]
FYI I keep having this issue even after recent updates, with xformers on or off. Using normalized square images 1024x1024 as dataset.

**Comment by mitchoz** [comment]
> FYI I keep having this issue even after recent updates, with xformers on or off. Using normalized square images 1024x1024 as dataset.

pip-install optimum-quanto

TRAINER_EXTRA_ARGS="--base_model_precision=int8-quanto" in config

seems to solve this
