### ISSUE TITLE
FLUX LoRA Training: xFormers not supported?

### ISSUE THREAD

**Issue by billnye2** [bghira/SimpleTuner#625]
Getting this error when trying to run training script for FLUX with xFormers. However, when disabling it with `export USE_XFORMERS=false` inside the config file, the training starts ok. This might be due to version mismatch in dependencies, not sure. Below is error when xFormers is enabled:

```python
Epoch 1/100, Steps:   0%|                                                                            | 0/500 [00:00<?, ?it/s]
cross_attention_kwargs ['image_rotary_emb'] are not expected by XFormersAttnProcessor and will be ignored.
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/content/SimpleTuner/train.py", line 2651, in <module>
    main()
  File "/content/SimpleTuner/train.py", line 1969, in main
    model_pred = transformer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 819, in forward
    return model_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 807, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/transformer_flux.py", line 392, in forward
    encoder_hidden_states, hidden_states = torch.utils.checkpoint.checkpoint(
  File "/usr/local/lib/python3.10/dist-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 494, in checkpoint
    ret = function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/transformer_flux.py", line 387, in custom_forward
    return module(*inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/transformer_flux.py", line 198, in forward
    attn_output, context_attn_output = self.attn(
ValueError: not enough values to unpack (expected 2, got 1)
```

Here are the dependency versions I have installed:
```python
accelerate==0.32.1
bitsandbytes==0.43.3
boto3==1.34.153
botocore==1.34.153
clip-interrogator==0.6.0
colorama==0.4.6
compel==2.0.3
dadaptation==3.2
datasets==2.20.0
deepspeed==0.14.4
diffusers @ git+https://github.com/huggingface/diffusers@00e3a8c828789bba79cf68531219e1baeeaff6fc
iterutils==0.1.6
numpy==1.26.0
opencv-python==4.10.0.84
pandas==2.1.4
peft==0.12.0
pillow==10.4.0
prodigyopt==1.0
requests==2.32.3
safetensors==0.4.3
scipy==1.13.1
tensorboard==2.17.0
torch @ https://download.pytorch.org/whl/cu121/torch-2.3.1%2Bcu121-cp310-cp310-linux_x86_64.whl#sha256=f0deb5d2f932a68ed54625ba140eddbf2af22be978ee19b9b63c986add6425b2
torchaudio @ https://download.pytorch.org/whl/cu121/torchaudio-2.3.1%2Bcu121-cp310-cp310-linux_x86_64.whl#sha256=0b423f4ae3356f11f6723e8c77208ac3f9361a4f941e4cc08d86c32c137594bc
torchmetrics==1.4.1
torchsde==0.2.6
torchvision @ https://download.pytorch.org/whl/cu121/torchvision-0.18.1%2Bcu121-cp310-cp310-linux_x86_64.whl#sha256=e95ba5a2c616939281e01babf11664d6d1725e81bba57ef81f81c3e57e4d4151
transformers==4.42.4
triton==2.3.1
triton-library==1.0.0rc4
urllib3==1.26.19
vega-datasets==0.9.0
wandb==0.17.5
xformers==0.0.27
```

**Comment by bghira** [comment]
resolved in main

**Comment by beyondbatman-master** [comment]
i meet the same issue, how to solve it?

**Comment by bghira** [comment]
xformers isn't really supported anymore as its capabilities were merged into pytorch 2.2 and we are now on pytorch 2.4.1

**Comment by beyondbatman-master** [comment]
Is pytorch 2.4.1 currently the accelerated version，implement similar functionality to xformer？

**Comment by beyondbatman-master** [comment]
so just use pytorch 2.4.1 and forget xformer，is that meaning？
