### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers.pipelines.flux'

### ISSUE THREAD

**Issue by magicwang1111** [bghira/SimpleTuner#650]
already update to latest diffusers.
(qwen) [wangxi@v100-4 SimpleTuner]$ git pull
Already up to date.
(qwen) [wangxi@v100-4 SimpleTuner]$ pip show diffusers
Name: diffusers
Version: 0.30.0.dev0
Summary: State-of-the-art diffusion in PyTorch and JAX.
Home-page: https://github.com/huggingface/diffusers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/diffusers/graphs/contributors)
Author-email: diffusers@huggingface.co
License: Apache 2.0 License
Location: /mnt/data/wangxi/miniconda3/envs/qwen/lib/python3.10/site-packages
Requires: filelock, huggingface-hub, importlib-metadata, numpy, Pillow, regex, requests, safetensors
Required-by: compel

(qwen) [wangxi@v100-4 SimpleTuner]$ CUDA_VISIBLE_DEVICES=5,7 bash train.sh
2024-08-06 11:13:11,377 [WARNING] (ArgsParser) The VAE model madebyollin/sdxl-vae-fp16-fix is not compatible. Please use a compatible VAE to eliminate this warning. The baked-in VAE will be used, instead.
2024-08-06 11:13:11,377 [INFO] (ArgsParser) VAE Model: /mnt/data1/shared_data/FLUX.1-dev/
2024-08-06 11:13:11,377 [INFO] (ArgsParser) Default VAE Cache location:
2024-08-06 11:13:11,377 [INFO] (ArgsParser) Text Cache location: cache
2024-08-06 11:13:11,378 [WARNING] (ArgsParser) Updating T5 XXL tokeniser max length to 512 for Flux.
2024-08-06 11:13:11,378 [WARNING] (ArgsParser) Gradient accumulation steps are enabled, but gradient precision is set to 'unmodified'. This may lead to numeric instability. Consider setting --gradient_precision=fp32.
2024-08-06 11:13:11,580 [WARNING] (accelerate.utils.other) Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
2024-08-06 11:13:11,584 [INFO] (__main__) Enabling tf32 precision boost for NVIDIA devices due to --allow_tf32.
2024-08-06 11:13:11,584 [INFO] (__main__) Load tokenizers
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
2024-08-06 11:13:11,894 [INFO] (__main__) Loading OpenAI CLIP-L text encoder from /mnt/data1/shared_data/FLUX.1-dev//text_encoder..
2024-08-06 11:13:12,016 [INFO] (__main__) Loading T5 XXL v1.1 text encoder from /mnt/data1/shared_data/FLUX.1-dev//text_encoder_2..
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.67s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.87s/it]
2024-08-06 11:13:16,873 [INFO] (__main__) Load VAE: /mnt/data1/shared_data/FLUX.1-dev/
2024-08-06 11:13:16,978 [INFO] (__main__) Moving text encoder to GPU.
2024-08-06 11:13:17,120 [INFO] (__main__) Moving text encoder 2 to GPU.
Exception ignored in: <function TextEmbeddingCache.__del__ at 0x7fa1b4bd29e0>
Traceback (most recent call last):
  File "/mnt/data1/wangxi/SimpleTuner/helpers/caching/text_embeds.py", line 1198, in __del__
    if self.batch_write_thread.is_alive():
AttributeError: 'TextEmbeddingCache' object has no attribute 'batch_write_thread'
2024-08-06 11:13:24,016 [INFO] (__main__) Initialising VAE in bf16 precision, you may specify a different value if preferred: bf16, fp32, default
2024-08-06 11:13:24,071 [INFO] (__main__) Loaded VAE into VRAM.
2024-08-06 11:13:24,095 [INFO] (DataBackendFactory) Loading data backend config from config/multidatabackend.json
2024-08-06 11:13:24,095 [INFO] (DataBackendFactory) Configuring text embed backend: text-embeds
2024-08-06 11:13:24,096 [ERROR] (__main__) No module named 'diffusers.pipelines.flux', traceback: Traceback (most recent call last):
  File "/mnt/data1/wangxi/SimpleTuner/train.py", line 663, in main
    configure_multi_databackend(
  File "/mnt/data1/wangxi/SimpleTuner/helpers/data_backend/factory.py", line 400, in configure_multi_databackend
    init_backend["text_embed_cache"] = TextEmbeddingCache(
  File "/mnt/data1/wangxi/SimpleTuner/helpers/caching/text_embeds.py", line 131, in __init__
    from diffusers.pipelines.flux import FluxPipeline
ModuleNotFoundError: No module named 'diffusers.pipelines.flux'

Exception ignored in: <function TextEmbeddingCache.__del__ at 0x7f7f3ea169e0>
Traceback (most recent call last):
  File "/mnt/data1/wangxi/SimpleTuner/helpers/caching/text_embeds.py", line 1198, in __del__
    if self.batch_write_thread.is_alive():
AttributeError: 'TextEmbeddingCache' object has no attribute 'batch_write_thread'

**Comment by bghira** [comment]
looks like your install is corrupted. please recreate the venv?

**Comment by bghira** [comment]
i believe this is fixed with the dependency updates for nvidia today.

**Comment by LianShuaiLong** [comment]
same error
