### ISSUE TITLE
Sometimes training process dies with Signals.SIGKILL 9

### ISSUE THREAD

**Issue by Shed-The-Skin** [bghira/SimpleTuner#653]
After setting up the repo with the [FLUX quickstart guide](https://github.com/bghira/SimpleTuner/blob/main/documentation/quickstart/FLUX.md), I ran a training session overnight to find that it had died somewhere along the way. It seems to have died after processing bucket 1.0 , console output:

```
(.venv) vwing@vwing-Desktop:~/Documents/SimpleTuner$ bash train.sh
2024-08-05 21:09:57,307 [WARNING] (ArgsParser) The VAE model madebyollin/sdxl-vae-fp16-fix is not compatible. Please use a compatible VAE to eliminate this warning. The baked-in VAE will be used, instead.
2024-08-05 21:09:57,307 [INFO] (ArgsParser) VAE Model: black-forest-labs/FLUX.1-dev
2024-08-05 21:09:57,307 [INFO] (ArgsParser) Default VAE Cache location:
2024-08-05 21:09:57,307 [INFO] (ArgsParser) Text Cache location: cache
2024-08-05 21:09:57,307 [WARNING] (ArgsParser) Updating T5 XXL tokeniser max length to 512 for Flux.
2024-08-05 21:09:57,307 [WARNING] (ArgsParser) Gradient accumulation steps are enabled, but gradient precision is set to 'unmodified'. This may lead to numeric instability. Consider setting --gradient_precision=fp32.
2024-08-05 21:09:57,365 [INFO] (__main__) Enabling tf32 precision boost for NVIDIA devices due to --allow_tf32.
2024-08-05 21:09:57,365 [INFO] (__main__) Load tokenizers
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
2024-08-05 21:09:57,958 [INFO] (__main__) Loading OpenAI CLIP-L text encoder from black-forest-labs/FLUX.1-dev/text_encoder..
2024-08-05 21:09:58,215 [INFO] (__main__) Loading T5 XXL v1.1 text encoder from black-forest-labs/FLUX.1-dev/text_encoder_2..
Downloading shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 3514.29it/s]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.59s/it]
2024-08-05 21:10:02,078 [INFO] (__main__) Load VAE: black-forest-labs/FLUX.1-dev
2024-08-05 21:10:02,315 [INFO] (__main__) Moving text encoder to GPU.
2024-08-05 21:10:02,517 [INFO] (__main__) Moving text encoder 2 to GPU.
2024-08-05 21:10:04,141 [INFO] (__main__) Initialising VAE in bf16 precision, you may specify a different value if preferred: bf16, fp32, default
2024-08-05 21:10:04,189 [INFO] (__main__) Loaded VAE into VRAM.
2024-08-05 21:10:04,217 [INFO] (DataBackendFactory) Loading data backend config from config/multidatabackend.json
2024-08-05 21:10:04,218 [INFO] (DataBackendFactory) Configuring text embed backend: text-embeds
model_index.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 536/536 [00:00<00:00, 7.37MB/s]
Loading pipeline components...:   0%|                                                                                                                                                                 | 0/5 [00:00<?, ?it/s]Loaded scheduler as FlowMatchEulerDiscreteScheduler from `scheduler` subfolder of black-forest-labs/FLUX.1-dev.
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 790.51it/s]
2024-08-05 21:10:04,394 [INFO] (TextEmbeddingCache) (Rank: 0) (id=text-embeds) Listing all text embed cache entries
2024-08-05 21:10:04,394 [INFO] (DataBackendFactory) Pre-computing null embedding
2024-08-05 21:10:09,692 [INFO] (DataBackendFactory) Completed loading text embed services.
2024-08-05 21:10:09,692 [INFO] (DataBackendFactory) Configuring data backend: pseudo-camera-10k-flux
2024-08-05 21:10:09,692 [INFO] (DataBackendFactory) (id=pseudo-camera-10k-flux) Loading bucket manager.
2024-08-05 21:10:09,693 [INFO] (JsonMetadataBackend) Checking for cache file: datasets/pseudo-camera-10k/aspect_ratio_bucket_indices.json
2024-08-05 21:10:09,693 [WARNING] (JsonMetadataBackend) No cache file found, creating new one.
2024-08-05 21:10:09,694 [INFO] (DataBackendFactory) (id=pseudo-camera-10k-flux) Refreshing aspect buckets on main process.
2024-08-05 21:10:09,694 [INFO] (BaseMetadataBackend) Discovering new files...
2024-08-05 21:10:13,224 [INFO] (BaseMetadataBackend) Compressed 0 existing files from 0.
2024-08-05 21:11:59,472 [INFO] (BaseMetadataBackend) Image processing statistics: {'total_processed': 14102, 'skipped': {'already_exists': 0, 'metadata_missing': 0, 'not_found': 0, 'too_small': 0, 'other': 0}}
2024-08-05 21:11:59,513 [INFO] (BaseMetadataBackend) Enforcing minimum image size of 0.5. This could take a while for very-large datasets.
2024-08-05 21:11:59,553 [INFO] (BaseMetadataBackend) Completed aspect bucket update.
2024-08-05 21:11:59,569 [INFO] (DataBackendFactory) Configured backend: {'id': 'pseudo-camera-10k-flux', 'config': {'crop': True, 'crop_aspect': 'square', 'crop_aspect_buckets': None, 'crop_style': 'center', 'disable_validation': False, 'resolution': 1.0, 'resolution_type': 'area', 'caption_strategy': 'filename', 'instance_data_dir': 'datasets/pseudo-camera-10k', 'maximum_image_size': 1.0, 'target_downsample_size': 1.0, 'config_version': 2}, 'dataset_type': 'image', 'data_backend': <helpers.data_backend.local.LocalDataBackend object at 0x7fcb8a4a7df0>, 'instance_data_dir': 'datasets/pseudo-camera-10k', 'metadata_backend': <helpers.metadata.backends.json.JsonMetadataBackend object at 0x7fcb8a4a7cd0>}
(Rank: 0)  | Bucket     | Image Count (per-GPU)
------------------------------
(Rank: 0)  | 1.0        | 14080
2024-08-05 21:11:59,570 [INFO] (DataBackendFactory) (id=pseudo-camera-10k-flux) Collecting captions.
2024-08-05 21:11:59,622 [INFO] (DataBackendFactory) (id=pseudo-camera-10k-flux) Initialise text embed pre-computation using the filename caption strategy. We have 14102 captions to process.
2024-08-05 21:25:46,726 [INFO] (DataBackendFactory) (id=pseudo-camera-10k-flux) Completed processing 14102 captions.
2024-08-05 21:25:46,727 [INFO] (DataBackendFactory) (id=pseudo-camera-10k-flux) Creating VAE latent cache.
2024-08-05 21:25:46,834 [INFO] (DataBackendFactory) (id=pseudo-camera-10k-flux) Discovering cache objects..
Processing bucket 1.0:   4%|██                                                         | 504/14080 [12:10<5:56:13,  1.57s/it]
Processing bucket 1.0:   5%|██▉                                                        | 710/14080 [17:22<5:41:32,  1.53s/it]
(id=pseudo-camera-10k-flux) Bucket 1.0 caching results: {'not_local': 0, 'already_cached': 4056, 'cached': 200, 'total': 14080}
2024-08-06 01:46:57,256 [INFO] (DataBackendFactory) Configured backend: {'id': 'pseudo-camera-10k-flux', 'config': {'crop': True, 'crop_aspect': 'square', 'crop_aspect_buckets': None, 'crop_style': 'center', 'disable_validation': False, 'resolution': 1.0, 'resolution_type': 'area', 'caption_strategy': 'filename', 'instance_data_dir': 'datasets/pseudo-camera-10k', 'maximum_image_size': 1.0, 'target_downsample_size': 1.0, 'config_version': 2, 'hash_filenames': True}, 'dataset_type': 'image', 'data_backend': <helpers.data_backend.local.LocalDataBackend object at 0x7fcb8a4a7df0>, 'instance_data_dir': 'datasets/pseudo-camera-10k', 'metadata_backend': <helpers.metadata.backends.json.JsonMetadataBackend object at 0x7fcb8a4a7cd0>, 'train_dataset': <helpers.multiaspect.dataset.MultiAspectDataset object at 0x7fcb8a4a5e10>, 'sampler': <helpers.multiaspect.sampler.MultiAspectSampler object at 0x7fcb8a4a56f0>, 'train_dataloader': <torch.utils.data.dataloader.DataLoader object at 0x7fcb8a4a68f0>, 'text_embed_cache': <helpers.caching.text_embeds.TextEmbeddingCache object at 0x7fcb8ab1e2c0>, 'vaecache': <helpers.caching.vae.VAECache object at 0x7fcb8981fd30>}
2024-08-06 01:46:57,451 [INFO] (validation) Precomputing the negative prompt embed for validations.
2024-08-06 01:46:57,608 [INFO] (__main__) Unloading text encoders, as they are not being trained.
2024-08-06 01:46:58,565 [INFO] (__main__) After nuking text encoders from orbit, we freed 9.11 GB of VRAM. The real memories were the friends we trained a model on along the way.
Fetching 3 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 11135.32it/s]
Traceback (most recent call last):
  File "/home/vwing/Documents/SimpleTuner/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/vwing/Documents/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/vwing/Documents/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/home/vwing/Documents/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/vwing/Documents/SimpleTuner/.venv/bin/python', 'train.py', '--model_type=lora', '--pretrained_model_name_or_path=black-forest-labs/FLUX.1-dev', '--enable_xformers_memory_efficient_attention', '--gradient_checkpointing', '--set_grads_to_none', '--gradient_accumulation_steps=4', '--resume_from_checkpoint=latest', '--snr_gamma=5', '--data_backend_config=config/multidatabackend.json', '--num_train_epochs=0', '--max_train_steps=30000', '--metadata_update_interval=65', '--adam_bfloat16', '--learning_rate=8e-7', '--lr_scheduler=sine', '--seed', '42', '--lr_warmup_steps=1000', '--output_dir=output/models', '--inference_scheduler_timestep_spacing=trailing', '--training_scheduler_timestep_spacing=trailing', '--report_to=wandb', '--allow_tf32', '--mixed_precision=bf16', '--base_model_precision=int8-quanto', '--lora_rank=4', '--flux', '--train_batch=10', '--max_workers=32', '--read_batch_size=25', '--write_batch_size=64', '--caption_dropout_probability=0.1', '--torch_num_threads=8', '--image_processing_batch_size=32', '--vae_batch_size=12', '--validation_prompt=ethnographic photography of teddy bear at a picnic', '--num_validation_images=1', '--validation_num_inference_steps=30', '--validation_seed=42', '--minimum_image_size=1024', '--resolution=1024', '--validation_resolution=1024x1024', '--resolution_type=pixel', '--checkpointing_steps=150', '--checkpoints_total_limit=2', '--validation_steps=100', '--tracker_run_name=simpletuner-sdxl', '--tracker_project_name=sdxl-training', '--validation_guidance=3', '--validation_guidance_rescale=0.0', '--validation_negative_prompt=blurry, cropped, ugly']' died with <Signals.SIGKILL: 9>.
```

Does this error mean that the training ran out of VRAM / RAM along the way? I'm not sure what to make of the error. I'm using WSL. Pip freeze:

```
absl-py==2.1.0
accelerate==0.31.0
aiohttp==3.9.3
aiosignal==1.3.1
appdirs==1.4.4
async-timeout==4.0.3
attrs==23.2.0
bitsandbytes==0.42.0
boto3==1.34.79
botocore==1.34.79
build==1.2.1
CacheControl==0.14.0
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
cleo==2.1.0
click==8.1.7
clip-interrogator==0.6.0
colorama==0.4.6
compel==2.0.2
crashtest==0.4.1
cryptography==43.0.0
dadaptation==3.2
datasets==2.14.4
deepspeed==0.10.3
diffusers @ git+https://github.com/huggingface/diffusers@15924bc73bfd74c769f23c8d2636d6c7514163a0
dill==0.3.7
distlib==0.3.8
docker-pycreds==0.4.0
dulwich==0.21.7
fastjsonschema==2.20.0
filelock==3.13.3
frozenlist==1.4.1
fsspec==2024.3.1
ftfy==6.2.0
gitdb==4.0.11
GitPython==3.1.43
grpcio==1.62.1
hjson==3.1.0
huggingface-hub==0.23.2
idna==3.6
importlib_metadata==7.1.0
installer==0.7.0
iterutils==0.1.6
jaraco.classes==3.4.0
jeepney==0.8.0
Jinja2==3.1.3
jmespath==1.0.1
keyring==24.3.1
lightning-utilities==0.11.2
Markdown==3.6
MarkupSafe==2.1.5
more-itertools==10.3.0
mpmath==1.3.0
msgpack==1.0.8
multidict==6.0.5
multiprocess==0.70.15
networkx==3.2.1
ninja==1.11.1.1
numpy==1.26.0
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.5.40
nvidia-nvtx-cu12==12.1.105
open-clip-torch==2.24.0
opencv-python==4.9.0.80
optimum-quanto==0.2.2
packaging==24.0
pandas==2.2.1
peft==0.9.0
pexpect==4.9.0
pillow==10.3.0
pkginfo==1.11.1
platformdirs==4.2.2
poetry==1.8.3
poetry-core==1.9.0
poetry-plugin-export==1.8.0
prodigyopt==1.0
protobuf==4.25.3
psutil==5.9.8
ptyprocess==0.7.0
py-cpuinfo==9.0.0
pyarrow==15.0.2
pycparser==2.22
pydantic==1.10.15
pyparsing==3.1.2
pyproject_hooks==1.1.0
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
rapidfuzz==3.9.5
regex==2023.12.25
requests==2.31.0
requests-toolbelt==1.0.0
s3transfer==0.10.1
safetensors==0.4.2
scipy==1.13.0
SecretStorage==3.3.3
sentencepiece==0.2.0
sentry-sdk==1.44.1
setproctitle==1.3.3
shellingham==1.5.4
six==1.16.0
smmap==5.0.1
sympy==1.12
tensorboard==2.16.2
tensorboard-data-server==0.7.2
timm==0.9.16
tokenizers==0.19.1
tomli==2.0.1
tomlkit==0.13.0
torch==2.3.0+cu121
torchaudio==2.3.0+cu121
torchmetrics==1.3.2
torchsde==0.2.6
torchvision==0.18.0+cu121
tqdm==4.66.2
trampoline==0.1.2
transformers==4.42.4
triton==2.3.0
triton-library==1.0.0rc3
trove-classifiers==2024.7.2
typing_extensions==4.11.0
tzdata==2024.1
urllib3==1.26.18
virtualenv==20.26.3
wandb==0.16.6
wcwidth==0.2.13
Werkzeug==3.0.2
xformers==0.0.26.post1
xxhash==3.4.1
yarl==1.9.4
zipp==3.18.1
```

I'd appreciate any and all help getting this running. Thank you.

**Comment by bghira** [comment]
aw man :[

that means your system ran out of actual system memory and did not have enough swap space to continue trying to load the transformer.

just after the text encoders unload is when we pull in the transformer.

unfortunately, there's not much to do - i don't think i can even catch this error and show a better message to the user, because it has run out of memory and we cannot allocate anymore.

SIGKILL-9 is an outside force that became very angry at us (the Linux kernel).

**Comment by Shed-The-Skin** [comment]
> aw man :[
> 
> that means your system ran out of actual system memory and did not have enough swap space to continue trying to load the transformer.
> 
> just after the text encoders unload is when we pull in the transformer.
> 
> unfortunately, there's not much to do - i don't think i can even catch this error and show a better message to the user, because it has run out of memory and we cannot allocate anymore.
> 
> SIGKILL-9 is an outside force that became very angry at us (the Linux kernel).

Thank you for the information and swift response, @bghira. Another question, if I may. I'm trying to train with 1x 4090 and I'm stilling maxing out my VRAM with 1020x1024, TRAIN_BATCH_SIZE=1, and adam_bf16 optimizer. [Updated training config.env](https://pastebin.com/8uqrKA5R). Does this sound right? The FLUX quickstart guide mentions training with 20 GB of VRAM, but I have yet to see my usage fall below at least 23.5 GB of VRAM. Thank you for your time and assistance.

**Comment by bghira** [comment]
gradient accumulation steps have some memory overhead on their own, though i'm not sure it is _that much_

**Comment by bghira** [comment]
you also might not want to use gradient accumulation steps with bf16 because of accuracy issues in the accumulation stage

**Comment by Shed-The-Skin** [comment]
Oddly enough when it crashes with SIGKILL 9, neither my RAM or VRAM are maxed out. My VRAM utilization was at about 2 GB when it crashed. Picture captured shortly after it crashed: https://files.catbox.moe/5ddmlq.jpg

**Comment by bghira** [comment]
it might just not have shown it. can you add `torch_dtype=torch.bfloat16` to line 776?

```
        from diffusers.models import FluxTransformer2DModel

        transformer = FluxTransformer2DModel.from_pretrained(
            args.pretrained_model_name_or_path,
            subfolder="transformer", torch_dype=torch.bfloat16,
            **pretrained_load_args,
        )
```

**Comment by bghira** [comment]
alternatively you can try the main branch latest commits. i have put that in, so we load model directly into the correct precision

**Comment by burgalon** [comment]
with recent changes in main branch i get constant SIGKILL. `731ccdf5` works though (with quanto, getting SIGKILL on 731ccdf5 too...)

**Comment by mhirki** [comment]
Commit 3310c672d4c7b688373026a8faf0eba2ea267709 may have increased RAM usage if the text encoders remain in RAM during training. One idea would be to partially revert this commit so that text encoders are moved to the "meta" device.

**Comment by burgalon** [comment]
> Have a look at the output `dmesg` command. If it's saying something about OOM killer, you're running out of RAM.

unfortunately can't run dmesg as I'm running in a container. `dmesg: read kernel buffer failed: Operation not permitted`

**Comment by OliviaOliveiira** [comment]
> gradient accumulation steps have some memory overhead on their own, though i'm not sure it is _that much_

it actually is that much, I'm looking at my wandb and it takes this much vram, and the training lasts 5h, however, as soon as I shift from batch 1 gr_a_steps 1 to gr_a_steps 2, it all goes bonkers and I get 9 hours of training
![image](https://github.com/user-attachments/assets/bcc1c11a-68cb-476a-ad7c-86d555ea9b22)

**Comment by burgalon** [comment]
the line which gets SIGKILLed is the freezing of the model in `_qunato_model`

**Comment by bghira** [comment]
it needs a lot of memory to quantise

**Comment by bghira** [comment]
try `grep oom /proc/vmstat` which will show you how many oomkiller events have occurred without dmesg access

**Comment by davizca** [comment]
> it needs a lot of memory to quantise

So this is a error which can be solved by installing more RAM in the computer? or it's VRAM related?

**Comment by bghira** [comment]
system RAM yes

**Comment by bghira** [comment]
added a note about this to the flux quickstart

**Comment by mhirki** [comment]
System RAM usage should now be several gigabytes lower now that pull request #694 has been merged.

**Comment by Roy3838** [comment]
Hey! Finding out in the morning that it died somewhere along the way is such a waste of a whole night's compute. 
Built a free/FOSS tool for exactly this: https://github.com/Roy3838/Observer 
It's a tiny local agent that watches your screen/terminal and pings or calls you the moment it sees the run actually stop or crash, so you catch it hours earlier instead of at breakfast. 
Inference is local, nothing leaves your machine. Happy to answer anything :D
