### ISSUE TITLE
No images were discovered by the bucket manager.

### ISSUE THREAD

**Issue by thojmr** [bghira/SimpleTuner#657]
Ok, I've spent 2 days trying to get past this, so could someone verify that my configs look correct here?

multidatasetbackend.json
```json
[
    {
        "id": "image_dataset",
        "type": "local",
        "text_embeds": "text_embeds",
        "instance_data_dir": "/root/images/flux_test/dataset",
        "cache_dir_vae": "/root/images/flux_test/image_cache",
        "crop": true,
        "crop_aspect": "square",
        "resolution_type": "pixel",
        "resolution": 1024,
        "minimum_image_size": 768,
        "caption_strategy": "textfile",
        "skip_file_discovery": "vae,aspect,text,metadata,caption,captions"
    },
    {
        "id": "text_embeds",
        "type": "local",
        "dataset_type": "text_embeds",
        "default": true,
        "cache_dir": "/root/images/flux_test/text_embeds"
    }
]
```

The folder paths are valid, and the dataset is typical of text to image pairs like `image_1.jpg`, `image_1.txt` in `/root/images/flux_test/dataset`.

Debug log
```
2024-08-06 17:09:09,489 [WARNING] (ArgsParser) The VAE model madebyollin/sdxl-vae-fp16-fix is not compatible. Please use a compatible VAE to eliminate this warning. The baked-in VAE will be used, instead.
2024-08-06 17:09:09,490 [INFO] (ArgsParser) VAE Model: black-forest-labs/FLUX.1-schnell
2024-08-06 17:09:09,490 [INFO] (ArgsParser) Default VAE Cache location: 
2024-08-06 17:09:09,491 [INFO] (ArgsParser) Text Cache location: cache
2024-08-06 17:09:09,491 [WARNING] (ArgsParser) -!- Flux supports a max length of 256 tokens, but you have supplied `--i_know_what_i_am_doing`, so this limit will not be enforced. -!-
2024-08-06 17:09:09,491 [WARNING] (ArgsParser) The model will begin to collapse after a short period of time, if the model you are continuing from has not been tuned beyond 256 tokens.
2024-08-06 17:09:09,491 [WARNING] (ArgsParser) Gradient accumulation steps are enabled, but gradient precision is set to 'unmodified'. This may lead to numeric instability. Consider setting --gradient_precision=fp32.
2024-08-06 17:09:09,557 [INFO] (__main__) Enabling tf32 precision boost for NVIDIA devices due to --allow_tf32.
2024-08-06 17:09:09,558 [INFO] (__main__) Load tokenizers
2024-08-06 17:09:10,575 [INFO] (__main__) Loading OpenAI CLIP-L text encoder from black-forest-labs/FLUX.1-schnell/text_encoder..
2024-08-06 17:09:15,266 [INFO] (__main__) Loading T5 XXL v1.1 text encoder from black-forest-labs/FLUX.1-schnell/text_encoder_2..
2024-08-06 17:11:07,439 [INFO] (__main__) Load VAE: black-forest-labs/FLUX.1-schnell
2024-08-06 17:11:11,256 [INFO] (__main__) Moving text encoder to GPU.
2024-08-06 17:11:11,726 [INFO] (__main__) Moving text encoder 2 to GPU.
2024-08-06 17:11:20,707 [INFO] (__main__) Initialising VAE in bf16 precision, you may specify a different value if preferred: bf16, fp32, default
2024-08-06 17:11:21,016 [INFO] (__main__) Loaded VAE into VRAM.
2024-08-06 17:11:21,039 [INFO] (DataBackendFactory) Loading data backend config from config/multidatabackend.json
2024-08-06 17:11:21,042 [INFO] (DataBackendFactory) Configuring text embed backend: text_embeds
2024-08-06 17:11:21,420 [INFO] (TextEmbeddingCache) (Rank: 0) (id=text_embeds) Listing all text embed cache entries
2024-08-06 17:11:21,429 [INFO] (DataBackendFactory) Pre-computing null embedding
2024-08-06 17:11:26,435 [INFO] (DataBackendFactory) Completed loading text embed services.
2024-08-06 17:11:26,436 [INFO] (DataBackendFactory) Configuring data backend: image_dataset
2024-08-06 17:11:26,439 [INFO] (DataBackendFactory) (id=image_dataset) Loading bucket manager.
2024-08-06 17:11:26,447 [INFO] (JsonMetadataBackend) Checking for cache file: /root/images/flux_test/dataset/aspect_ratio_bucket_indices.json
2024-08-06 17:11:26,448 [WARNING] (JsonMetadataBackend) No cache file found, creating new one.
2024-08-06 17:11:26,449 [INFO] (DataBackendFactory) Configured backend: {'id': 'image_dataset', 'config': {'crop': True, 'crop_aspect': 'square', 'crop_aspect_buckets': None, 'crop_style': 'random', 'disable_validation': False, 'resolution': 1024, 'resolution_type': 'pixel', 'caption_strategy': 'textfile', 'instance_data_dir': '/root/images/flux_test/dataset', 'maximum_image_size': None, 'target_downsample_size': None, 'config_version': 2}, 'dataset_type': 'image', 'data_backend': <helpers.data_backend.local.LocalDataBackend object at 0x7f7a22e93eb0>, 'instance_data_dir': '/root/images/flux_test/dataset', 'metadata_backend': <helpers.metadata.backends.json.JsonMetadataBackend object at 0x7f7a22e93ee0>}
2024-08-06 17:11:26,456 [ERROR] (__main__) No images were discovered by the bucket manager in the dataset: image_dataset., traceback: Traceback (most recent call last):
  File "/root/data/train.py", line 663, in main
    configure_multi_databackend(
  File "/root/data/helpers/data_backend/factory.py", line 771, in configure_multi_databackend
    raise Exception(
Exception: No images were discovered by the bucket manager in the dataset: image_dataset.

```

I am completely out of ideas.  I've tried so many different combinations now.

**Comment by bghira** [comment]
can you try blanking or removing `skip_file_discovery` option?

**Comment by thojmr** [comment]
Seems like setting ` "skip_file_discovery": ""` actually worked.  Not sure why since none of my dataset files had those words in them.

**Comment by bghira** [comment]
see [DATALOADER.md](https://github.com/bghira/SimpleTuner/blob/main/documentation/DATALOADER.md)

![image](https://github.com/user-attachments/assets/a3e56c8a-529c-4b40-a78e-552d1fb72d2d)

i would like to improve the wording here, or somewhere else that makes sense. do you have any ideas where it 'went wrong' for the understanding of this parameter's purpose? i'm not sure which example it came from.

**Comment by thojmr** [comment]
Ah, I assumed it was matching on files names and skipping individual files since it has "file" in the name.  It if were "skip_folder_discovery", or "skip_dataset_discovery" it would have been more clear to me.

**Comment by bghira** [comment]
the way this functions is each component in the list is skipped at startup;

- metadata: skip scanning for image size information / crop details
- aspect: skip aspect bucket updates
- vae: skip discovery of missing vae cache objects
- text: skip text embed generation and missing item discovery

for datasets with many many (millions) of images, these options improve resume time quite a lot.

**Comment by thojmr** [comment]
That makes more sense.  I would place those bullet points in the documentation for clarity.
