### ISSUE TITLE
Flux sample generation error

### ISSUE THREAD

**Issue by OliviaOliveiira** [bghira/SimpleTuner#668]
I've reached the sample point during training (200 steps) and encountered an error

Epoch 1/2, Steps:   4%|█▍                                 | 200/5000 [36:58<14:48:34, 11.11s/it, lr=9.77e-6, step_loss=0.514][2024-08-07 12:11:44,428] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
cannot import name 'log' from 'torch.distributed.elastic.agent.server.api' (/home/miya123/miniconda3/envs/py310_env/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py)
Traceback (most recent call last):
  File "/home/miya123/Desktop/Huita/SimpleTuner/train.py", line 2750, in <module>
    main()
  File "/home/miya123/Desktop/Huita/SimpleTuner/train.py", line 2418, in main
    validation.run_validations(validation_type="intermediary", step=step)
  File "/home/miya123/Desktop/Huita/SimpleTuner/helpers/training/validation.py", line 857, in run_validations
    self.setup_pipeline(validation_type)
  File "/home/miya123/Desktop/Huita/SimpleTuner/helpers/training/validation.py", line 986, in setup_pipeline
    extra_pipeline_kwargs["transformer"] = unwrap_model(
  File "/home/miya123/Desktop/Huita/SimpleTuner/helpers/training/wrappers.py", line 5, in unwrap_model
    model = accelerator.unwrap_model(model)
  File "/home/miya123/miniconda3/envs/py310_env/lib/python3.10/site-packages/accelerate/accelerator.py", line 2515, in unwrap_model
    return extract_model_from_parallel(model, keep_fp32_wrapper)
  File "/home/miya123/miniconda3/envs/py310_env/lib/python3.10/site-packages/accelerate/utils/other.py", line 80, in extract_model_from_parallel
    from deepspeed import DeepSpeedEngine
  File "/home/miya123/miniconda3/envs/py310_env/lib/python3.10/site-packages/deepspeed/__init__.py", line 22, in <module>
    from . import module_inject
  File "/home/miya123/miniconda3/envs/py310_env/lib/python3.10/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/home/miya123/miniconda3/envs/py310_env/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 567, in <module>
    from ..pipe import PipelineModule
  File "/home/miya123/miniconda3/envs/py310_env/lib/python3.10/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/miya123/miniconda3/envs/py310_env/lib/python3.10/site-packages/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/miya123/miniconda3/envs/py310_env/lib/python3.10/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "/home/miya123/miniconda3/envs/py310_env/lib/python3.10/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 26, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/home/miya123/miniconda3/envs/py310_env/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 41, in <module>
    from ..elasticity import (
  File "/home/miya123/miniconda3/envs/py310_env/lib/python3.10/site-packages/deepspeed/elasticity/__init__.py", line 10, in <module>
    from .elastic_agent import DSElasticAgent
  File "/home/miya123/miniconda3/envs/py310_env/lib/python3.10/site-packages/deepspeed/elasticity/elastic_agent.py", line 9, in <module>
    from torch.distributed.elastic.agent.server.api import log, _get_socket_with_port
ImportError: cannot import name 'log' from 'torch.distributed.elastic.agent.server.api' (/home/miya123/miniconda3/envs/py310_env/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py)

**Comment by mhirki** [comment]
You seem to have old version of deepspeed combined with torch-2.4.0 (see issue #656). Nvidia dependencies were updated in commit f9b0ebb6821409a6b0d83b7b23f8fefc7ee61e01 recently so you can try reinstalling latest dependencies via poetry.

**Comment by OliviaOliveiira** [comment]
> You seem to have old version of deepspeed combined with torch-2.4.0 (see issue #656). Nvidia dependencies were updated in commit [f9b0ebb](https://github.com/bghira/SimpleTuner/commit/f9b0ebb6821409a6b0d83b7b23f8fefc7ee61e01) recently so you can try reinstalling latest dependencies via poetry.

Will try, thanks!

**Comment by OliviaOliveiira** [comment]
> You seem to have old version of deepspeed combined with torch-2.4.0 (see issue #656). Nvidia dependencies were updated in commit [f9b0ebb](https://github.com/bghira/SimpleTuner/commit/f9b0ebb6821409a6b0d83b7b23f8fefc7ee61e01) recently so you can try reinstalling latest dependencies via poetry.

Updated through poetry no root, yet the cuda broke, so I had to upgrade bitsandbytes manually

**Comment by bghira** [comment]
that's in main now. thanks so much!
