### ISSUE TITLE
bitsnbytes error on first run of train.sh

### ISSUE THREAD

**Issue by bghira** [bghira/SimpleTuner#671]
I am using server with cuda 12.1 pre installed that seems to work fine.
But I got bitsnbytes error on first run of train.sh.
And now when running a train.sh getting a new error:
``` log
./train.sh
Traceback (most recent call last):
  File "/workspace/SimpleTuner/.venv/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 32, in <module>
    import torch
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/__init__.py", line 290, in <module>
    from torch._C import *  # noqa: F403
ImportError: /workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
```

_Originally posted by @a-l-e-x-d-s-9 in https://github.com/bghira/SimpleTuner/issues/656#issuecomment-2273576547_

**Comment by bghira** [comment]
@a-l-e-x-d-s-9 can you try #674 the new dockerfile as a possible deployment method
