### ISSUE TITLE
Specifying both train_text_encoder and text_encoder_lr at the same time results in an error

### ISSUE THREAD

**Issue by leonary** [bghira/SimpleTuner#684]
```
2024-08-09 02:15:39,553 [WARNING] (__main__) Learning rates were provided both for the transformer and the text encoder- e.g. text_encoder_lr: 4e-05 and learning_rate: 0.0004. When using prodigy only learning_rate is used as the initial learning rate.
new(): invalid data type 'str'
Traceback (most recent call last):
  File "/root/autodl-tmp/SimpleTuner/train.py", line 2765, in <module>
    main()
  File "/root/autodl-tmp/SimpleTuner/train.py", line 1248, in main
    params_to_optimize[1]["lr"] = args.learning_rate
TypeError: new(): invalid data type 'str'
```
Flux lora training.
The part of the code that caused the error:
```
if args.train_text_encoder and args.text_encoder_lr:
            logger.warn(
                f"Learning rates were provided both for the {'unet' if unet is not None else 'transformer'} and the text encoder- e.g. text_encoder_lr:"
                f" {args.text_encoder_lr} and learning_rate: {args.learning_rate}. "
                f"When using prodigy only learning_rate is used as the initial learning rate."
            )
            # changes the learning rate of text_encoder_parameters_one and text_encoder_parameters_two to be
            # --learning_rate
            params_to_optimize[1]["lr"] = args.learning_rate
            params_to_optimize[2]["lr"] = args.learning_rate
            if args.sd3:
                # Third text encoder.
                params_to_optimize[3]["lr"] = args.learning_rate

        optimizer = optimizer_class(
            params_to_optimize,
            **extra_optimizer_args,
        )
```

**Comment by bghira** [comment]
use `float(args.learning_rate)` but that feature is pretty experimental and untested as it is

**Comment by leonary** [comment]
> use `float(args.learning_rate)` but that feature is pretty experimental and untested as it is (ergo I will assume this isn't the final issue you will reach)

Print the result of `print(params_to_optimize[1])`:
```
Parameter containing:
tensor([[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.],
...,
[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.]], dtype=torch.bfloat16,
requires_grad=True)
```
`params_to_optimize[1]` is not a dictionary containing the lr key.

**Comment by bghira** [comment]
i think the text encoder peft training was updated upstream at some point and i never went and updated this trainer's integration with it. if you would like to open a pull request, that will be welcomed. but i don't believe i will be able to spend any time on text encoder training myself

**Comment by leonary** [comment]
I don’t know how to write code for this, so let’s not consider training the text encoder for now. Thanks for your help.
