### ISSUE TITLE
NameError: name 'noise_scheduler_copy' is not defined

### ISSUE THREAD

**Issue by AmithisCurious** [bghira/SimpleTuner#692]
Hi, New to git here, Absolutely love your work, but in the new update for flux, in the file __init__.py noise_scheduler_copy does not seem to be defined,
Here's the Traceback to the error I'm getting,

name 'noise_scheduler_copy' is not defined
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train.py", line 2776, in <module>
    main()
  File "/workspace/SimpleTuner/train.py", line 496, in main
    update_flux_schedule_to_fast(
  File "/workspace/SimpleTuner/helpers/models/flux/__init__.py", line 8, in update_flux_schedule_to_fast
    print(f"sigmas before: {noise_scheduler_copy.sigmas}")
NameError: name 'noise_scheduler_copy' is not defined

Digging into the the init file, I found this function starting at line 5 

```
def update_flux_schedule_to_fast(args, noise_scheduler_to_copy):
    if args.flux_fast_schedule:
        # 4-step noise schedule [0.7, 0.1, 0.1, 0.1] from SD3-Turbo paper
        print(f"sigmas before: {noise_scheduler_copy.sigmas}")
        for i in range(0, 250):
            noise_scheduler_copy.sigmas[i] = 1.0
        for i in range(250, 500):
            noise_scheduler_copy.sigmas[i] = 0.3
        for i in range(500, 750):
            noise_scheduler_copy.sigmas[i] = 0.2
        for i in range(750, 1000):
            noise_scheduler_copy.sigmas[i] = 0.1
        print(f"sigmas after: {noise_scheduler_copy.sigmas}")
    return noise_scheduler_to_copy
```

I assume the simple fix to this would be to just fix the variable names, Requesting to initiate a PR for this fix

**Comment by AmithisCurious** [comment]
yeah that is correct

**Comment by bghira** [comment]
godspeed

**Comment by mhirki** [comment]
I would also advise sticking to the Dev model but if you insist on training the Schnell model, you may want to read my final comments on the matter here:
https://github.com/bghira/SimpleTuner/commit/f628380510f589944692b9d9f05c438d15c1f212#commitcomment-145191420

Some earlier comments are also here:
https://github.com/bghira/SimpleTuner/pull/622
