### ISSUE TITLE
【Need Help】Exception: Failed to load tokenizer

### ISSUE THREAD

**Issue by NBSTpeterhill** [bghira/SimpleTuner#697]
![photo_2024-08-09_20-38-18](https://github.com/user-attachments/assets/b4571f72-5e84-4697-93af-9525cf52f024)

**When training FLUX, I have this question, who knows how to fix it ?**

/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/nvidia/nvjitlink/lib
2024-08-09 18:46:36,362 [WARNING] (ArgsParser) The VAE model madebyollin/sdxl-vae-fp16-fix is not compatible. Please use a compatible VAE to eliminate this warning. The baked-in VAE will be used, instead.
2024-08-09 18:46:36,364 [INFO] (ArgsParser) VAE Model: black-forest-labs/FLUX.1-dev
2024-08-09 18:46:36,365 [INFO] (ArgsParser) Default VAE Cache location: 
2024-08-09 18:46:36,366 [INFO] (ArgsParser) Text Cache location: cache
2024-08-09 18:46:36,367 [WARNING] (ArgsParser) Updating T5 XXL tokeniser max length to 512 for Flux.
2024-08-09 18:46:36,368 [WARNING] (ArgsParser) Flux Dev expects around 28 or fewer inference steps. Consider limiting --validation_num_inference_steps to 28.
2024-08-09 18:46:36,369 [WARNING] (ArgsParser) Gradient accumulation steps are enabled, but gradient precision is set to 'unmodified'. This may lead to numeric instability. Consider setting --gradient_precision=fp32.
2024-08-09 18:46:36,700 [WARNING] (accelerate.utils.other) Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
2024-08-09 18:46:36,760 [INFO] (__main__) Enabling tf32 precision boost for NVIDIA devices due to --allow_tf32.
2024-08-09 18:46:36,762 [INFO] (__main__) Load tokenizers
2024-08-09 18:46:37,093 [WARNING] (__main__) Primary tokenizer (CLIP-L/14) failed to load. Continuing to test whether we have just the secondary tokenizer..
Error: -> Can't load tokenizer for 'black-forest-labs/FLUX.1-dev'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'black-forest-labs/FLUX.1-dev' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
Traceback: Traceback (most recent call last):
  File "/workspace/SimpleTuner/train.py", line 183, in get_tokenizers
    tokenizer_1 = CLIPTokenizer.from_pretrained(**tokenizer_kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2147, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'black-forest-labs/FLUX.1-dev'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'black-forest-labs/FLUX.1-dev' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

2024-08-09 18:46:37,282 [WARNING] (__main__) Could not load secondary tokenizer (OpenCLIP-G/14). Cannot continue: Can't load tokenizer for 'black-forest-labs/FLUX.1-dev'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'black-forest-labs/FLUX.1-dev' is the correct path to a directory containing all relevant files for a T5TokenizerFast tokenizer.
Failed to load tokenizer
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train.py", line 2777, in <module>
    main()
  File "/workspace/SimpleTuner/train.py", line 438, in main
    tokenizer_1, tokenizer_2, tokenizer_3 = get_tokenizers(args)
  File "/workspace/SimpleTuner/train.py", line 247, in get_tokenizers
    raise Exception("Failed to load tokenizer")
Exception: Failed to load tokenizer

**Comment by bghira** [comment]
you probably have to do `huggingface-cli login` as it is a gated model.

**Comment by NBSTpeterhill** [comment]
> you probably have to do `huggingface-cli login` as it is a gated model.
Thanks but,
I successed login already, but still, the tokenizer just refuse me…………as the picture below shows.
![QQ20240809-210227](https://github.com/user-attachments/assets/1dc33983-6096-4e9e-b6f9-47990e92da2a)

**Comment by NBSTpeterhill** [comment]
![QQ20240809-210351](https://github.com/user-attachments/assets/b42dbd20-2099-420c-b059-4a4404e32b7c)
Here, the linux login.
But not work.

**Comment by bghira** [comment]
did you set FLUX=true ?

**Comment by NBSTpeterhill** [comment]
> did you set FLUX=true ?
Yes
I watched your video on Youtuber step by step (Thanks for sharing again)

here is my config
[NBST-Flux-config.zip](https://github.com/user-attachments/files/16565871/NBST-Flux-config.zip)

**Comment by NBSTpeterhill** [comment]
![QQ20240809-211100](https://github.com/user-attachments/assets/cc25617c-2557-4adf-962a-6f67ece632ae)
Linux usage is also on PODs cloud GPU

**Comment by bghira** [comment]
- `huggingface-cli whoami` works?
- i'm not sure how to do `ls` via huggingface-cli, but you can do `huggingface-cli download --repo-type=model black-forest-labs/FLUX.1-dev --local-dir=flux-download` and then delete the `flux-download` folder after testing

i don't have any instructional videos, so it must've been somebody else's

**Comment by mhirki** [comment]
Make sure you don't have PIXART_SIGMA=true or KOLORS=true in your config.env. You get the warning "Could not load secondary tokenizer (OpenCLIP-G/14)" only if you have one of those enabled.

**Comment by NBSTpeterhill** [comment]
> * `huggingface-cli whoami` works? 作品？
> * i'm not sure how to do `ls` via huggingface-cli, but you can do `huggingface-cli download --repo-type=model black-forest-labs/FLUX.1-dev --local-dir=flux-download` and then delete the `flux-download` folder after testing我不知道如何通过 Huggingface-cli 执行`ls` ，但您可以执行`huggingface-cli download --repo-type=model black-forest-labs/FLUX.1-dev --local-dir=flux-download`和然后测试后删除`flux-download`文件夹
> 
> i don't have any instructional videos, so it must've been somebody else's我没有任何教学视频，所以它一定是别人的

Thanks for your reply, seems Hugging face refuse my access.
![QQ截图20240809212259](https://github.com/user-attachments/assets/8aef4961-b0fd-44b3-82da-3ce043642377)

**Comment by NBSTpeterhill** [comment]
> Make sure you don't have PIXART_SIGMA=true or KOLORS=true in your config.env. You get the warning "Could not load secondary tokenizer (OpenCLIP-G/14)" only if you have one of those enabled.确保 config.env 中没有 PIXART_SIGMA=true 或 KOLORS=true。仅当您启用了其中之一时，您才会收到警告“无法加载辅助标记器 (OpenCLIP-G/14)”。



> Make sure you don't have PIXART_SIGMA=true or KOLORS=true in your config.env. You get the warning "Could not load secondary tokenizer (OpenCLIP-G/14)" only if you have one of those enabled.确保 config.env 中没有 PIXART_SIGMA=true 或 KOLORS=true。仅当您启用了其中之一时，您才会收到警告“无法加载辅助标记器 (OpenCLIP-G/14)”。

[NBST-Flux-config.zip](https://github.com/user-attachments/files/16565994/NBST-Flux-config.zip)
Thanks, here is my config. Can I know more detiles about what is your suggestions?

**Comment by bghira** [comment]
i think it's really just the permissions error - if you can work that out, i think it will just work for you.

**Comment by NBSTpeterhill** [comment]
> i think it's really just the permissions error - if you can work that out, i think it will just work for you.

Thanks for you patient，I made a new huggingface API Key 【Read】, and now it works.
^^
![QQ20240809-213214](https://github.com/user-attachments/assets/96f63f82-6522-4ba1-b315-1afe6ee671c1)

**Comment by mhirki** [comment]
> [NBST-Flux-config.zip](https://github.com/user-attachments/files/16565994/NBST-Flux-config.zip) Thanks, here is my config. Can I know more detiles about what is your suggestions?

I had a look at your config.env file. You probably don't want LR_SCHEDULE="cosine" together with OPTIMIZER="prodigy". Prodigy is an adaptive optimizer and you should use either LR_SCHEDULER="constant" or LR_SCHEDULE="constant_with_warmup".

And just ignore my previous comment. I was reading the code a bit too hastily.

**Comment by hongminpark** [comment]
In my case, I had to manually visit huggingface flux repository, and then clicked grant access button.
Make sure you have granted access to repository/model. 

<img width="1141" alt="Screenshot 2024-08-12 at 09 29 23" src="https://github.com/user-attachments/assets/f6757aef-4520-461c-87ae-130ea8fb1bfa">

Or you might check token permission to have read/write full access.
