### ISSUE TITLE
Error generating validation images when training SDXL LoRA

### ISSUE THREAD

**Issue by roblaughter** [bghira/SimpleTuner#698]
**Issue:** error validating images when generating SDXL LoRA. Seems to be similar to #546 

Flux training generated validation images just fine. 

Commenting out [these lines](https://github.com/bghira/SimpleTuner/blob/596f7b4a6dbf3b62de96568b50a6d10ac97a6a8b/helpers/training/validation.py#L621) let the validation run. 

```
for text_encoder in self.prompt_handler.text_encoders:
        # Can't remember why we move this to the GPU right here..
        if text_encoder is not None:
            text_encoder = text_encoder.to(
                device=self.accelerator.device, dtype=self.weight_dtype
            )
    [
        current_validation_prompt_embeds,
        self.validation_negative_prompt_embeds,
    ] = self.prompt_handler.compel.pad_conditioning_tensors_to_same_length(
        [
            current_validation_prompt_embeds,
            self.validation_negative_prompt_embeds,
        ]
    )
    for text_encoder in self.prompt_handler.text_encoders:
        # Or why we move it back...maybe it's a Compel oddity :(
        if text_encoder is not None:
            text_encoder = text_encoder.to("cpu")
```

**Traceback**

```
2024-08-09 20:47:07,350 [ERROR] (validation) Error gathering text embed for validation prompt : Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select), traceback: Traceback (most recent call last):
  File "/workspace/SimpleTuner/helpers/training/validation.py", line 1193, in validate_prompt
    extra_validation_kwargs.update(self._gather_prompt_embeds(prompt))
  File "/workspace/SimpleTuner/helpers/training/validation.py", line 630, in _gather_prompt_embeds
    ] = self.prompt_handler.compel.pad_conditioning_tensors_to_same_length(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/compel.py", line 266, in pad_conditioning_tensors_to_same_length
    emptystring_conditioning = self.build_conditioning_tensor("")
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/compel.py", line 112, in build_conditioning_tensor
    conditioning, _ = self.build_conditioning_tensor_for_conjunction(conjunction)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/compel.py", line 186, in build_conditioning_tensor_for_conjunction
    this_conditioning, this_options = self.build_conditioning_tensor_for_prompt_object(p)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/compel.py", line 218, in build_conditioning_tensor_for_prompt_object
    return self._get_conditioning_for_flattened_prompt(prompt), {}
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/compel.py", line 282, in _get_conditioning_for_flattened_prompt
    return self.conditioning_provider.get_embeddings_for_weighted_prompt_fragments(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/embeddings_provider.py", line 524, in get_embeddings_for_weighted_prompt_fragments
    outputs = [provider.get_embeddings_for_weighted_prompt_fragments(text_batch, fragment_weights_batch, should_return_tokens=should_return_tokens, device=device) for provider in self.embedding_providers]
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/embeddings_provider.py", line 524, in <listcomp>
    outputs = [provider.get_embeddings_for_weighted_prompt_fragments(text_batch, fragment_weights_batch, should_return_tokens=should_return_tokens, device=device) for provider in self.embedding_providers]
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/embeddings_provider.py", line 120, in get_embeddings_for_weighted_prompt_fragments
    base_embedding = self.build_weighted_embedding_tensor(tokens, per_token_weights, mask, device=device)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/embeddings_provider.py", line 357, in build_weighted_embedding_tensor
    empty_z = self._encode_token_ids_to_embeddings(empty_token_ids)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/embeddings_provider.py", line 390, in _encode_token_ids_to_embeddings
    text_encoder_output = self.text_encoder(token_ids,
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 806, in forward
    return self.text_model(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 698, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 218, in forward
    inputs_embeds = self.token_embedding(input_ids)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 164, in forward
    return F.embedding(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2267, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

2024-08-09 20:47:07,357 [ERROR] (validation) Error gathering text embed for validation prompt a cute puppy dog: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select), traceback: Traceback (most recent call last):
  File "/workspace/SimpleTuner/helpers/training/validation.py", line 1193, in validate_prompt
    extra_validation_kwargs.update(self._gather_prompt_embeds(prompt))
  File "/workspace/SimpleTuner/helpers/training/validation.py", line 630, in _gather_prompt_embeds
    ] = self.prompt_handler.compel.pad_conditioning_tensors_to_same_length(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/compel.py", line 266, in pad_conditioning_tensors_to_same_length
    emptystring_conditioning = self.build_conditioning_tensor("")
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/compel.py", line 112, in build_conditioning_tensor
    conditioning, _ = self.build_conditioning_tensor_for_conjunction(conjunction)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/compel.py", line 186, in build_conditioning_tensor_for_conjunction
    this_conditioning, this_options = self.build_conditioning_tensor_for_prompt_object(p)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/compel.py", line 218, in build_conditioning_tensor_for_prompt_object
    return self._get_conditioning_for_flattened_prompt(prompt), {}
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/compel.py", line 282, in _get_conditioning_for_flattened_prompt
    return self.conditioning_provider.get_embeddings_for_weighted_prompt_fragments(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/embeddings_provider.py", line 524, in get_embeddings_for_weighted_prompt_fragments
    outputs = [provider.get_embeddings_for_weighted_prompt_fragments(text_batch, fragment_weights_batch, should_return_tokens=should_return_tokens, device=device) for provider in self.embedding_providers]
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/embeddings_provider.py", line 524, in <listcomp>
    outputs = [provider.get_embeddings_for_weighted_prompt_fragments(text_batch, fragment_weights_batch, should_return_tokens=should_return_tokens, device=device) for provider in self.embedding_providers]
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/embeddings_provider.py", line 120, in get_embeddings_for_weighted_prompt_fragments
    base_embedding = self.build_weighted_embedding_tensor(tokens, per_token_weights, mask, device=device)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/embeddings_provider.py", line 357, in build_weighted_embedding_tensor
    empty_z = self._encode_token_ids_to_embeddings(empty_token_ids)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/compel/embeddings_provider.py", line 390, in _encode_token_ids_to_embeddings
    text_encoder_output = self.text_encoder(token_ids,
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 806, in forward
    return self.text_model(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 698, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 218, in forward
    inputs_embeds = self.token_embedding(input_ids)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 164, in forward
    return F.embedding(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2267, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
```

**Comment by bghira** [comment]
can you try adding `--disable_compel` to the parameters?

**Comment by roblaughter** [comment]
I did try that, but may have tried to set the parameter in the wrong place. 
I'm in the middle of a run—I'll test when it's done!

**Comment by bghira** [comment]
i've gone a step further and simply made compel go bye-bye.
