### ISSUE TITLE
Flux Lora training fails after latest PRs.

### ISSUE THREAD

**Issue by TheDuckingDuck** [bghira/SimpleTuner#700]
Full Error:
```
2024-08-09 21:07:01,025 [INFO] (__main__) Using LoRA training mode (rank=32)
2024-08-09 21:07:01,246 [INFO] (root) Weight: (3072, 3072) | Rank: 32 | Num Iter: 1 | Num Bits: 4
Creating a new Tensor subclass Params4bit but the raw Tensor object is already associated to a python object of type QBytesTensor
Traceback (most recent call last):
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/train.py", line 2800, in <module>
    main()
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/train.py", line 966, in main
    transformer.add_adapter(transformer_lora_config)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/loaders/peft.py", line 146, in add_adapter
    inject_adapter_in_model(adapter_config, self, adapter_name)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/peft/mapping.py", line 166, in inject_adapter_in_model
    peft_model = tuner_cls(model, peft_config, adapter_name=adapter_name)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 111, in __init__
    super().__init__(model, config, adapter_name)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 147, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 302, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, current_key=key)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 182, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 257, in _create_new_module
    new_module = dispatcher(target, adapter_name, lora_config=lora_config, **kwargs)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 858, in dispatch_default
    new_module = Linear(target, adapter_name, **kwargs)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 289, in __init__
    self.update_layer(
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 109, in update_layer
    self.loftq_init(adapter_name)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 161, in loftq_init
    qweight, lora_A, lora_B = loftq_init(weight, **kwargs)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/peft/utils/loftq_utils.py", line 212, in loftq_init
    qweight = bnb.nn.Params4bit(
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 227, in __new__
    self = torch.Tensor._make_subclass(cls, data, requires_grad)
RuntimeError: Creating a new Tensor subclass Params4bit but the raw Tensor object is already associated to a python object of type QBytesTensor
```

**Comment by TheDuckingDuck** [comment]
I thought maybe it would work with lora_init_type=default but that errors with;
```
2024-08-09 21:15:21,082 [WARNING] (helpers.training.quantisation) An earlier experimental build of this code erroneously used int8 instead of fp8. If you are resuming training and see errors, please use int8 instead of fp8.
'Parameter' object has no attribute 'qtype'
Traceback (most recent call last):
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/train.py", line 2800, in <module>
    main()
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/train.py", line 1605, in main
    quantoise(
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/helpers/training/quantisation/__init__.py", line 56, in quantoise
    _quanto_model(transformer, args.base_model_precision)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/helpers/training/quantisation/__init__.py", line 48, in _quanto_model
    quantize(model, weights=weight_quant)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/optimum/quanto/quantize.py", line 98, in quantize
    _quantize_submodule(model, name, m, weights=weights, activations=activations, optimizer=optimizer)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/optimum/quanto/quantize.py", line 45, in _quantize_submodule
    qmodule = quantize_module(module, weights=weights, activations=activations, optimizer=optimizer)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/optimum/quanto/nn/qmodule.py", line 86, in quantize_module
    return qcls.from_module(module, weights=weights, activations=activations, optimizer=optimizer)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/optimum/quanto/nn/qmodule.py", line 206, in from_module
    qmodule.weight.copy_(module.weight)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/optimum/quanto/tensor/qtensor.py", line 93, in __torch_function__
    return func(*args, **kwargs)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/py
```

**Comment by bghira** [comment]
hmmm.. it's working here... but i just realised i'm using a test version of PEFT. you can install:

```
pip install git+https://github.com/BenjaminBossan/peft@feat-support-optimum-quanto
```

**Comment by TheDuckingDuck** [comment]
Appears to have slightly changed the error on latest PR, with the PEFT version installed:
```
Traceback (most recent call last):
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/train.py", line 2804, in <module>
    main()
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/train.py", line 1609, in main
    quantoise(
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/helpers/training/quantisation/__init__.py", line 56, in quantoise
    _quanto_model(transformer, args.base_model_precision)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/helpers/training/quantisation/__init__.py", line 48, in _quanto_model
    quantize(model, weights=weight_quant)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/optimum/quanto/quantize.py", line 98, in quantize
    _quantize_submodule(model, name, m, weights=weights, activations=activations, optimizer=optimizer)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/optimum/quanto/quantize.py", line 45, in _quantize_submodule
    qmodule = quantize_module(module, weights=weights, activations=activations, optimizer=optimizer)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/optimum/quanto/nn/qmodule.py", line 86, in quantize_module
    return qcls.from_module(module, weights=weights, activations=activations, optimizer=optimizer)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/optimum/quanto/nn/qmodule.py", line 206, in from_module
    qmodule.weight.copy_(module.weight)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/optimum/quanto/tensor/qtensor.py", line 93, in __torch_function__
    return func(*args, **kwargs)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/optimum/quanto/tensor/qbytes.py", line 130, in __torch_dispatch__
    return qdispatch(*args, **kwargs)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/optimum/quanto/tensor/qbytes_ops.py", line 121, in copy_
    assert dest.qtype == src.qtype
AttributeError: 'Parameter' object has no attribute 'qtype'

```
This PR https://github.com/bghira/SimpleTuner/commit/596f7b4a6dbf3b62de96568b50a6d10ac97a6a8b is working, though I haven't tracked which specific PR after this breaks it.

**Comment by bghira** [comment]
are you resuming training? or it's a fresh run?

**Comment by bghira** [comment]
i believe i found the issue, a 2nd call to quanto that somehow doesn't error here

**Comment by TheDuckingDuck** [comment]
Does appear to start training without crashing now, thanks :)
