### ISSUE TITLE
Flux Lora training error when starting: TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [bghira/SimpleTuner#710]
I started a new training and getting an error immidetly: "TypeError: 'NoneType' object is not callable"
``` log
./train.sh
/workspace/SimpleTuner/.venv/lib/python3.11/site-packages/nvidia/nvjitlink/lib
2024-08-10 17:21:19,577 [WARNING] (ArgsParser) The VAE model madebyollin/sdxl-vae-fp16-fix is not compatible. Please use a compatible VAE to eliminate this warning. The baked-in VAE will be used, instead.
2024-08-10 17:21:19,578 [INFO] (ArgsParser) VAE Model: black-forest-labs/FLUX.1-dev
2024-08-10 17:21:19,578 [INFO] (ArgsParser) Default VAE Cache location: 
2024-08-10 17:21:19,578 [INFO] (ArgsParser) Text Cache location: cache
2024-08-10 17:21:19,578 [WARNING] (ArgsParser) -!- Flux supports a max length of 512 tokens, but you have supplied `--i_know_what_i_am_doing`, so this limit will not be enforced. -!-
2024-08-10 17:21:19,578 [WARNING] (ArgsParser) The model will begin to collapse after a short period of time, if the model you are continuing from has not been tuned beyond 256 tokens.
2024-08-10 17:21:19,578 [WARNING] (ArgsParser) Gradient accumulation steps are enabled, but gradient precision is set to 'unmodified'. This may lead to numeric instability. Consider setting --gradient_precision=fp32.
2024-08-10 17:21:19,612 [WARNING] (accelerate.utils.other) Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
2024-08-10 17:21:19,761 [INFO] (__main__) Logged into Hugging Face Hub as 'alexds9'
2024-08-10 17:21:19,761 [INFO] (__main__) Enabling tf32 precision boost for NVIDIA devices due to --allow_tf32.
2024-08-10 17:21:19,761 [INFO] (__main__) Load tokenizers
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
2024-08-10 17:21:20,121 [WARNING] (__main__) Could not load secondary tokenizer (OpenCLIP-G/14). Cannot continue: Cannot instantiate this tokenizer from a slow version. If it's based on sentencepiece, make sure you have sentencepiece installed.
2024-08-10 17:21:20,359 [INFO] (__main__) Loading OpenAI CLIP-L text encoder from black-forest-labs/FLUX.1-dev/text_encoder..
2024-08-10 17:21:20,851 [INFO] (__main__) Load VAE: black-forest-labs/FLUX.1-dev
2024-08-10 17:21:21,222 [INFO] (__main__) Moving text encoder to GPU.
2024-08-10 17:21:21,429 [INFO] (__main__) Loading VAE onto accelerator, converting from torch.float32 to torch.bfloat16
2024-08-10 17:21:21,528 [INFO] (DataBackendFactory) Loading data backend config from /workspace/multidatabackend.json
2024-08-10 17:21:21,529 [INFO] (DataBackendFactory) Configuring text embed backend: alt-embed-cache
Loading pipeline components...:   0%|                                                                                                                                             | 0/3 [00:00<?, ?it/s]Loaded scheduler as FlowMatchEulerDiscreteScheduler from `scheduler` subfolder of black-forest-labs/FLUX.1-dev.
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 342.04it/s]
2024-08-10 17:21:21,793 [INFO] (TextEmbeddingCache) (Rank: 0) (id=alt-embed-cache) Listing all text embed cache entries
2024-08-10 17:21:21,793 [INFO] (DataBackendFactory) Pre-computing null embedding
Write embeds to disk:   0%|                                                                            | 0/1 [00:00<?, ?it/s]2024-08-10 17:21:22,063 [ERROR] (__main__) 'NoneType' object is not callable, traceback: Traceback (most recent call last):
  File "/workspace/SimpleTuner/train.py", line 670, in main                                                                  
    configure_multi_databackend(
  File "/workspace/SimpleTuner/helpers/data_backend/factory.py", line 425, in configure_multi_databackend
    init_backend["text_embed_cache"].compute_embeddings_for_prompts(
  File "/workspace/SimpleTuner/helpers/caching/text_embeds.py", line 622, in compute_embeddings_for_prompts
    output = self.compute_embeddings_for_flux_prompts(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/SimpleTuner/helpers/caching/text_embeds.py", line 998, in compute_embeddings_for_flux_prompts
    self.encode_flux_prompt(
  File "/workspace/SimpleTuner/helpers/caching/text_embeds.py", line 273, in encode_flux_prompt
    prompt_embeds, pooled_prompt_embeds, time_ids = self.pipeline.encode_prompt(
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/pipelines/flux/pipeline_flux.py", line 349, in encode_prompt
    prompt_embeds = self._get_t5_prompt_embeds(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/pipelines/flux/pipeline_flux.py", line 215, in _get_t5_prompt_embeds
    text_inputs = self.tokenizer_2(
                  ^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

**Comment by bghira** [comment]
```
2024-08-10 17:21:20,121 [WARNING] (__main__) Could not load secondary tokenizer (OpenCLIP-G/14). Cannot continue: Cannot instantiate this tokenizer from a slow version. If it's based on sentencepiece, make sure you have sentencepiece installed.
```

```
pip install sentencepiece
```

**Comment by bghira** [comment]
seems like your dependencies might not have fully installed, i think sentencepiece should be pulled in automatically

**Comment by a-l-e-x-d-s-9** [comment]
Yes, sentencepiece installation fixed the error.
Thank you very much!
