### ISSUE TITLE
Bug: SD3 training unbound exception and float->bf16 error

### ISSUE THREAD

**Issue by Zanshinmu** [bghira/SimpleTuner#713]
I am attempting to do some SD3 LoRA training on a 192GB M2 Ultra.   Yes, I know what I'm getting into.  I've trained multiple SDXL checkpoints and LoRAs on this machine. 

Anyway, configured fine, but here's the first error:

```
cannot access local variable 'update_flux_schedule_to_fast' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/zanshin/SimpleTuner/train.py", line 2776, in <module>
    main()
  File "/Users/zanshin/SimpleTuner/train.py", line 496, in main
    update_flux_schedule_to_fast(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'update_flux_schedule_to_fast' where it is not associated with a value

```
I got it to work by adding an import here. train.py:271

great, all the pre-training stuff goes now

But then I get this error when the actual training starts:

```
Epoch 1/136 Steps:   0%|                                                                           | 0/30000 [00Epoch 1/136, Steps:   0%|                                                                          | 0/30000 [00:00<?, ?it/s]Input type (float) and bias type (c10::BFloat16) should be the same
Traceback (most recent call last):
  File "/Users/zanshin/SimpleTuner/train.py", line 2777, in <module>
    main()
  File "/Users/zanshin/SimpleTuner/train.py", line 2104, in main
    model_pred = transformer(
                 ^^^^^^^^^^^^
  File "/Users/zanshin/SimpleTuner/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zanshin/SimpleTuner/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zanshin/SimpleTuner/.venv/lib/python3.12/site-packages/diffusers/models/transformers/transformer_sd3.py", line 309, in forward
    hidden_states = self.pos_embed(hidden_states)  # takes care of adding positional embeddings too.
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zanshin/SimpleTuner/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zanshin/SimpleTuner/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zanshin/SimpleTuner/.venv/lib/python3.12/site-packages/diffusers/models/embeddings.py", line 219, in forward
    latent = self.proj(latent)
             ^^^^^^^^^^^^^^^^^
  File "/Users/zanshin/SimpleTuner/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zanshin/SimpleTuner/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zanshin/SimpleTuner/.venv/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zanshin/SimpleTuner/.venv/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Input type (float) and bias type (c10::BFloat16) should be the same

Epoch 1/136, Steps:   0%|                                                                          | 0/30000 [00:00<?, ?it/s]
```

guessing something didn't get initialized right.

**Comment by bghira** [comment]
can you share your config.env ?

**Comment by Zanshinmu** [comment]
Sure thing
[config_env.txt](https://github.com/user-attachments/files/16570937/config_env.txt)

Was just getting it working before I messed with the settings too much, they're mostly default.

**Comment by bghira** [comment]
please pull main to test https://github.com/bghira/SimpleTuner/commit/d876f415fec1cefd939192b3edc8a7212839a2e1

**Comment by Zanshinmu** [comment]
Sorry it took a while, had a job running on that machine that had to finish.

Looks good. No unbound exception, no other error.  Doing the warmup steps as I type this!
