### ISSUE TITLE
local variable 'model_max_seq_length' referenced before assignment Traceback (most recent call last)

### ISSUE THREAD

**Issue by xuyamu** [bghira/SimpleTuner#726]
(.venv) (base) xuyamu@SK-KCPTAMNMZKYU:~/SimpleTuner$ bash train.sh
/home/xuyamu/SimpleTuner/.venv/lib/python3.10/site-packages/nvidia/nvjitlink/lib
2024-08-12 00:50:45,636 [WARNING] (ArgsParser) The VAE model madebyollin/sdxl-vae-fp16-fix is not compatible. Please use a compatible VAE to eliminate this warning. The baked-in VAE will be used, instead.
2024-08-12 00:50:45,636 [INFO] (ArgsParser) VAE Model: /datasets/models/pipeline
2024-08-12 00:50:45,637 [INFO] (ArgsParser) Default VAE Cache location: 
2024-08-12 00:50:45,637 [INFO] (ArgsParser) Text Cache location: cache
2024-08-12 00:50:45,637 [INFO] (ArgsParser) Using flux timestep scheme.
local variable 'model_max_seq_length' referenced before assignment
Traceback (most recent call last):
  File "/home/xuyamu/SimpleTuner/train.py", line 2825, in <module>
    main()
  File "/home/xuyamu/SimpleTuner/train.py", line 276, in main
    args = parse_args()
  File "/home/xuyamu/SimpleTuner/helpers/arguments.py", line 2032, in parse_args
    f"Updating T5 XXL tokeniser max length to {model_max_seq_length} for Flux."
UnboundLocalError: local variable 'model_max_seq_length' referenced before assignment

——
What's going on?ヾ(;ﾟ;Д;ﾟ;)ﾉﾞ

In addition, due to firewall issues, I cannot download the model to my jupyter notebook through huggingface. I downloaded the model locally. I put it like this. Is it OK？
![01](https://github.com/user-attachments/assets/5612297c-c536-4a2c-ad59-2be3da02b5af)

Then I changed the relevant code in config.env to:

```
# Using a Huggingface Hub model:
# export MODEL_NAME="black-forest-labs/FLUX.1-dev"
# Using a local path to a huggingface hub model or saved checkpoint:
export MODEL_NAME="/datasets/models/pipeline"

```

**Comment by bghira** [comment]
well, right off the bat as i investigate i see that line 2032 doesn't exist in arguments.py anymore - can you pull the latest branch and see if the error persists?

**Comment by bghira** [comment]
it might have been missing commits on the release branch. since they have been deemed stable, i have merged them in.

**Comment by xuyamu** [comment]
> it might have been missing commits on the release branch. since they have been deemed stable, i have merged them in.

(.venv) (base) xuyamu@SK-KCPTAMNMZKYU:~/SimpleTuner$ bash train.sh
/home/xuyamu/SimpleTuner/.venv/lib/python3.10/site-packages/nvidia/nvjitlink/lib
2024-08-12 11:05:17,491 [WARNING] (ArgsParser) The VAE model madebyollin/sdxl-vae-fp16-fix is not compatible. Please use a compatible VAE to eliminate this warning. The baked-in VAE will be used, instead.
2024-08-12 11:05:17,491 [INFO] (ArgsParser) VAE Model: /datasets/models/pipeline
2024-08-12 11:05:17,492 [INFO] (ArgsParser) Default VAE Cache location: 
2024-08-12 11:05:17,492 [INFO] (ArgsParser) Text Cache location: cache
local variable 'model_max_seq_length' referenced before assignment
Traceback (most recent call last):
  File "/home/xuyamu/SimpleTuner/train.py", line 2825, in <module>
    main()
  File "/home/xuyamu/SimpleTuner/train.py", line 276, in main
    args = parse_args()
  File "/home/xuyamu/SimpleTuner/helpers/arguments.py", line 1983, in parse_args
    f"Updating T5 XXL tokeniser max length to {model_max_seq_length} for Flux."
UnboundLocalError: local variable 'model_max_seq_length' referenced before assignment

(.venv) (base) xuyamu@SK-KCPTAMNMZKYU:~/SimpleTuner$ 


-----------

Now the error comes to line 1983ヾ(;ﾟ;Д;ﾟ;)ﾉﾞ
Is the location of the model I downloaded manually correct? I did not download the models in the transformer folder because the models is too large. Is it necessary to download it?

**Comment by bghira** [comment]
```
    flux_version = "dev"
    if "schnell" in args.pretrained_model_name_or_path.lower():
        flux_version = "schnell"
        model_max_seq_length = 256
    elif "dev" in args.pretrained_model_name_or_path.lower():
        model_max_seq_length = 512

```

it's really stupid but there's no official way to determine the model sequence length other than the name of the model. put -dev at the end of the path.

**Comment by bghira** [comment]
or, pull and use the newer commit. but you will definitely need the 'transformer' directory handy.

**Comment by xuyamu** [comment]
> or, pull and use the newer commit. but you will definitely need the 'transformer' directory handy.
I re-downloaded arguments.py and put it into my notebook, and then there were even more bugs:

(.venv) (base) xuyamu@SK-KCPTAMNMZKYU:~/SimpleTuner$ bash train.sh
/home/xuyamu/SimpleTuner/.venv/lib/python3.10/site-packages/nvidia/nvjitlink/lib
2024-08-13 08:03:20,624 [WARNING] (ArgsParser) The VAE model madebyollin/sdxl-vae-fp16-fix is not compatible. Please use a compatible VAE to eliminate this warning. The baked-in VAE will be used, instead.
2024-08-13 08:03:20,624 [INFO] (ArgsParser) VAE Model: /datasets/models/pipeline
2024-08-13 08:03:20,624 [INFO] (ArgsParser) Default VAE Cache location: 
2024-08-13 08:03:20,624 [INFO] (ArgsParser) Text Cache location: cache
2024-08-13 08:03:20,625 [WARNING] (ArgsParser) Updating T5 XXL tokeniser max length to 512 for Flux.
2024-08-13 08:03:20,722 [ERROR] (__main__) Failed to log into Hugging Face Hub: Token is required (`token=True`), but no token found. You need to provide a token or be logged in to Hugging Face with `huggingface-cli login` or `huggingface_hub.login`. See https://huggingface.co/settings/tokens.
2024-08-13 08:03:20,722 [INFO] (__main__) Enabling tf32 precision boost for NVIDIA devices due to --allow_tf32.
2024-08-13 08:03:20,722 [INFO] (__main__) Load tokenizers
2024-08-13 08:03:20,723 [WARNING] (__main__) Primary tokenizer (CLIP-L/14) failed to load. Continuing to test whether we have just the secondary tokenizer..
Error: -> Incorrect path_or_model_id: '/datasets/models/pipeline'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
Traceback: Traceback (most recent call last):
  File "/home/xuyamu/SimpleTuner/.venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
  File "/home/xuyamu/SimpleTuner/.venv/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/xuyamu/SimpleTuner/.venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/xuyamu/SimpleTuner/.venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/datasets/models/pipeline'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xuyamu/SimpleTuner/train.py", line 190, in get_tokenizers
    tokenizer_1 = CLIPTokenizer.from_pretrained(**tokenizer_kwargs)
  File "/home/xuyamu/SimpleTuner/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2190, in from_pretrained
    resolved_config_file = cached_file(
  File "/home/xuyamu/SimpleTuner/.venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 466, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '/datasets/models/pipeline'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

2024-08-13 08:03:20,723 [WARNING] (__main__) Could not load secondary tokenizer (OpenCLIP-G/14). Cannot continue: Incorrect path_or_model_id: '/datasets/models/pipeline'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
Failed to load tokenizer
Traceback (most recent call last):
  File "/home/xuyamu/SimpleTuner/train.py", line 2825, in <module>
    main()
  File "/home/xuyamu/SimpleTuner/train.py", line 448, in main
    tokenizer_1, tokenizer_2, tokenizer_3 = get_tokenizers(args)
  File "/home/xuyamu/SimpleTuner/train.py", line 254, in get_tokenizers
    raise Exception("Failed to load tokenizer")
Exception: Failed to load tokenizer

----------------------------

ヾ(;ﾟ;Д;ﾟ;)ﾉﾞThe current models are placed in pipeline/FLUX.1-dev, but no matter whether the models are placed in the pipeline folder or pipeline/FLUX.1-dev, the above error will appear.

Models placement screenshot:
![20240813](https://github.com/user-attachments/assets/fdcac4da-ba87-49a4-974f-f7ff91edf6b7)

**Comment by bghira** [comment]
you probably need to use pipeline/FLUX.1-dev path then. fullllll path.
