### ISSUE TITLE
DeepSpeed: validations get stuck

### ISSUE THREAD

**Issue by tikhonlavrev** [bghira/SimpleTuner#759]
I have tried zero 2 and 3, but there is error.

Here the log:
```
2024-08-14 05:20:06,993 [INFO] (__main__) Unloading text encoders, as they are not being trained.
2024-08-14 05:20:09,033 [INFO] (__main__) After nuking text encoders from orbit, we freed 9.11 GB of VRAM. The real memories were the friends we trained a model on along the way.
Fetching 3 files: 100%|█████████████████████████| 3/3 [00:00<00:00, 4463.61it/s]
Fetching 3 files: 100%|█████████████████████████| 3/3 [00:00<00:00, 3486.54it/s]
'DummyOptim' object has no attribute 'param_groups'
Traceback (most recent call last):
  File "/media/bilikpintar/trainer/SimpleTuner/train.py", line 2420, in <module>
    main()
  File "/media/bilikpintar/trainer/SimpleTuner/train.py", line 970, in main
    lr_scheduler = get_lr_scheduler(
  File "/media/bilikpintar/trainer/SimpleTuner/helpers/training/custom_schedule.py", line 585, in get_lr_scheduler
    lr_scheduler = get_scheduler(
  File "/media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/optimization.py", line 335, in get_scheduler
    return schedule_func(optimizer, num_warmup_steps=num_warmup_steps, last_epoch=last_epoch)
  File "/media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/optimization.py", line 78, in get_constant_schedule_with_warmup
    return LambdaLR(optimizer, lr_lambda, last_epoch=last_epoch)
  File "/media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 320, in __init__
    self.lr_lambdas = [lr_lambda] * len(optimizer.param_groups)
AttributeError: 'DummyOptim' object has no attribute 'param_groups'

2024-08-14 05:20:10,950 [INFO] (__main__) Collected the following data backends: ['alt-embed-cache', 'SomniumFLUX']
2024-08-14 05:20:10,951 [INFO] (__main__) Calculated our maximum training steps at 1646760 because we have 40 epochs and 41169 steps per epoch.
2024-08-14 05:20:10,951 [INFO] (__main__) Loading constant_with_warmup learning rate scheduler with 1000 warmup steps
2024-08-14 05:20:10,954 [INFO] (__main__) Learning rate: 1e-05
2024-08-14 05:20:10,954 [INFO] (__main__) Using DeepSpeed optimizer.
2024-08-14 05:20:10,956 [INFO] (__main__) Loading constant_with_warmup learning rate scheduler with 1000 warmup steps
2024-08-14 05:20:10,956 [INFO] (__main__) Using generic 'constant_with_warmup' learning rate scheduler.
'DummyOptim' object has no attribute 'param_groups'
Traceback (most recent call last):
  File "/media/bilikpintar/trainer/SimpleTuner/train.py", line 2420, in <module>
    main()
  File "/media/bilikpintar/trainer/SimpleTuner/train.py", line 970, in main
    lr_scheduler = get_lr_scheduler(
  File "/media/bilikpintar/trainer/SimpleTuner/helpers/training/custom_schedule.py", line 585, in get_lr_scheduler
    lr_scheduler = get_scheduler(
  File "/media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/optimization.py", line 335, in get_scheduler
    return schedule_func(optimizer, num_warmup_steps=num_warmup_steps, last_epoch=last_epoch)
  File "/media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/optimization.py", line 78, in get_constant_schedule_with_warmup
    return LambdaLR(optimizer, lr_lambda, last_epoch=last_epoch)
  File "/media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 320, in __init__
    self.lr_lambdas = [lr_lambda] * len(optimizer.param_groups)
AttributeError: 'DummyOptim' object has no attribute 'param_groups'
```

I also tried various optimizer (adamw and adamw_bf16) and scheduler, but it always failed. My GPU is 2x80GB A100.

Here is my config.env:
```
# Configure these values.

# 'lora' or 'full'
# lora - train a small network for a character or style, or both. quite versatile.
# full - requires lots of vram, trains very slowly, needs a lot of data and concepts.
export MODEL_TYPE='full'

# SDXL is trained by default, but you will need to enable one of these options for anything else.

# Set this to 'true' if you are training a Stable Diffusion 3 checkpoint.
# Use MODEL_NAME="stabilityai/stable-diffusion-3-medium-diffusers"
export STABLE_DIFFUSION_3=false
# Similarly, this is to train PixArt Sigma (1K or 2K) models.
# Use MODEL_NAME="PixArt-alpha/PixArt-Sigma-XL-2-1024-MS"
export PIXART_SIGMA=false
# For old Stable Diffusion 1.x/2.x models, you'll enable this.
# Use MODEL_NAME="stabilityai/stable-diffusion-2-1"
export STABLE_DIFFUSION_LEGACY=false
# For Kwai-Kolors, enable KOLORS.
# Use MODEL_NAME="kwai-kolors/kolors-diffusers"
export KOLORS=false
# For Flux, if you have 8 GPUs and DeepSpeed configured.
# Use MODEL_NAME="black-forest-labs/FLUX.1-dev"
export FLUX=true

# ControlNet model training is only supported when MODEL_TYPE='full'
# See this document for more information: https://github.com/bghira/SimpleTuner/blob/main/documentation/CONTROLNET.md
# DeepFloyd, PixArt, and SD3 do not currently support ControlNet model training.
export CONTROLNET=false

# DoRA enhances the training style of LoRA, but it will run more slowly at the same rank.
# See: https://arxiv.org/abs/2402.09353
# See: https://github.com/huggingface/peft/pull/1474
export USE_DORA=false

# BitFit freeze strategy for the u-net causes everything but the biases to be frozen.
# This may help retain the full model's underlying capabilities. LoRA is currently not tested/known to work.
#if [[ "$MODEL_TYPE" == "full" ]]; then
#    # When training a full model, we will rely on BitFit to keep the u-net intact.
#    export USE_BITFIT=true
#elif [[ "$MODEL_TYPE" == "lora" ]]; then
#    # LoRA can not use BitFit.
#    export USE_BITFIT=false
#elif [[ "$MODEL_TYPE" == "deepfloyd-full" ]]; then
#    export USE_BITFIT=true
#fi

# Restart where we left off. Change this to "checkpoint-1234" to start from a specific checkpoint.
export RESUME_CHECKPOINT="latest"

# How often to checkpoint. Depending on your learning rate, you may wish to change this.
# For the default settings with 10 gradient accumulations, more frequent checkpoints might be preferable at first.
export CHECKPOINTING_STEPS=2500
# This is how many checkpoints we will keep. Two is safe, but three is safer.
export CHECKPOINTING_LIMIT=2

# This is decided as a relatively conservative 'constant' learning rate.
# Adjust higher or lower depending on how burnt your model becomes.
export LEARNING_RATE=1e-5 #@param {type:"number"}

# Using a Huggingface Hub model:
export MODEL_NAME="black-forest-labs/FLUX.1-dev"
# Using a local path to a huggingface hub model or saved checkpoint:
#export MODEL_NAME="/datasets/models/pipeline"

# Make DEBUG_EXTRA_ARGS empty to disable wandb.
export DEBUG_EXTRA_ARGS="--report_to=wandb"
export TRACKER_PROJECT_NAME="${MODEL_TYPE}-training"
export TRACKER_RUN_NAME="simpletuner-sdxl"

# Max number of steps OR epochs can be used. Not both.
export MAX_NUM_STEPS=0
# Will likely overtrain, but that's fine.
export NUM_EPOCHS=40

# A convenient prefix for all of your training paths.
# These may be absolute or relative paths. Here, we are using relative paths.
# The output will just be in a folder called "output/models" by default.
export DATALOADER_CONFIG="config/multidatabackend.json"
export OUTPUT_DIR="output/models"

# Set this to "true" to push your model to Hugging Face Hub.
export PUSH_TO_HUB="false"
# If PUSH_TO_HUB and PUSH_CHECKPOINTS are both enabled, every saved checkpoint will be pushed to Hugging Face Hub.
export PUSH_CHECKPOINTS="true"
# This will be the model name for your final hub upload, eg. "yourusername/yourmodelname"
# It defaults to the wandb project name, but you can override this here.
export HUB_MODEL_NAME=$TRACKER_PROJECT_NAME

# By default, images will be resized so their SMALLER EDGE is 1024 pixels, maintaining aspect ratio.
# Setting this value to 768px might result in more reasonable training data sizes for SDXL.
export RESOLUTION=1024
# If you want to have the training data resized by pixel area (Megapixels) rather than edge length,
#  set this value to "area" instead of "pixel", and uncomment the next RESOLUTION declaration.
export RESOLUTION_TYPE="pixel"
#export RESOLUTION=1          # 1.0 Megapixel training sizes
# If RESOLUTION_TYPE="pixel", the minimum resolution specifies the smaller edge length, measured in pixels. Recommended: 1024.
# If RESOLUTION_TYPE="area", the minimum resolution specifies the total image area, measured in megapixels. Recommended: 1.
export MINIMUM_RESOLUTION=$RESOLUTION

# How many decimals to round aspect buckets to.
#export ASPECT_BUCKET_ROUNDING=2

# Use this to append an instance prompt to each caption, used for adding trigger words.
# This has not been tested in SDXL.
#export INSTANCE_PROMPT="lotr style "
# If you also supply a user prompt library or `--use_prompt_library`, this will be added to those lists.
export VALIDATION_PROMPT="Nahida (genshin impact), A young giel is standing while holding a sword"
export VALIDATION_GUIDANCE=7.5
# You'll want to set this to 0.7 if you are training a terminal SNR model.
export VALIDATION_GUIDANCE_RESCALE=0.0
# How frequently we will save and run a pipeline for validations.
export VALIDATION_STEPS=100
export VALIDATION_NUM_INFERENCE_STEPS=30
export VALIDATION_NEGATIVE_PROMPT="blurry, cropped, ugly"
export VALIDATION_SEED=42
export VALIDATION_RESOLUTION=$RESOLUTION


# Adjust this for your GPU memory size. This, and resolution, are the biggest VRAM killers.
export TRAIN_BATCH_SIZE=1
# Accumulate your update gradient over many steps, to save VRAM while still having higher effective batch size:
# effective batch size = ($TRAIN_BATCH_SIZE * $GRADIENT_ACCUMULATION_STEPS).
export GRADIENT_ACCUMULATION_STEPS=4
# How many images to encode at once with the VAE. Can increase VRAM use.
export VAE_BATCH_SIZE=2

# Use any standard scheduler type. constant, polynomial, constant_with_warmup
export LR_SCHEDULE="constant_with_warmup"
# A warmup period allows the model and the EMA weights more importantly to familiarise itself with the current quanta.
# For the cosine or sine type schedules, the warmup period defines the interval between peaks or valleys.
# Use a sine schedule to simulate a warmup period, or a Cosine period to simulate a polynomial start.
#export LR_WARMUP_STEPS=$((MAX_NUM_STEPS / 10))
export LR_WARMUP_STEPS=1000

# Caption dropout probability. Set to 0.1 for 10% of captions dropped out. Set to 0 to disable.
# You may wish to disable dropout if you want to limit your changes strictly to the prompts you show the model.
# You may wish to increase the rate of dropout if you want to more broadly adopt your changes across the model.
export CAPTION_DROPOUT_PROBABILITY=0.1

export METADATA_UPDATE_INTERVAL=65

# How many workers to use for VAE caching.
export MAX_WORKERS=32
# Read and write batch sizes for VAE caching.
export READ_BATCH_SIZE=25
export WRITE_BATCH_SIZE=64
# How many images to process at once (resize, crop, transform) during VAE caching.
export IMAGE_PROCESSING_BATCH_SIZE=32
# When using large batch sizes, you'll need to increase the pool connection limit.
export AWS_MAX_POOL_CONNECTIONS=128
# For very large systems, setting this can reduce CPU overhead of torch spawning an unnecessarily large number of threads.
export TORCH_NUM_THREADS=8

# If this is set, any images that fail to open will be DELETED to avoid re-checking them every time.
export DELETE_ERRORED_IMAGES=0
# If this is set, any images that are too small for the minimum resolution size will be DELETED.
export DELETE_SMALL_IMAGES=0

# Bytedance recommends these be set to "trailing" so that inference and training behave in a more congruent manner.
# To follow the original SDXL training strategy, use "leading" instead, though results are generally worse.
export TRAINING_SCHEDULER_TIMESTEP_SPACING="trailing"
export INFERENCE_SCHEDULER_TIMESTEP_SPACING="trailing"

# Removing this option or unsetting it uses vanilla training. Setting it reweights the loss by the position of the timestep in the noise schedule.
# A value "5" is recommended by the researchers. A value of "20" is the least impact, and "1" is the most impact.
export MIN_SNR_GAMMA=5

# Set this to an explicit value of "false" to disable Xformers. Probably required for AMD users.
export USE_XFORMERS=false

# There's basically no reason to unset this. However, to disable it, use an explicit value of "false".
# This will save a lot of memory consumption when enabled.
export USE_GRADIENT_CHECKPOINTING=true

##
# Options below here may require a bit more complicated configuration, so they are not simple variables.
##

# TF32 is great on Ampere or Ada, not sure about earlier generations.
export ALLOW_TF32=true

# AdamW 8Bit is a robust and lightweight choice. Adafactor might reduce memory consumption, and Dadaptation is slow and experimental.
# AdamW is the default optimizer, but it uses a lot of memory and is slower than AdamW8Bit or Adafactor.
# NOTE: When training a quantised base model, you can't use adamw_bf16. Instead, try adafactor or adamw.
# Choices: adamw, adamw8bit, adafactor, dadaptation, adamw_bf16
export OPTIMIZER="adamw"


# EMA is a strong regularisation method that uses a lot of extra VRAM to hold two copies of the weights.
# This is worthwhile on large training runs, but not so much for smaller training runs.
# NOTE: EMA is not currently applied to LoRA.
export USE_EMA=false
export EMA_DECAY=0.999

export TRAINER_EXTRA_ARGS=""
## For offset noise training:
# Not recommended for terminal SNR models.
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --offset_noise --noise_offset=0.02"

## For terminal SNR training:
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --prediction_type=v_prediction --rescale_betas_zero_snr"
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --training_scheduler_timestep_spacing=trailing --inference_scheduler_timestep_spacing=trailing"
## You may benefit from directing training toward a specific weighted subset of timesteps.
# In this example, we train the final 25% of the timestep schedule with a 3x bias.
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --timestep_bias_strategy=later --timestep_bias_portion=0.25 --timestep_bias_multiplier=3"
# In this example, we train the earliest 25% of the timestep schedule with a 5x bias.
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --timestep_bias_strategy=earlier --timestep_bias_portion=0.25 --timestep_bias_multiplier=5"
# Here, we designate that specifically, timesteps 200 to 500 should be prioritised.
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --timestep_bias_strategy=range --timestep_bias_begin=200 --timestep_bias_end=500 --timestep_bias_multiplier=3"

## For experimental min-SNR weighted loss training (5 is suggested value by the original researchers):
# Not recommended for terminal SNR models.
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --snr_gamma=5.0"

# For Wasabi S3 filesystem backend (experimental)
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --data_backend=aws --aws_bucket_name=test123"
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --aws_endpoint_url=https://s3.wasabisys.com"
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --aws_access_key=1234567890"
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --aws_secret_access_key=0987654321"


# Reproducible training. Set to -1 to disable.
export TRAINING_SEED=42

# Mixed precision is the best. You honestly might need to YOLO it in fp16 mode for Google Colab type setups.
export MIXED_PRECISION="bf16"                # Might not be supported on all GPUs. fp32 will be needed for others.
export PURE_BF16=false

# This has to be changed if you're training with multiple GPUs.
export TRAINING_NUM_PROCESSES=2
export TRAINING_NUM_MACHINES=1
export ACCELERATE_EXTRA_ARGS=""                          # --multi_gpu or other similar flags for huggingface accelerate

# With Pytorch 2.1, you might have pretty good luck here.
# If you're using aspect bucketing however, each resolution change will recompile. Seriously, just don't do it.
# Well, then again... Pytorch 2.2 has support for dynamic shapes. Why not?
export TRAINING_DYNAMO_BACKEND='no'                # or 'no' if you want to disable torch compile in case of performance issues or lack of support (eg. AMD)

export TOKENIZERS_PARALLELISM=false
export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --i_know_what_i_am_doing"
```

**Comment by bghira** [comment]
it seems some code may be missing that used to be there for DummyScheduler use:

```
        logger.info(f"Using DeepSpeed learning rate scheduler")
        lr_scheduler = accelerate.utils.DummyScheduler(
            optimizer,
            total_num_steps=args.max_train_steps,
            warmup_num_steps=args.lr_warmup_steps,
        )
```

based on `use_deepspeed_scheduler`

**Comment by bghira** [comment]
can do thank you for testing it

**Comment by tikhonlavrev** [comment]
Okay I'm back. After the train progress at the validation phase, I got this error:

```
Keyword arguments {'safety_checker': None} are not expected by FluxPipeline and will be ignored.
                                                                                                                  Loaded scheduler as FlowMatchEulerDiscreteScheduler from `scheduler` subfolder of black-forest-labs/FLUX.1-dev.it/s]
Loaded tokenizer_2 as T5TokenizerFast from `tokenizer_2` subfolder of black-forest-labs/FLUX.1-dev.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.44it/s]
Loaded text_encoder_2 as T5EncoderModel from `text_encoder_2` subfolder of black-forest-labs/FLUX.1-dev. 16.43it/s]
Loading pipeline components...: 100%|████████████████████████████████████████████████| 6/6 [00:01<00:00,  5.66it/s]
no schedulerline components...: 100%|████████████████████████████████████████████████| 6/6 [00:01<00:00,  5.08it/s]
                                                                                                                  [rank1]:[E814 13:15:53.273041837 ProcessGroupNCCL.cpp:607] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=357826, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=5400000) ran for 5400054 milliseconds before timing out.
[rank1]:[E814 13:15:53.273231131 ProcessGroupNCCL.cpp:1664] [PG 0 (default_pg) Rank 1] Exception (either an error or timeout) detected by watchdog at work: 357826, last enqueued NCCL work: 357826, last completed NCCL work: 357825.
[rank1]:[E814 13:15:53.467738431 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 1] Timeout at NCCL work: 357826, last enqueued NCCL work: 357826, last completed NCCL work: 357825.
[rank1]:[E814 13:15:53.467770070 ProcessGroupNCCL.cpp:621] [Rank 1] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank1]:[E814 13:15:53.467778105 ProcessGroupNCCL.cpp:627] [Rank 1] To avoid data inconsistency, we are taking the entire process down.
[rank1]:[E814 13:15:53.469096103 ProcessGroupNCCL.cpp:1515] [PG 0 (default_pg) Rank 1] Process group watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=357826, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=5400000) ran for 5400054 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:609 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x728a77777f86 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x728a2998ff42 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x728a29996983 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x728a29998d6c in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdc253 (0x728a76cdc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x728a78c94ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x126850 (0x728a78d26850 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG 0 (default_pg) Rank 1] Process group watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=357826, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=5400000) ran for 5400054 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:609 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x728a77777f86 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x728a2998ff42 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x728a29996983 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x728a29998d6c in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdc253 (0x728a76cdc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x728a78c94ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x126850 (0x728a78d26850 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1521 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x728a77777f86 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe1a5e4 (0x728a2961a5e4 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xdc253 (0x728a76cdc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #3: <unknown function> + 0x94ac3 (0x728a78c94ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x126850 (0x728a78d26850 in /lib/x86_64-linux-gnu/libc.so.6)

[rank0]:[E814 13:15:55.540449524 ProcessGroupNCCL.cpp:607] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=357826, OpType=_ALLGATHER_BASE, NumelIn=50823168, NumelOut=101646336, Timeout(ms)=5400000) ran for 5400036 milliseconds before timing out.
[rank0]:[E814 13:15:55.540611818 ProcessGroupNCCL.cpp:1664] [PG 0 (default_pg) Rank 0] Exception (either an error or timeout) detected by watchdog at work: 357826, last enqueued NCCL work: 357826, last completed NCCL work: 357825.
[rank0]:[E814 13:15:56.147769383 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 0] Timeout at NCCL work: 357826, last enqueued NCCL work: 357826, last completed NCCL work: 357825.
[rank0]:[E814 13:15:56.147788118 ProcessGroupNCCL.cpp:621] [Rank 0] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank0]:[E814 13:15:56.147793358 ProcessGroupNCCL.cpp:627] [Rank 0] To avoid data inconsistency, we are taking the entire process down.
[rank0]:[E814 13:15:56.148874252 ProcessGroupNCCL.cpp:1515] [PG 0 (default_pg) Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=357826, OpType=_ALLGATHER_BASE, NumelIn=50823168, NumelOut=101646336, Timeout(ms)=5400000) ran for 5400036 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:609 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x781563577f86 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x78151578ff42 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x781515796983 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x781515798d6c in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdc253 (0x781562adc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x781564a94ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x126850 (0x781564b26850 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG 0 (default_pg) Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=357826, OpType=_ALLGATHER_BASE, NumelIn=50823168, NumelOut=101646336, Timeout(ms)=5400000) ran for 5400036 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:609 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x781563577f86 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x78151578ff42 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x781515796983 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x781515798d6c in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdc253 (0x781562adc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x781564a94ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x126850 (0x781564b26850 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1521 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x781563577f86 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe1a5e4 (0x78151541a5e4 in /media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xdc253 (0x781562adc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #3: <unknown function> + 0x94ac3 (0x781564a94ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x126850 (0x781564b26850 in /lib/x86_64-linux-gnu/libc.so.6)

W0814 13:16:02.511000 130773158887424 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 540117 closing signal SIGTERM
E0814 13:16:06.686000 130773158887424 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -6) local_rank: 1 (pid: 540118) of binary: /media/bilikpintar/trainer/SimpleTuner/.venv/bin/python
Traceback (most recent call last):
  File "/media/bilikpintar/trainer/SimpleTuner/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1091, in launch_command
    deepspeed_launcher(args)
  File "/media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 787, in deepspeed_launcher
    distrib_run.run(args)
  File "/media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/media/bilikpintar/trainer/SimpleTuner/.venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
train.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-14_13:16:02
  host      : fluxtraining.internal.cloudapp.net
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 540118)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 540118
=======================================================
```

**Comment by bghira** [comment]
oh man. any idea how long it waited before kicking out the NCCL error? did it just get stuck?

**Comment by tikhonlavrev** [comment]
I'm sorry I leave my machine, so I can't sure how long does it take. I can approximate between 30 minutes-1 hours, this is the interval when I leave my machine

**Comment by bghira** [comment]
it's 5400054ms or 90 minutes :[ you can try and reduce validation step count to 1 and see when it is getting stuck. but it seems like deepspeed validations might just need to be disabled for now until i can access a machine and test this

**Comment by bghira** [comment]
ok. this is actually resolved in 1380f11 i believe. i spun up a 2x A100-80G SXM4 box and configured ZeRO3 with CPU offload, ran validation steps pretty low.

**Comment by heart-du** [comment]
I am using x-flux for training, but it can not enable zero3. Is there any place to be changed in the code.

**Comment by bghira** [comment]
_points to the x-flux github page_
