### ISSUE TITLE
Kolors tensor size error at start of training

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#790]
Epoch 1/132, Steps:   0%|                                                                          | 0/20000 [00:00<?, ?it/s]Given groups=1, weight of size [320, 4, 3, 3], expected input[5, 16, 56, 80] to have 4 channels, but got 16 channels instead
Traceback (most recent call last):
  File "/root/autodl-tmp/SimpleTuner/train.py", line 2315, in <module>
    main()
  File "/root/autodl-tmp/SimpleTuner/train.py", line 1721, in main
    model_pred = unet(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/utils/operations.py", line 819, in forward
    return model_forward(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/utils/operations.py", line 807, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 43, in decorate_autocast
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1169, in forward
    sample = self.conv_in(sample)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[5, 16, 56, 80] to have 4 channels, but got 16 channels instead

**Comment by zhuliyi0** [comment]
I am on latest release branch

**Comment by zhuliyi0** [comment]
nevermind, deleting dataset cache fixed it.

**Comment by bghira** [comment]
the internal calculations and batching changed mildly
