### ISSUE TITLE
AttributeError: 'DummyOptim' object has no attribute 'param_groups'

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#796]
#759 similar but different. I got the same error right before training start. If I diable accelerate I can get to start of training then OOM. There were some warnings about accelerate kernel version is low.

In terms of necessity of flux finetuning, I think it might still be necessary for some small dataset that is not easily learned by lora. I have this dataset of couple hundreds images that sdxl full finetune learns super fast but flux lora fails. I tried sdxl lora before, though not with simpletuner, and sdxl lora fails too.

the error:

2024-08-18 11:54:27,110 [INFO] (__main__) Loading constant_with_warmup learning rate scheduler with 100 warmup steps
2024-08-18 11:54:27,114 [INFO] (__main__) Learning rate: 1e-05
2024-08-18 11:54:27,114 [INFO] (__main__) Using DeepSpeed optimizer (AdamW).
2024-08-18 11:54:27,114 [INFO] (__main__) Using DeepSpeed scheduler (WarmupLR).
2024-08-18 11:54:27,117 [INFO] (__main__) Loading constant_with_warmup learning rate scheduler with 100 warmup steps
2024-08-18 11:54:27,117 [INFO] (__main__) Using generic 'constant_with_warmup' learning rate scheduler.
'DummyOptim' object has no attribute 'param_groups'
Traceback (most recent call last):
  File "/root/autodl-tmp/SimpleTuner/train.py", line 2315, in <module>
    main()
  File "/root/autodl-tmp/SimpleTuner/train.py", line 837, in main
    lr_scheduler = get_lr_scheduler(
  File "/root/autodl-tmp/SimpleTuner/helpers/training/custom_schedule.py", line 585, in get_lr_scheduler
    lr_scheduler = get_scheduler(
  File "/root/miniconda3/lib/python3.10/site-packages/diffusers/optimization.py", line 335, in get_scheduler
    return schedule_func(optimizer, num_warmup_steps=num_warmup_steps, last_epoch=last_epoch)
  File "/root/miniconda3/lib/python3.10/site-packages/diffusers/optimization.py", line 78, in get_constant_schedule_with_warmup
    return LambdaLR(optimizer, lr_lambda, last_epoch=last_epoch)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 320, in __init__
    self.lr_lambdas = [lr_lambda] * len(optimizer.param_groups)
AttributeError: 'DummyOptim' object has no attribute 'param_groups'

**Comment by bghira** [comment]
we're still experimenting with new lora training strategies - for example lycoris is now added and lokr can be used to approximate full-rank finetuning. you can additionally use `--flux_lora_target=context+ffs` and have an equivalent to CLIP training. do some number of steps on this LoRA and then restart training fresh using `--init_lora=` pointing to that `context+ffs` lora and then, `--flux_lora_target=all+ffs`.

it will complain that the lora you are continuing doesn't have the target keys for all+ffs, but it will add them. and then you can see the benefit of starting training with the text layers already knowing your concept. it is very powerful. please test that while i look into this.

**Comment by bghira** [comment]
i've pushed a possible fix for this, but you'll have to note #759

**Comment by zhuliyi0** [comment]
> we're still experimenting with new lora training strategies - for example lycoris is now added and lokr can be used to approximate full-rank finetuning. you can additionally use `--flux_lora_target=context+ffs` and have an equivalent to CLIP training. do some number of steps on this LoRA and then restart training fresh using `--init_lora=` pointing to that `context+ffs` lora and then, `--flux_lora_target=all+ffs`.
> 
> it will complain that the lora you are continuing doesn't have the target keys for all+ffs, but it will add them. and then you can see the benefit of starting training with the text layers already knowing your concept. it is very powerful. please test that while i look into this.

Thanks for the info. I will give other types of lora a try. 

> i've pushed a possible fix for this, but you'll have to note https://github.com/bghira/SimpleTuner/issues/759 is about validations getting stuck, and should be disabled

Yes it got pass that error, but another one popped up:

2024-08-18 14:45:47,707 [INFO] (__main__) Loading constant_with_warmup learning rate scheduler with 100 warmup steps
2024-08-18 14:45:47,711 [INFO] (__main__) Learning rate: 1e-05
2024-08-18 14:45:47,711 [INFO] (__main__) Using DeepSpeed optimizer (AdamW).
2024-08-18 14:45:47,711 [INFO] (__main__) Using DeepSpeed scheduler (WarmupLR).
local variable 'default_settings' referenced before assignment
Traceback (most recent call last):
  File "/root/autodl-tmp/SimpleTuner/train.py", line 2454, in <module>
    main()
  File "/root/autodl-tmp/SimpleTuner/train.py", line 899, in main
    optimizer_args_from_config, optimizer_class = determine_optimizer_class_with_config(
  File "/root/autodl-tmp/SimpleTuner/helpers/training/optimizer_param.py", line 262, in determine_optimizer_class_with_config
    return default_settings, optimizer_class
UnboundLocalError: local variable 'default_settings' referenced before assignment

**Comment by bghira** [comment]
pushed a fix for this too

**Comment by zhuliyi0** [comment]
that error is gone. And I had to upgrade cuda from 11.8 to 12.1 to continue, until, the next error:

[2024-08-18 15:28:16,014] [INFO] [utils.py:781:see_memory_usage] DeepSpeedZeRoOffload initialize [end]
[2024-08-18 15:28:16,015] [INFO] [utils.py:782:see_memory_usage] MA 0.18 GB         Max_MA 22.35 GB         CA 22.37 GB         Max_CA 22 GB 
[2024-08-18 15:28:16,015] [INFO] [utils.py:789:see_memory_usage] CPU Virtual Memory:  used = 183.04 GB, percent = 18.2%
[2024-08-18 15:28:16,188] [INFO] [utils.py:781:see_memory_usage] Before creating fp16 partitions
[2024-08-18 15:28:16,189] [INFO] [utils.py:782:see_memory_usage] MA 0.18 GB         Max_MA 0.18 GB         CA 22.37 GB         Max_CA 22 GB 
[2024-08-18 15:28:16,189] [INFO] [utils.py:789:see_memory_usage] CPU Virtual Memory:  used = 182.51 GB, percent = 18.1%
[2024-08-18 15:28:36,495] [INFO] [utils.py:781:see_memory_usage] After creating fp16 partitions: 12
[2024-08-18 15:28:36,495] [INFO] [utils.py:782:see_memory_usage] MA 0.18 GB         Max_MA 0.18 GB         CA 22.37 GB         Max_CA 22 GB 
[2024-08-18 15:28:36,495] [INFO] [utils.py:789:see_memory_usage] CPU Virtual Memory:  used = 193.09 GB, percent = 19.2%
[2024-08-18 15:28:36,675] [INFO] [utils.py:781:see_memory_usage] Before creating fp32 partitions
[2024-08-18 15:28:36,676] [INFO] [utils.py:782:see_memory_usage] MA 0.18 GB         Max_MA 0.18 GB         CA 22.37 GB         Max_CA 22 GB 
[2024-08-18 15:28:36,676] [INFO] [utils.py:789:see_memory_usage] CPU Virtual Memory:  used = 193.22 GB, percent = 19.2%
[2024-08-18 15:29:04,343] [INFO] [utils.py:781:see_memory_usage] After creating fp32 partitions
[2024-08-18 15:29:04,344] [INFO] [utils.py:782:see_memory_usage] MA 0.18 GB         Max_MA 0.18 GB         CA 22.37 GB         Max_CA 22 GB 
[2024-08-18 15:29:04,344] [INFO] [utils.py:789:see_memory_usage] CPU Virtual Memory:  used = 233.33 GB, percent = 23.2%
[2024-08-18 15:29:04,511] [INFO] [utils.py:781:see_memory_usage] Before initializing optimizer states
[2024-08-18 15:29:04,512] [INFO] [utils.py:782:see_memory_usage] MA 0.18 GB         Max_MA 0.18 GB         CA 22.37 GB         Max_CA 22 GB 
[2024-08-18 15:29:04,512] [INFO] [utils.py:789:see_memory_usage] CPU Virtual Memory:  used = 232.95 GB, percent = 23.1%
E0818 15:29:23.080000 140353168590656 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -9) local_rank: 0 (pid: 1549) of binary: /root/miniconda3/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1091, in launch_command
    deepspeed_launcher(args)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 787, in deepspeed_launcher
    distrib_run.run(args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
/root/autodl-tmp/SimpleTuner/train.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-18_15:29:23
  host      : autodl-container-c75a498ab8-1d4254ba
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 1549)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 1549
=====================================================

I set deepspeed to stage 3, set both offload to cpu, and bf16, other settings are default.

**Comment by bghira** [comment]
oof. that is too much memory requested. you might want to try nvme offload for 3.

**Comment by zhuliyi0** [comment]
changed accelerate setting to only offload optimizer state, and it is running, although, it takes 20+ sec per step. So it is true that Flux wants to be trained on multiple GPUs..

I am trying nvme off-loading. I set offload path by accelerate config, and double checked yaml file, but still got the following error:

> DeepSpeed is using nvme but nvme_path is not specified.
> Traceback (most recent call last):
>   File "/root/autodl-tmp/SimpleTuner/train.py", line 2454, in <module>
>     main()
>   File "/root/autodl-tmp/SimpleTuner/train.py", line 862, in main
>     raise ValueError(
> ValueError: DeepSpeed is using nvme but nvme_path is not specified.

I tried adding these offset pathes after accelerate launch, still same error.

config yaml looks like this:

> compute_environment: LOCAL_MACHINE
> debug: false
> deepspeed_config:
>   gradient_accumulation_steps: 1
>   offload_optimizer_device: nvme
>   offload_optimizer_nvme_path: /root/autodl-tmp/nvme_offload
>   offload_param_device: nvme
>   offload_param_nvme_path: /root/autodl-tmp/nvme_offload
>   zero3_init_flag: false
>   zero_stage: 2
> distributed_type: DEEPSPEED
> downcast_bf16: 'no'
> enable_cpu_affinity: false
> machine_rank: 0
> main_training_function: main
> mixed_precision: bf16
> num_machines: 1
> num_processes: 1
> rdzv_backend: static
> same_network: true
> tpu_env: []
> tpu_use_cluster: false
> tpu_use_sudo: false
> use_cpu: false

**Comment by bghira** [comment]
yep.. even the next best thing is in kohya's trainer now, but it doesn't support multiple GPUs:

https://github.com/kohya-ss/sd-scripts/pull/1374/commits/ef535ec6bb99918027afc1e31efa72cd3761d453#diff-53ce178cab63cb26a2ef726379c796d907efe65a4e05c1552085a966a3f83fca

**Comment by bghira** [comment]
it is `--offload_param_path`

**Comment by zhuliyi0** [comment]
Thanks it is working now.

**Comment by zhuliyi0** [comment]
this fix might have caused another error, since release branch does not have it:

> 2024-08-18 21:41:03,655 [INFO] (__main__) Loading constant_with_warmup learning rate scheduler with 100 warmup steps
> 2024-08-18 21:41:03,661 [INFO] (__main__) Learning rate: 1e-05
> Optimizer None not found.
> Traceback (most recent call last):
>   File "/root/autodl-tmp/SimpleTuner/train.py", line 2454, in <module>
>     main()
>   File "/root/autodl-tmp/SimpleTuner/train.py", line 899, in main
>     optimizer_args_from_config, optimizer_class = determine_optimizer_class_with_config(
>   File "/root/autodl-tmp/SimpleTuner/helpers/training/optimizer_param.py", line 261, in determine_optimizer_class_with_config
>     optimizer_class, optimizer_details = optimizer_parameters(args.optimizer, args)
>   File "/root/autodl-tmp/SimpleTuner/helpers/training/optimizer_param.py", line 206, in optimizer_parameters
>     raise ValueError(f"Optimizer {optimizer} not found.")
> ValueError: Optimizer None not found.

I was finetuning Kolors.

**Comment by zhuliyi0** [comment]
No I was wrong, not related. Something between release and this fix caused this error.

**Comment by bghira** [comment]
made --optimizer mandatory
