### ISSUE TITLE
sample population smaller than requested slice

### ISSUE THREAD

**Issue by bghira** [bghira/SimpleTuner#800]
```
Traceback (most recent call last):
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/train.py", line 2341, in <module>
    main()
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/train.py", line 1395, in main
    batch = iterator_fn(step, *iterator_args)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/helpers/data_backend/factory.py", line 1222, in random_dataloader_iterator
    return next(chosen_iter)
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 672, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 620, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 288, in __iter__
    for idx in self.sampler:
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/helpers/multiaspect/sampler.py", line 497, in __iter__
    to_yield = self._yield_n_from_exhausted_bucket(
  File "/mnt/6882D52782D4FB10/PrepST/SimpleTuner/helpers/multiaspect/sampler.py", line 184, in _yield_n_from_exhausted_bucket
    samples = random.sample(available_images, k=n)
  File "/usr/lib/python3.10/random.py", line 482, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
```

**Comment by bghira** [comment]
493fa72620d99a3d288efe6ce684c7ad46e8024a
