### ISSUE TITLE
`RuntimeError: Expected A.dtype() == at::kBFloat16 to be true, but got false. ` when training FLUX

### ISSUE THREAD

**Issue by ambocclusion** [bghira/SimpleTuner#804]
When attempting to train FLUX on a RTX 4090 at 4bit using `int4-quanto` I get this error:

RuntimeError: Expected A.dtype() == at::kBFloat16 to be true, but got false. 

<details>

<summary>Full Error</summary>

```
Epoch 1/1000, Steps:   0%|                                                                          | 0/1000 [00:00<?, ?it/s]Expected A.dtype() == at::kBFloat16 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
Traceback (most recent call last):
  File "/home/occlusion/Documents/ai/SimpleTuner/train.py", line 2315, in <module>
    main()
  File "/home/occlusion/Documents/ai/SimpleTuner/train.py", line 1641, in main
    model_pred = transformer(
                 ^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/accelerate/utils/operations.py", line 819, in forward
    return model_forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/accelerate/utils/operations.py", line 807, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 43, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/diffusers/models/transformers/transformer_flux.py", line 400, in forward
    encoder_hidden_states, hidden_states = torch.utils.checkpoint.checkpoint(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/_compile.py", line 31, in inner
    return disable_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 600, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/utils/checkpoint.py", line 488, in checkpoint
    ret = function(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/diffusers/models/transformers/transformer_flux.py", line 395, in custom_forward
    return module(*inputs)
           ^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/diffusers/models/transformers/transformer_flux.py", line 201, in forward
    attn_output, context_attn_output = self.attn(
                                       ^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/diffusers/models/attention_processor.py", line 490, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/diffusers/models/attention_processor.py", line 1800, in __call__
    query = attn.to_q(hidden_states)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/peft/tuners/lora/layer.py", line 544, in forward
    result = self.base_layer(x, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/optimum/quanto/nn/qlinear.py", line 45, in forward
    return torch.nn.functional.linear(input, self.qweight, bias=self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/optimum/quanto/tensor/qtensor.py", line 90, in __torch_function__
    return qfunc(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/optimum/quanto/tensor/qtensor_func.py", line 152, in linear
    return QTensorLinear.apply(input, other, bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/occlusion/.conda/envs/simpletuner/lib/python3.11/site-packages/optimum/quanto/tensor/qtensor_func.py", line 118, in forward
    output = torch._weight_int4pack_mm(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected A.dtype() == at::kBFloat16 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

</details>

Here is my full config:

<details>

<summary>Config</summary>

```RESUME_CHECKPOINT='latest'
DATALOADER_CONFIG='config/multidatabackend.json'
ASPECT_BUCKET_ROUNDING='2'
TRAINING_SEED='42'
USE_EMA='false'
USE_XFORMERS='false'
MINIMUM_RESOLUTION='0'
OUTPUT_DIR='output/models/model1'
USE_DORA='false'
USE_BITFIT='false'
PUSH_TO_HUB='true'
PUSH_CHECKPOINTS='false'
MAX_NUM_STEPS='1000'
NUM_EPOCHS='0'
CHECKPOINTING_STEPS='500'
CHECKPOINTING_LIMIT='2'
HUB_MODEL_NAME='meme1'
DEBUG_EXTRA_ARGS=''
MODEL_TYPE='lora'
MODEL_NAME='black-forest-labs/FLUX.1-dev'
FLUX='true'
KOLORS='false'
STABLE_DIFFUSION_3='false'
STABLE_DIFFUSION_LEGACY='false'
FLUX_LORA_TARGET='all'
TRAIN_BATCH_SIZE='1'
USE_GRADIENT_CHECKPOINTING='true'
GRADIENT_ACCUMULATION_STEPS='1'
CAPTION_DROPOUT_PROBABILITY='0.1'
RESOLUTION_TYPE='pixel'
RESOLUTION='1024'
VALIDATION_SEED='42'
VALIDATION_STEPS='500'
VALIDATION_RESOLUTION='1024x1024'
VALIDATION_GUIDANCE='7.5'
VALIDATION_GUIDANCE_RESCALE='0.0'
VALIDATION_NUM_INFERENCE_STEPS='20'
VALIDATION_PROMPT='a photo of two people in a city street'
ALLOW_TF32='false'
MIXED_PRECISION='bf16'
OPTIMIZER='adamw_bf16'
LEARNING_RATE='1e-4'
LR_SCHEDULE='polynomial'
LR_WARMUP_STEPS='100'
ACCELERATE_EXTRA_ARGS=''
TRAINING_NUM_PROCESSES='1'
TRAINING_NUM_MACHINES='1'
VALIDATION_TORCH_COMPILE='false'
TRAINER_DYNAMO_BACKEND='no'
TRAINER_EXTRA_ARGS='--lora_rank=16 --lr_end=1e-8 --base_model_precision=int4-quanto --compress_disk_cache --base_model_default_dtype=bf16'

```

</details>

<details>

<summary>multidatabackend</summary>

```
[
    {
        "id": "meme1",
        "type": "local",
        "instance_data_dir": "datasets/meme1",
        "crop": true,
        "crop_style": "center",
        "crop_aspect": "square",
        "resolution": 512,
        "resolution_type": "pixel",
        "minimum_image_size": 1.0,
        "prepend_instance_prompt": false,
        "instance_prompt": "couple",
        "only_instance_prompt": false,
        "caption_strategy": "textfile",
        "cache_dir_vae": "cache/vae/meme1",
        "vae_cache_clear_each_epoch": true
    },
    {
        "id": "an example backend for text embeds.",
        "dataset_type": "text_embeds",
        "default": true,
        "type": "local",
        "cache_dir": "cache/text/meme1",
	"disabled": false,
	"write_batch_size": 128
    }
]
```

</details>

I've tried downgrading packages like recommended in this thread https://github.com/bghira/SimpleTuner/issues/721 to no avail.

**Comment by bghira** [comment]
can you try OPTIMIZER=optimi-lion ?

**Comment by ambocclusion** [comment]
`Unknown optimizer requested: optimi-lion`

**Comment by bghira** [comment]
are you on main branch or release?

**Comment by ambocclusion** [comment]
Latest main

**Comment by bghira** [comment]
🤔 but https://github.com/bghira/SimpleTuner/blob/main/helpers/training/optimizer_param.py#L63

**Comment by ambocclusion** [comment]
Huh, odd that line is blank on mine. Let me do a hard reset and I'll get back to you

**Comment by ambocclusion** [comment]
Doh, I might be on release after all. I switched to my Linux boot to try and debug this and didn't switch that one to main. I'll try again on main

**Comment by bghira** [comment]
it's okay - hopefully the main branch works for you. i was using int2-quanto last night after a bunch of fixes. you will have to do `poetry install --no-root` again

**Comment by ambocclusion** [comment]
Still getting the initial error `Expected A.dtype() == at::kBFloat16 to be true, but got false. `

Git status reports this:

```On branch main
Your branch is up to date with 'origin/main'.
```

**Comment by bghira** [comment]
that's with lion?

**Comment by bghira** [comment]
out of curiosity can you test int2-quanto for the same error

**Comment by ambocclusion** [comment]
Yes and a note: I've been deleting the files added to the dataset folder, the output folder, and the cache on each attempt just to 100% make sure my settings are the most recent version. Testing int2 now

**Comment by ambocclusion** [comment]
It looks like training started with int2, thanks!

**Comment by bghira** [comment]
ok int2 is something i've been trying to do extensive testing on, but;
- the cluster i have access to only allows jobs to run 6hrs at a time
- quanto doesn't let you resume training

ergo i can only get so far before it will go no further. however, i was able to resume training the int2 lora on bf16 using more vram and its validations looked fine.

but i don't know what it does to do extended training on int2. if you see any issues, please report those - just know the validations should probably be disabled because we do them on the int2 weights, which looks awful.

**Comment by bghira** [comment]
oh...

> We additionally experimented with qint4 when using bfloat16. This is only applicable to bfloat16 on H100 because other configurations are not supported yet. With qint4, we can expect to see more improvements in memory consumption at the cost of increased inference latency. Increased latency is expected, because there is no native hardware support for int4 computation – the weights are transferred using 4 bits, but computation is still done in bfloat16. The table below shows our results for PixArt-Sigma:

sooo the A100 and H100 are the only places the int4 works. bummer..

**Comment by ambocclusion** [comment]
Ah geez that stinks. Thanks for looking into that. I'll let you know how the results turn out after 1000 steps.

**Comment by bghira** [comment]
you can continue finetuning the int2 lora on int8 for an improvement in quality later.
