### ISSUE TITLE
optimizer got an empty parameter list

### ISSUE THREAD

**Issue by magicwang1111** [bghira/SimpleTuner#843]
2024-08-22 11:22:41,371 [INFO] (TextEmbeddingCache) (Rank: 0) (id=text-embeds) Listing all text embed cache entries
2024-08-22 11:22:41,384 [INFO] (DataBackendFactory) Pre-computing null embedding
2024-08-22 11:22:46,390 [INFO] (DataBackendFactory) Completed loading text embed services.
2024-08-22 11:22:46,390 [INFO] (DataBackendFactory) Configuring data backend: 0822qxxy style
2024-08-22 11:22:46,390 [INFO] (DataBackendFactory) (id=0822qxxy style) Loading bucket manager.
2024-08-22 11:22:46,392 [INFO] (JsonMetadataBackend) Checking for cache file: /mnt/data1/dataset/20240820_Your_name/aspect_ratio_bucket_indices_square.json
2024-08-22 11:22:46,392 [INFO] (JsonMetadataBackend) Pulling cache file from storage
2024-08-22 11:22:46,392 [INFO] (DataBackendFactory) (id=0822qxxy style) Refreshing aspect buckets on main process.
2024-08-22 11:22:46,392 [INFO] (BaseMetadataBackend) Discovering new files...
2024-08-22 11:22:46,417 [INFO] (BaseMetadataBackend) Compressed 488 existing files from 1.
2024-08-22 11:22:46,417 [INFO] (BaseMetadataBackend) No new files discovered. Doing nothing.
2024-08-22 11:22:46,417 [INFO] (BaseMetadataBackend) Statistics: {'total_processed': 0, 'skipped': {'already_exists': 488, 'metadata_missing': 0, 'not_found': 0, 'too_small': 0, 'other': 0}}
2024-08-22 11:22:46,418 [WARNING] (DataBackendFactory) Key config_version not found in the current backend config, using the existing value '2'.
2024-08-22 11:22:46,418 [WARNING] (DataBackendFactory) Key hash_filenames not found in the current backend config, using the existing value 'True'.
2024-08-22 11:22:46,418 [INFO] (DataBackendFactory) Configured backend: {'id': '0822qxxy style', 'config': {'probability': 1.0, 'repeats': 10, 'crop': False, 'crop_aspect': 'square', 'crop_aspect_buckets': None, 'crop_style': 'center', 'disable_validation': False, 'resolution': 1024, 'resolution_type': 'pixel', 'caption_strategy': 'textfile', 'instance_data_dir': '/mnt/data1/dataset/20240820_Your_name/', 'maximum_image_size': None, 'target_downsample_size': None, 'config_version': 2, 'hash_filenames': True}, 'dataset_type': 'image', 'data_backend': <helpers.data_backend.local.LocalDataBackend object at 0x7fd18b8f87f0>, 'instance_data_dir': '/mnt/data1/dataset/20240820_Your_name', 'metadata_backend': <helpers.metadata.backends.json.JsonMetadataBackend object at 0x7fd18b8f82e0>}
(Rank: 0)  | Bucket     | Image Count (per-GPU)
------------------------------
(Rank: 0)  | 1.75       | 488
2024-08-22 11:22:46,419 [INFO] (DataBackendFactory) (id=0822qxxy style) Collecting captions.
2024-08-22 11:22:46,426 [INFO] (DataBackendFactory) (id=0822qxxy style) Initialise text embed pre-computation using the textfile caption strategy. We have 488 captions to process.
2024-08-22 11:22:46,437 [INFO] (DataBackendFactory) (id=0822qxxy style) Completed processing 488 captions.
2024-08-22 11:22:46,437 [INFO] (DataBackendFactory) (id=0822qxxy style) Creating VAE latent cache.
2024-08-22 11:22:46,439 [INFO] (DataBackendFactory) (id=0822qxxy style) Discovering cache objects..
2024-08-22 11:22:46,457 [INFO] (DataBackendFactory) Configured backend: {'id': '0822qxxy style', 'config': {'probability': 1.0, 'repeats': 10, 'crop': False, 'crop_aspect': 'square', 'crop_aspect_buckets': None, 'crop_style': 'center', 'disable_validation': False, 'resolution': 1024, 'resolution_type': 'pixel', 'caption_strategy': 'textfile', 'instance_data_dir': '/mnt/data1/dataset/20240820_Your_name/', 'maximum_image_size': None, 'target_downsample_size': None, 'config_version': 2, 'hash_filenames': True}, 'dataset_type': 'image', 'data_backend': <helpers.data_backend.local.LocalDataBackend object at 0x7fd18b8f87f0>, 'instance_data_dir': '/mnt/data1/dataset/20240820_Your_name', 'metadata_backend': <helpers.metadata.backends.json.JsonMetadataBackend object at 0x7fd18b8f82e0>, 'train_dataset': <helpers.multiaspect.dataset.MultiAspectDataset object at 0x7fd18b8f9270>, 'sampler': <helpers.multiaspect.sampler.MultiAspectSampler object at 0x7fd18b6fdc90>, 'train_dataloader': <torch.utils.data.dataloader.DataLoader object at 0x7fd18b6fe290>, 'text_embed_cache': <helpers.caching.text_embeds.TextEmbeddingCache object at 0x7fd1a90eb670>, 'vaecache': <helpers.caching.vae.VAECache object at 0x7fd18b6700a0>}
Token indices sequence length is longer than the specified maximum sequence length for this model (131 > 77). Running this sequence through the model will result in indexing errors
2024-08-22 11:22:46,462 [WARNING] (helpers.models.flux.pipeline) The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['a high - resolution anime still featuring a young male character with black hair wearing a white school uniform with a green and yellow tie. he appears startled or surprised, with his mouth slightly open and a hand to his cheek, as though he has just witnessed something unexpected.']
2024-08-22 11:23:19,688 [INFO] (validation) Precomputing the negative prompt embed for validations.
2024-08-22 11:23:46,543 [WARNING] (__main__) CUDA, ROCm, or Apple MPS not detected here. We cannot report VRAM reductions.
2024-08-22 11:23:46,543 [INFO] (__main__) Unloading text encoders, as they are not being trained.
2024-08-22 11:23:47,194 [INFO] (__main__) After nuking text encoders from orbit, we freed 0 GB of VRAM. The real memories were the friends we trained a model on along the way.
Fetching 3 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 7367.04it/s]
2024-08-22 11:23:48,845 [INFO] (__main__) Keeping some base model weights in torch.bfloat16.
2024-08-22 11:23:48,846 [INFO] (helpers.training.quantisation) Loading Quanto for LoRA training. This may take a few minutes.
2024-08-22 11:23:48,847 [INFO] (helpers.training.quantisation) Quantising FluxTransformer2DModel. Using int8-quanto.
2024-08-22 11:25:38,922 [INFO] (helpers.training.quantisation) Freezing model.
2024-08-22 11:26:07,251 [INFO] (__main__) Using lycoris training mode
2024-08-22 11:26:07|[LyCORIS]-INFO: Using rank adaptation algo: lokr
2024-08-22 11:26:07|[LyCORIS]-INFO: Use Dropout value: 0.0
2024-08-22 11:26:07|[LyCORIS]-INFO: Create LyCORIS Module
2024-08-22 11:26:07|[LyCORIS]-INFO: create LyCORIS: 0 modules.
2024-08-22 11:26:07|[LyCORIS]-INFO: module type table: {}
2024-08-22 11:26:07,260 [INFO] (__main__) LyCORIS network has been initialized with 0 parameters
2024-08-22 11:26:07,260 [INFO] (__main__) Collected the following data backends: ['text-embeds', '0822qxxy style']
2024-08-22 11:26:07,260 [INFO] (__main__) Loading constant_with_warmup learning rate scheduler with 300 warmup steps
2024-08-22 11:26:07,263 [INFO] (__main__) Learning rate: 0.0003
2024-08-22 11:26:07,264 [INFO] (helpers.training.optimizer_param) cls: <class 'helpers.training.adam_bfloat16.AdamWBF16'>, settings: {'betas': (0.9, 0.999), 'weight_decay': 0.01, 'eps': 1e-06}
2024-08-22 11:26:07,268 [INFO] (__main__) Optimizer arguments, weight_decay=0.01 eps=1e-08, extra_arguments={'lr': 0.0003, 'betas': (0.9, 0.999), 'weight_decay': 0.01, 'eps': 1e-06}
optimizer got an empty parameter list
Traceback (most recent call last):
  File "/mnt/data1/wangxi/SimpleTuner/train.py", line 2526, in <module>
    main()
  File "/mnt/data1/wangxi/SimpleTuner/train.py", line 954, in main
    optimizer = optimizer_class(
  File "/mnt/data1/wangxi/SimpleTuner/helpers/training/adam_bfloat16/__init__.py", line 54, in __init__
    super().__init__(params, defaults)
  File "/home/wangxi/miniconda3/envs/flux/lib/python3.10/site-packages/torch/optim/optimizer.py", line 362, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list

(flux) [wangxi@v100-4 SimpleTuner]$
update to latest code.

**Comment by magicwang1111** [comment]
# Configure these values.

# 'lora' or 'full'
# lora - train a small network for a character or style, or both. quite versatile.
# full - requires lots of vram, trains very slowly, needs a lot of data and concepts.
export MODEL_TYPE='lora'

# SDXL is trained by default, but you will need to enable one of these options for anything else.

# Set this to 'true' if you are training a Stable Diffusion 3 checkpoint.
# Use MODEL_NAME="stabilityai/stable-diffusion-3-medium-diffusers"
export STABLE_DIFFUSION_3=false
# Similarly, this is to train PixArt Sigma (1K or 2K) models.
# Use MODEL_NAME="PixArt-alpha/PixArt-Sigma-XL-2-1024-MS"
export PIXART_SIGMA=false
# For old Stable Diffusion 1.x/2.x models, you'll enable this.
# Use MODEL_NAME="stabilityai/stable-diffusion-2-1"
export STABLE_DIFFUSION_LEGACY=false
# For Kwai-Kolors, enable KOLORS.
# Use MODEL_NAME="kwai-kolors/kolors-diffusers"
export KOLORS=false

# See this document for much more up-to-date information: https://github.com/bghira/SimpleTuner/blob/main/documentation/quickstart/FLUX.md
# Use MODEL_NAME="black-forest-labs/FLUX.1-dev"
export FLUX=true
# When training flux, a value of 1.0 here will KEEP the distillation in-tact.
# Set this value around 3.5 to 4.0 to break distillation and require CFG at inference time.
export FLUX_GUIDANCE_VALUE=1.0
# Training just the 'mmdit' blocks keeps the model very stable, but does not change it a lot.
# Using 'all+ffs' is the other end of the spectrum, and it will LoRA absolutely everything.
# - This mode has limited compatibility with other platforms and might not be the best choice.
# When 'ai-toolkit' is used, it will use the values from Ostris' ai-toolkit, which goes further than 'all'.
# The default, 'all', is a nice conservative style of training that will produce more meaningful results than 'mmdit',
#  and maintain a high degree of compatibility among inference platforms like ComfyUI.
export FLUX_LORA_TARGET=all # options: 'all+ffs', 'all', 'context', 'mmdit', 'ai-toolkit'


# ControlNet model training is only supported when MODEL_TYPE='full'
# See this document for more information: https://github.com/bghira/SimpleTuner/blob/main/documentation/CONTROLNET.md
# DeepFloyd, PixArt, Flux, and SD3 do not currently support ControlNet model training.
export CONTROLNET=false

# DoRA enhances the training style of LoRA, but it will run more slowly at the same rank.
# See: https://arxiv.org/abs/2402.09353
# See: https://github.com/huggingface/peft/pull/1474
export USE_DORA=false

# BitFit freeze strategy for the u-net causes everything but the biases to be frozen.
# This may help retain the full model's underlying capabilities. LoRA is currently not tested/known to work.
#if [[ "$MODEL_TYPE" == "full" ]]; then
#    # When training a full model, we will rely on BitFit to keep the u-net intact.
#    export USE_BITFIT=true
#elif [[ "$MODEL_TYPE" == "lora" ]]; then
#    # LoRA can not use BitFit.
#    export USE_BITFIT=false
#elif [[ "$MODEL_TYPE" == "deepfloyd-full" ]]; then
#    export USE_BITFIT=true
#fi

# Restart where we left off. Change this to "checkpoint-1234" to start from a specific checkpoint.
export RESUME_CHECKPOINT="latest"

# How often to checkpoint. Depending on your learning rate, you may wish to change this.
# For the default settings with 10 gradient accumulations, more frequent checkpoints might be preferable at first.
export CHECKPOINTING_STEPS=100
# This is how many checkpoints we will keep. Two is safe, but three is safer.
export CHECKPOINTING_LIMIT=10

# This is decided as a relatively conservative 'constant' learning rate.
# Adjust higher or lower depending on how burnt your model becomes.
export LEARNING_RATE=8e-7 #@param {type:"number"}

# Using a Huggingface Hub model:
export MODEL_NAME="black-forest-labs/FLUX.1-dev"
# Using a local path to a huggingface hub model or saved checkpoint:
#export MODEL_NAME="/mnt/data1/shared_data/FLUX.1-dev/"

# Make DEBUG_EXTRA_ARGS empty to disable wandb.
export DEBUG_EXTRA_ARGS="--report_to=wandb"
export TRACKER_PROJECT_NAME="${MODEL_TYPE}-training"
export TRACKER_RUN_NAME="simpletuner-sdxl"

# Max number of steps OR epochs can be used. Not both.
export MAX_NUM_STEPS=30000
# Will likely overtrain, but that's fine.
export NUM_EPOCHS=0

# A convenient prefix for all of your training paths.
# These may be absolute or relative paths. Here, we are using relative paths.
# The output will just be in a folder called "output/models" by default.
export DATALOADER_CONFIG="config/multidatabackend.json"
export OUTPUT_DIR="output/models"

# Set this to "true" to push your model to Hugging Face Hub.
export PUSH_TO_HUB="false"
# If PUSH_TO_HUB and PUSH_CHECKPOINTS are both enabled, every saved checkpoint will be pushed to Hugging Face Hub.
export PUSH_CHECKPOINTS="true"
# This will be the model name for your final hub upload, eg. "yourusername/yourmodelname"
# It defaults to the wandb project name, but you can override this here.
export HUB_MODEL_NAME=$TRACKER_PROJECT_NAME

# By default, images will be resized so their SMALLER EDGE is 1024 pixels, maintaining aspect ratio.
# Setting this value to 768px might result in more reasonable training data sizes for SDXL.
export RESOLUTION=1024
# If you want to have the training data resized by pixel area (Megapixels) rather than edge length,
#  set this value to "area" instead of "pixel", and uncomment the next RESOLUTION declaration.
export RESOLUTION_TYPE="pixel"
#export RESOLUTION=1          # 1.0 Megapixel training sizes
# If RESOLUTION_TYPE="pixel", the minimum resolution specifies the smaller edge length, measured in pixels. Recommended: 1024.
# If RESOLUTION_TYPE="area", the minimum resolution specifies the total image area, measured in megapixels. Recommended: 1.
export MINIMUM_RESOLUTION=$RESOLUTION

# How many decimals to round aspect buckets to.
#export ASPECT_BUCKET_ROUNDING=2

# Use this to append an instance prompt to each caption, used for adding trigger words.
# This has not been tested in SDXL.
#export INSTANCE_PROMPT="lotr style "
# If you also supply a user prompt library or `--use_prompt_library`, this will be added to those lists.
export VALIDATION_PROMPT="ethnographic photography of teddy bear at a picnic"
export VALIDATION_GUIDANCE=7.5
# You'll want to set this to 0.7 if you are training a terminal SNR model.
export VALIDATION_GUIDANCE_RESCALE=0.0
# For flux training, you may want to do validation with classifier free guidance.
# You can set this to be >1.0 to do so. If you don't enable CFG, results may be unreliable or look very bad.
# Flux LoRAs have a side-effect of requiring a blank negative prompt, so be sure to set VALIDATION_NEGATIVE_PROMPT="" as well.
export VALIDATION_GUIDANCE_REAL=1.0
# Skip CFG during validation sampling with CFG (flux only, default=2).
export VALIDATION_NO_CFG_UNTIL_TIMESTEP=2
# How frequently we will save and run a pipeline for validations.
export VALIDATION_STEPS=100
export VALIDATION_NUM_INFERENCE_STEPS=30
export VALIDATION_NEGATIVE_PROMPT="blurry, cropped, ugly"
export VALIDATION_SEED=42
export VALIDATION_RESOLUTION=$RESOLUTION


# Adjust this for your GPU memory size. This, and resolution, are the biggest VRAM killers.
export TRAIN_BATCH_SIZE=10
# Accumulate your update gradient over many steps, to save VRAM while still having higher effective batch size:
# effective batch size = ($TRAIN_BATCH_SIZE * $GRADIENT_ACCUMULATION_STEPS).
export GRADIENT_ACCUMULATION_STEPS=4
# How many images to encode at once with the VAE. Can increase VRAM use.
export VAE_BATCH_SIZE=4

# Use any standard scheduler type. constant, polynomial, constant_with_warmup
export LR_SCHEDULE="polynomial"
# A warmup period allows the model and the EMA weights more importantly to familiarise itself with the current quanta.
# For the cosine or sine type schedules, the warmup period defines the interval between peaks or valleys.
# Use a sine schedule to simulate a warmup period, or a Cosine period to simulate a polynomial start.
#export LR_WARMUP_STEPS=$((MAX_NUM_STEPS / 10))
export LR_WARMUP_STEPS=1000

# Caption dropout probability. Set to 0.1 for 10% of captions dropped out. Set to 0 to disable.
# You may wish to disable dropout if you want to limit your changes strictly to the prompts you show the model.
# You may wish to increase the rate of dropout if you want to more broadly adopt your changes across the model.
export CAPTION_DROPOUT_PROBABILITY=0.1

export METADATA_UPDATE_INTERVAL=65

# How many workers to use for VAE caching.
export MAX_WORKERS=32
# Read and write batch sizes for VAE caching.
export READ_BATCH_SIZE=25
export WRITE_BATCH_SIZE=64
# How many images to process at once (resize, crop, transform) during VAE caching.
export IMAGE_PROCESSING_BATCH_SIZE=32
# When using large batch sizes, you'll need to increase the pool connection limit.
export AWS_MAX_POOL_CONNECTIONS=128
# For very large systems, setting this can reduce CPU overhead of torch spawning an unnecessarily large number of threads.
export TORCH_NUM_THREADS=8

# If this is set, any images that fail to open will be DELETED to avoid re-checking them every time.
export DELETE_ERRORED_IMAGES=0
# If this is set, any images that are too small for the minimum resolution size will be DELETED.
export DELETE_SMALL_IMAGES=0

# Bytedance recommends these be set to "trailing" so that inference and training behave in a more congruent manner.
# To follow the original SDXL training strategy, use "leading" instead, though results are generally worse.
export TRAINING_SCHEDULER_TIMESTEP_SPACING="trailing"
export INFERENCE_SCHEDULER_TIMESTEP_SPACING="trailing"

# Removing this option or unsetting it uses vanilla training. Setting it reweights the loss by the position of the timestep in the noise schedule.
# A value "5" is recommended by the researchers. A value of "20" is the least impact, and "1" is the most impact.
export MIN_SNR_GAMMA=5

# Set this to an explicit value of "false" to disable Xformers. Probably required for AMD users.
export USE_XFORMERS=false

# There's basically no reason to unset this. However, to disable it, use an explicit value of "false".
# This will save a lot of memory consumption when enabled.
export USE_GRADIENT_CHECKPOINTING=true

##
# Options below here may require a bit more complicated configuration, so they are not simple variables.
##

# TF32 is great on Ampere or Ada, not sure about earlier generations.
export ALLOW_TF32=true

# AdamWBF16 is the default optimizer, but it does not support non-bf16 training.
# All other optimi optimizers should work with any precision level.
# Choices: adamw_bf16, optimi-stableadamw, optimi-adamw, optimi-lion, optimi-radam, optimi-ranger, optimi-adan, optimi-adam, optimi-sgd
export OPTIMIZER="adamw_bf16"


# EMA is a strong regularisation method that uses a lot of extra VRAM to hold two copies of the weights.
# This is worthwhile on large training runs, but not so much for smaller training runs.
# NOTE: EMA is not currently applied to LoRA.
export USE_EMA=false
export EMA_DECAY=0.999

export TRAINER_EXTRA_ARGS=""
## For offset noise training:
# Not recommended for terminal SNR models.
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --offset_noise --noise_offset=0.02"

## For terminal SNR training:
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --prediction_type=v_prediction --rescale_betas_zero_snr"
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --training_scheduler_timestep_spacing=trailing --inference_scheduler_timestep_spacing=trailing"

# Reproducible training. Set to -1 to disable.
export TRAINING_SEED=42

# Mixed precision is the best. You honestly might need to YOLO it in fp16 mode for Google Colab type setups.
export MIXED_PRECISION="bf16"                # Might not be supported on all GPUs. fp32 will be needed for others.
export PURE_BF16=true

# This has to be changed if you're training with multiple GPUs.
export TRAINING_NUM_PROCESSES=1
export TRAINING_NUM_MACHINES=1
export ACCELERATE_EXTRA_ARGS=""                          # --multi_gpu or other similar flags for huggingface accelerate

# Some models just simply won't work with torch.compile or will not experience any speedup. YMMV.
export TRAINING_DYNAMO_BACKEND='no'                # or 'no' if you want to disable torch compile in case of performance issues or lack of support (eg. AMD)

# Workaround a bug in the tokenizers platform.
export TOKENIZERS_PARALLELISM=false

**Comment by bghira** [comment]
2024-08-22 11:26:07|[LyCORIS]-INFO: create LyCORIS: 0 modules.
2024-08-22 11:26:07|[LyCORIS]-INFO: module type table: {}

**Comment by magicwang1111** [comment]
> 2024-08-22 11:26:07|[LyCORIS]-INFO: create LyCORIS: 0 modules.2024-08-22 11：26：07|[LyCORIS]-INFO：创建 LyCORIS：0 个模块。 2024-08-22 11:26:07|[LyCORIS]-INFO: module type table: {}2024-08-22 11：26：07|[LyCORIS]-INFO： 模块类型表： {}
> 
> bad lycoris config 错误的 lycoris 配置

{
    "algo": "lora",
    "multiplier": 1.0,
    "linear_dim": 64,
    "linear_alpha": 1
  }
  
  i use your example lycoris config

**Comment by mhirki** [comment]
I guess lycoris_config.json.example is outdated already. Here's a working lycoris_config.json produced by the configure.py script:
```json
{
    "algo": "lokr",
    "multiplier": 1.0,
    "linear_dim": 10000,
    "linear_alpha": 1,
    "factor": 16,
    "apply_preset": {
        "target_module": [
            "Attention",
            "FeedForward"
        ],
        "module_algo_map": {
            "Attention": {
                "factor": 16
            },
            "FeedForward": {
                "factor": 8
            }
        }
    }
}
```
