### ISSUE TITLE
Weird precision error

### ISSUE THREAD

**Issue by tristanwqy** [bghira/SimpleTuner#854]
I got this error
```shell
2024-08-23 10:01:13,463 [INFO] (__main__) Moving the diffusion transformer to GPU in torch.bfloat16 precision.
2024-08-23 10:01:13,482 [WARNING] (__main__) xformers is not enabled, as it is incompatible with this model type.
2024-08-23 10:01:13,482 [INFO] (__main__) 
***** Running training *****
-  Num batches = 27179
-  Num Epochs = 20
  - Current Epoch = 1
-  Total train batch size (w. parallel, distributed & accumulation) = 128
  - Instantaneous batch size per device = 8
  - Gradient Accumulation steps = 4
-  Total optimization steps = 135900
-  Total optimization steps remaining = 135900
Epoch 1/20, Steps:   0%|                                                   | 0/135900 [00:33<?, ?it/s, lr=0, step_loss=0.394]Expected BFloat16, got FloatExpected BFloat16, got Float
Expected BFloat16, got Float

Expected BFloat16, got Float
Traceback (most recent call last):
  File "/home/ubuntu/SimpleTuner/train.py", line 2526, in <module>
    main()
  File "/home/ubuntu/SimpleTuner/train.py", line 2008, in main
    accelerator.backward(loss)
  File "/home/ubuntu/miniconda3/envs/simple_tuner/lib/python3.11/site-packages/accelerate/accelerator.py", line 2159, in backward
    loss.backward(**kwargs)
  File "/home/ubuntu/miniconda3/envs/simple_tuner/lib/python3.11/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/home/ubuntu/miniconda3/envs/simple_tuner/lib/python3.11/site-packages/torch/autograd/__init__.py", line 289, in backward
    _engine_run_backward(
  File "/home/ubuntu/miniconda3/envs/simple_tuner/lib/python3.11/site-packages/torch/autograd/graph.py", line 768, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected BFloat16, got Float

```
and here is my config file
```config
# Adjust this for your GPU memory size. This, and resolution, are the biggest VRAM killers.
export TRAIN_BATCH_SIZE=8
# Accumulate your update gradient over many steps, to save VRAM while still having higher effective batch size:
# effective batch size = ($TRAIN_BATCH_SIZE * $GRADIENT_ACCUMULATION_STEPS).
export GRADIENT_ACCUMULATION_STEPS=4
# How many images to encode at once with the VAE. Can increase VRAM use.
export VAE_BATCH_SIZE=16

# Use any standard scheduler type. constant, polynomial, constant_with_warmup
export LR_SCHEDULE="polynomial"
# A warmup period allows the model and the EMA weights more importantly to familiarise itself with the current quanta.
# For the cosine or sine type schedules, the warmup period defines the interval between peaks or valleys.
# Use a sine schedule to simulate a warmup period, or a Cosine period to simulate a polynomial start.
#export LR_WARMUP_STEPS=$((MAX_NUM_STEPS / 10))
export LR_WARMUP_STEPS=1000

# Caption dropout probability. Set to 0.1 for 10% of captions dropped out. Set to 0 to disable.
# You may wish to disable dropout if you want to limit your changes strictly to the prompts you show the model.
# You may wish to increase the rate of dropout if you want to more broadly adopt your changes across the model.
export CAPTION_DROPOUT_PROBABILITY=0.1

export METADATA_UPDATE_INTERVAL=65

# How many workers to use for VAE caching.
export MAX_WORKERS=32
# Read and write batch sizes for VAE caching.
export READ_BATCH_SIZE=64
export WRITE_BATCH_SIZE=64
# How many images to process at once (resize, crop, transform) during VAE caching.
export IMAGE_PROCESSING_BATCH_SIZE=64
# When using large batch sizes, you'll need to increase the pool connection limit.
export AWS_MAX_POOL_CONNECTIONS=128
# For very large systems, setting this can reduce CPU overhead of torch spawning an unnecessarily large number of threads.
export TORCH_NUM_THREADS=64

# If this is set, any images that fail to open will be DELETED to avoid re-checking them every time.
export DELETE_ERRORED_IMAGES=0
# If this is set, any images that are too small for the minimum resolution size will be DELETED.
export DELETE_SMALL_IMAGES=0

# Bytedance recommends these be set to "trailing" so that inference and training behave in a more congruent manner.
# To follow the original SDXL training strategy, use "leading" instead, though results are generally worse.
export TRAINING_SCHEDULER_TIMESTEP_SPACING="trailing"
export INFERENCE_SCHEDULER_TIMESTEP_SPACING="trailing"

# Removing this option or unsetting it uses vanilla training. Setting it reweights the loss by the position of the timestep in the noise schedule.
# A value "5" is recommended by the researchers. A value of "20" is the least impact, and "1" is the most impact.
export MIN_SNR_GAMMA=5

# Set this to an explicit value of "false" to disable Xformers. Probably required for AMD users.
export USE_XFORMERS=true

# There's basically no reason to unset this. However, to disable it, use an explicit value of "false".
# This will save a lot of memory consumption when enabled.
export USE_GRADIENT_CHECKPOINTING=true

##
# Options below here may require a bit more complicated configuration, so they are not simple variables.
##

# TF32 is great on Ampere or Ada, not sure about earlier generations.
export ALLOW_TF32=true

# AdamWBF16 is the default optimizer, but it does not support non-bf16 training.
# All other optimi optimizers should work with any precision level.
# Choices: adamw_bf16, optimi-stableadamw, optimi-adamw, optimi-lion, optimi-radam, optimi-ranger, optimi-adan, optimi-adam, optimi-sgd
export OPTIMIZER="optimi-adamw"


# EMA is a strong regularisation method that uses a lot of extra VRAM to hold two copies of the weights.
# This is worthwhile on large training runs, but not so much for smaller training runs.
# NOTE: EMA is not currently applied to LoRA.
export USE_EMA=false
export EMA_DECAY=0.999

export TRAINER_EXTRA_ARGS=""
export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --lora_rank=64"
export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --max_grad_norm=1.0 --gradient_precision=fp32"
# x-flux only trains the mmdit blocks but you can change lora_target to all or context to experiment.
export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --base_model_default_dtype=bf16 --lora_init_type=default"
## For offset noise training:
# Not recommended for terminal SNR models.
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --offset_noise --noise_offset=0.02"

## For terminal SNR training:
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --prediction_type=v_prediction --rescale_betas_zero_snr"
#export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --training_scheduler_timestep_spacing=trailing --inference_scheduler_timestep_spacing=trailing"

# Reproducible training. Set to -1 to disable.
export TRAINING_SEED=42

# Mixed precision is the best. You honestly might need to YOLO it in fp16 mode for Google Colab type setups.
export MIXED_PRECISION="bf16"                # Might not be supported on all GPUs. fp32 will be needed for others.
export PURE_BF16=false

# This has to be changed if you're training with multiple GPUs.
export TRAINING_NUM_PROCESSES=4
export TRAINING_NUM_MACHINES=1
export DEEPSPEED_CONFIG_FILE="config/ds_config.yaml"
#export ACCELERATE_EXTRA_ARGS="--config_file ${DEEPSPEED_CONFIG_FILE}"
# --multi_gpu or other similar flags for huggingface accelerate

# Some models just simply won't work with torch.compile or will not experience any speedup. YMMV.
export TRAINING_DYNAMO_BACKEND='no'                # or 'no' if you want to disable torch compile in case of performance issues or lack of support (eg. AMD)

# Workaround a bug in the tokenizers platform.
export TOKENIZERS_PARALLELISM=false
```

**Comment by bghira** [comment]
```
export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --max_grad_norm=1.0 --gradient_precision=fp32"
```

it is gradient precision set to fp32
