### ISSUE TITLE
ValueError: Invalid LoRA checkpoint.

### ISSUE THREAD

**Issue by DoiryCool** [bghira/SimpleTuner#883]
When I loaded flux lora checkpoint,It shows `ValueError: Invalid LoRA checkpoint.`

```bash
Traceback (most recent call last):
  File "/userdata136/FLUX.1-dev/tr.py", line 5, in <module>
    pipe.load_lora_weights('/root/user/FLUX.1-dev/loras/pytorch_lora_weights.safetensors', weight_name="pytorch_lora_weights.safetensors")
  File "/root/miniconda3/lib/python3.9/site-packages/diffusers/loaders/lora_pipeline.py", line 1639, in load_lora_weights
    raise ValueError("Invalid LoRA checkpoint.")
ValueError: Invalid LoRA checkpoint.
```
The code is:
```python
import torch
from diffusers import FluxPipeline, FluxTransformer2DModel

pipe = FluxPipeline.from_pretrained("/root/user/FLUX.1-dev", torch_dtype=torch.bfloat16)
pipe.load_lora_weights('/root/user/FLUX.1-dev/loras', weight_name="pytorch_lora_weights.safetensors")
pipe=pipe.to("cuda")

prompt = ""
image = pipe(
    prompt,
    height=1344,
    width=768,
    guidance_scale=3.5,
    output_type="pil",
    num_inference_steps=50,
    max_sequence_length=512,
    generator=torch.Generator(device="cuda").manual_seed(0),
    joint_attention_kwargs={"scale": 1.0}
).images[0]
image.save("flux-dev.png")
```
Can I ask what's wrong?

**Comment by DoiryCool** [comment]
![Screenshot from 2024-08-27 15-23-03](https://github.com/user-attachments/assets/704bb466-4a89-4391-8eab-356ff7536641)
Is the error because of LyCORIS not support yet?

**Comment by bghira** [comment]
use the model card code example

**Comment by xcltql666** [comment]
Hi，could you please share the example code with me?
