### ISSUE TITLE
Macbook M3 for tuning? (transformers_flux and then _scaled_dot_product_attention_math_for_mps issues)

### ISSUE THREAD

**Issue by defertoexpertise** [bghira/SimpleTuner#937]
Things looked promising but.. not lol

Got an error that in transformers/transformers_flux.py  

line 41... scale = torch.arange(0, dim, 2, dtype=torch.float64, device=pos.device) / dim

Wouldn't work because MPS doesn't support float64... so of course i swapped it to float32 in the dependency lol. 

After changing the line in transformers (ya i know dirty me) from float64 to float32 just to test what the next break would be... i ran into ....

```Traceback (most recent call last):
  File "/Users/ME/AI/SimpleTuner/train.py", line 2632, in <module>
    main()
  File "/Users/ME/AI/SimpleTuner/train.py", line 2079, in main
    accelerator.backward(loss)
  File "/Users/ME/AI/SimpleTuner/.venv/lib/python3.11/site-packages/accelerate/accelerator.py", line 2159, in backward
    loss.backward(**kwargs)
  File "/Users/ME/AI/SimpleTuner/.venv/lib/python3.11/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/Users/ME/AI/SimpleTuner/.venv/lib/python3.11/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/Users/ME/AI/SimpleTuner/.venv/lib/python3.11/site-packages/torch/autograd/graph.py", line 817, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass```
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: derivative for aten::_scaled_dot_product_attention_math_for_mps is not implemented

Which i couldn't find any workaround for... Anyone on the project have a mac that can maybe give me a tip or is it hopeless.

**Comment by bghira** [comment]
welp, i've already explained that MPS and Flux don't mix. but any other model works. MPS just destroys the model for Flux.
