### ISSUE TITLE
value should be one of int, float, str, bool, or torch.Tensor

### ISSUE THREAD

**Issue by piotr-sikora-v** [bghira/SimpleTuner#940]
I have new pure installation.
I do everything via quick start and I have this error:

```
2024-09-04 23:45:31,637 [INFO] (SaveHookManager) Denoiser class set to: UNet2DConditionModel.
2024-09-04 23:45:31,637 [INFO] (SaveHookManager) Pipeline class set to: StableDiffusionXLPipeline.
2024-09-04 23:45:31,637 [INFO] (helpers.training.trainer) Checkpoint 'latest' does not exist. Starting a new training run.
2024-09-04 23:45:31,639 [INFO] (helpers.training.trainer) Loading our accelerator...
value should be one of int, float, str, bool, or torch.Tensor
Traceback (most recent call last):
  File "/data1/foss/SimpleTuner/train.py", line 50, in <module>
    trainer.init_trackers()
  File "/data1/foss/SimpleTuner/helpers/training/trainer.py", line 1328, in init_trackers
    self.accelerator.init_trackers(
  File "/data1/foss/SimpleTuner/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 685, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)
  File "/data1/foss/SimpleTuner/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 2586, in init_trackers
    tracker.store_init_configuration(config)
  File "/data1/foss/SimpleTuner/venv/lib/python3.10/site-packages/accelerate/tracking.py", line 79, in execute_on_main_process
    return PartialState().on_main_process(function)(self, *args, **kwargs)
  File "/data1/foss/SimpleTuner/venv/lib/python3.10/site-packages/accelerate/tracking.py", line 211, in store_init_configuration
    self.writer.add_hparams(values, metric_dict={})
  File "/data1/foss/SimpleTuner/venv/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 330, in add_hparams
    exp, ssi, sei = hparams(hparam_dict, metric_dict, hparam_domain_discrete)
  File "/data1/foss/SimpleTuner/venv/lib/python3.10/site-packages/torch/utils/tensorboard/summary.py", line 318, in hparams
    raise ValueError(
ValueError: value should be one of int, float, str, bool, or torch.Tensor

```

I try to SDXL full finetune

**Comment by bghira** [comment]
it is because of tensorboard. set --report_to=wandb or none

**Comment by punkie909** [comment]
i ran into a similar error message with tensorboard enabled

a hotfix i did was adding `delattr(public_args, "vae_kwargs")` under here https://github.com/bghira/SimpleTuner/blob/e4a0adf9326960489c50abdbadb1f45fb1ef92e3/helpers/training/trainer.py#L1321

when looking at it `vae_kwargs` is a dict and not one of the types it would like. but idk if this breaks something else

maybe this helps in this case

**Comment by piotr-sikora-v** [comment]
Yes, that help! Thanks!
